### ISSUE TITLE
Headless server version？

### ISSUE THREAD

**Issue by aoliao12138** [NVlabs/instant-ngp#10]
Hello, instant-ngp is a really brilliant work. I really appreciate it. I wonder whether this program can be run on a headless server? Thank you very much!

**Comment by Tom94** [comment]
It can!

The Python bindings don't spawn a GUI by default and the bundled `scripts/run.py` script only does so when provided with the `--gui` parameter.

Further, you can build the project without even linking OpenGL/GLFW by disabling the `NGP_BUILD_WITH_GUI` CMake option (on by default). Caveat: this last feature is somewhat experimental still.

**Comment by pwais** [comment]
there should be a way to remote using either some of the existing ImGui remoting options: 
 * https://github.com/ocornut/imgui/wiki/Useful-Extensions#remoting

Failing that, perhaps VNC / nomachine / x11 inside docker ( https://l10nn.medium.com/running-x11-applications-with-docker-75133178d090 )

**Comment by Tom94** [comment]
Consolidating with #6 due to the close relation
