### ISSUE TITLE
col2nerf.py

### ISSUE THREAD

**Issue by kenoben** [NVlabs/instant-ngp#101]
I can't get transform.json because of this error
![explorer_tNiSqZPSMG](https://user-images.githubusercontent.com/64289522/151723656-2d59f49e-2bf9-4d22-a78d-87102a746194.png)
r

**Comment by subzerofun** [comment]
The python script is called "colmap2nerf.py" not "col2nerf.py".

**Comment by Tom94** [comment]
Hi there, it looks like your python installation is missing some of the dependencies listed in `requirements.txt` (the error message calls out `numpy` in particular). If you still have problems once these are installed, please feel free to re-open the issue.
