### ISSUE TITLE
Uncaught exception: image not found: data\nerf\caithness_playground\images\DJI_0001.JPG

### ISSUE THREAD

**Issue by LiamGallagher737** [NVlabs/instant-ngp#1019]
I am keep getting the error `Uncaught exception: image not found: data\nerf\caithness_playground\images\DJI_0001.JPG`. I am able to use the fox example just fine. The following is the folder layout

```
📦data
 ┣ 📂nerf
 ┃ ┣ 📂caithness_playground
 ┃      ┣ 📜 transforms.json
 ┃      ┗ 📂images
 ┃           ┗ 📜 DJI_0001.JPG and so on
 ┃ ┗ 📂fox
 ┃      ┣ 📜 transforms.json
 ┃      ┗ 📂images
 ┃           ┗ 📜 0001.jpg and so on
 ┣ 📂image
 ┗ 📂sdf
```

I basically copied the fox. Here is an example of the `transforms.json` file under `caithness_playground`.

```json
"file_path": "images/DJI_0001.JPG",
"sharpness": 1152.5914597297576,
"transform_matrix": [
  [
    -0.9916970487839755,
    0.08713320324435979,
    -0.09457678553492607,
    -1.2197057598759073
  ],
  [
    -0.1285445375567598,
    -0.6925070614267528,
    0.7098663759740309,
    1.6383120671969031
  ],
  [
    -0.0036421606158977284,
    0.7161297192446148,
    0.6979577063958596,
    3.2733906350093025
  ],
  [
    0.0,
    0.0,
    0.0,
    1.0
  ]
]
```

And I am trying to run the program using the following command in an Anaconda Prompt.

```
.\build\testbed --scene data\nerf\caithness_playground
```

Here is an image.

![image](https://user-images.githubusercontent.com/86995276/196152218-0b113415-ad91-46a0-818b-b887ab2d1b18.png)

And the result when ran.

![image](https://user-images.githubusercontent.com/86995276/196152315-4c035e0c-136f-4f0c-af77-33aebcf56feb.png)

I'd greatly appreciate any help I can get towards getting this to work. Thank you in advanced.

**Comment by barney2074** [comment]
wondering if it is a permissions thing?
i.e what user did you run colmap2nerf as, or did you copy the files from somewhere else

**Comment by LiamGallagher737** [comment]
I am following along with [this](https://youtu.be/8pfPUN8NyZE?t=1504) tutorial. I did not copy the files from somewhere else I used the `colmap2nerf.py` script. The following is the command I used in Anaconda.
```
python scripts/colmap2nerf.py --colmap_matcher exhaustive --run_colmap --aabb_scale 16 --images <images path>
```

**Comment by LiamGallagher737** [comment]
I've found that if I replace the image `DJI_0001.JPG` with one of the fox images renamed to the same then the error changes to the following.

```
Uncaught exception: image not found: data\nerf\caithness_park\images\DJI_0002.JPG   
```

So, the issue must be with my images. The following is the metadata for one of my images. I left out the security and previous versions tabs as they are the same as the fox image.

![image](https://user-images.githubusercontent.com/86995276/196594050-89ad6d57-5a66-4e57-bff1-a9ac6108d1cc.png)

![image](https://user-images.githubusercontent.com/86995276/196594151-eb1ba75a-0af1-49ee-97e4-8f481d4d2a86.png)

![image](https://user-images.githubusercontent.com/86995276/196594187-f65ce6d6-40fb-44e3-9996-d4b314721a52.png)

![image](https://user-images.githubusercontent.com/86995276/196594207-f8313f79-0e2d-4cf8-b6a5-8e316658b737.png)

![image](https://user-images.githubusercontent.com/86995276/196594232-96b99432-82d7-48f7-9b3b-e68a8e66b3b3.png)

![image](https://user-images.githubusercontent.com/86995276/196594248-871935c9-2e77-4d9c-b75a-c7d3618910f5.png)

**Comment by barney2074** [comment]
your images are pretty big, but I don't think it is the issue here

Some Python libraries such as OpenCV have problems with non-ascii characters in filenames
Try renaming your files/folder. Suggest renaming it to something, then back to how it was

**Comment by Tom94** [comment]
Hi, this sounds like STBI, the software instant-ngp is using to load images, can't load your JPG files. I just pushed a change to the code that should give you a more descriptive error message -- perhaps it sheds light on how the camera can be configured to produce compatible jpg images.

In the end, your best bet is probably to re-encode the images yourself using a known working tool (e.g. Python's imageio or PIL).

**Comment by LiamGallagher737** [comment]
Turns out the images were too big. I resized them to 2000 x 1500 and it worked fine thanks for the help @barney2074.
