### ISSUE TITLE
modeling only inside the unit cube

### ISSUE THREAD

**Issue by arielbenitah** [NVlabs/instant-ngp#102]
Hi,  really impressive work! Thanks a lot for sharing it!
I was wondering if there is a possibility to run the model **only** inside the cube.
Leaving unmodeled all parts outside it.
Thanks again

**Comment by Tom94** [comment]
Hi there, the answer to your question depends a little on interpretation -- I can see two -- but it is "yes" in both cases.

1. Do you mean __training__ the model just in the unit cube? This is possible by specifying `"aabb_scale": 1` in the corresponding `.json` training data. However, if the scene actually extends outside of this cube, the model will come up with strange ways to distribute the outside information on the surface of the cube. _So I would not recomment doing this._
2. Do you mean __visualizing__ the trained model just in the unit cube? If so, you can achieve this by setting the "Crop aabb" setting in the GUI to the appropriate region (see the screenshot). There also is a Python binding for this:
```
testbed.render_aabb = [[0.0, 0.0, 0.0], [1.0, 1.0, 1.0]]
```

![image](https://user-images.githubusercontent.com/4923655/151962174-46d78f41-a691-4632-9c44-0522ee570f2c.png)

**Comment by arielbenitah** [comment]
Hi @Tom94 , woow, thanks a lot for your crystal clear and detailed explanations of my not so clear question ;-)
Your answers gave me even better understanding of how this unit cube is working.

In fact I'm specifically interested by your first answer (training the model). My scene indeed extends outside the unit
cube. Is there any possibility to prevent the program distributing outside information on the surface of the unit cube? maybe by limiting the rays **within the unit cube**?

Thanks a lot

**Comment by Tom94** [comment]
I don't think this can be done. Setting `"aabb_scale": 1` indeed constrains rays to the unit cube, however the supervision by training images necessarily causes the model to try capturing all detail within the bounded domain it has to work with.

For this to be possible, the training data would have to be 3-dimensional (e.g. [OpenEXR deep images](https://www.openexr.com/documentation/InterpretingDeepPixels.pdf)) and the training algorithm would have to be modified to only try to fit colors corresponding to the ray segments that are actually trained.

**Comment by arielbenitah** [comment]
I understand. Thanks a lot for the detailed answer :-)

**Comment by hoanhle** [comment]
@Tom94 Is there a way for me to limit the `aabb` even further? I tried to edit `m_aabb` in `testbed_nerf.cu` but i don't think it's working like it should. I assume there is some logic somewhere that assume  the positions must fall within 0 to 1?


```
	m_aabb = BoundingBox{vec3(0.442f,  0.528f,  0.6525f), vec3(0.442f,  0.528f,  0.6525f)};
	vec3 inflation_amount = vec3(0.5f * std::min(1 << (NERF_CASCADES()-1), m_nerf.training.dataset.aabb_scale),  0.353f * std::min(1 << (NERF_CASCADES()-1), m_nerf.training.dataset.aabb_scale),   0.1f * std::min(1 << (NERF_CASCADES()-1), m_nerf.training.dataset.aabb_scale));
	m_aabb.inflate(inflation_amount);

	// m_aabb = BoundingBox{vec3(0.5f), vec3(0.5f)};
	// m_aabb.inflate(0.5f * std::min(1 << (NERF_CASCADES()-1), m_nerf.training.dataset.aabb_scale));
```
