### ISSUE TITLE
error including <GL/gl.h>

### ISSUE THREAD

**Issue by seokwon-lee** [NVlabs/instant-ngp#1024]
In file included from /home/ipa/seokwon/mywork/NeRF/instant-ngp/src/render_buffer.cu:35:
/usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_gl_interop.h:66:10: fatal error: GL/gl.h: No such file or directory
   66 | #include <GL/gl.h>
      |          ^~~~~~~~~
compilation terminated.

I tried
 cmake . -B build -DNGP_BUILD_WITH_GUI=off
Can anybody help?
CUDA version is 11.7

**Comment by Tom94** [comment]
Hi, can you pull the latest code and try again?
