### ISSUE TITLE
export of 3D model is not clear in-fact i bumped marching cube resolution from 250 to 500 

### ISSUE THREAD

**Issue by fahimsun** [NVlabs/instant-ngp#103]
I am trying to export 3d model, with --save_mesh functionality, the export of 3D model is not clear in-fact i bumped marching cube resolution from 250 to 500. Still not much improvement.
![MeshLab_2021_10](https://user-images.githubusercontent.com/32779838/151830978-865ef3ee-8625-41d2-9953-f7e7ef12969d.jpg)

**Comment by Tom94** [comment]
Hi there, the mesh export functionality is not really intended as a robust, high-quality mesh reconstruction technique. Rather, we're providing it as an aid to researchers to easily extract level sets from their NeRF models.

Reconstructing high-quality meshes from 2D viewpoints is a difficult ongoing area of research and unfortunately far from solved -- if this is what you're after, I'd recommend checking out e.g. [NeuS](https://arxiv.org/pdf/2106.10689.pdf) or, if you're after relightable meshes, [nvdiffrec](https://nvlabs.github.io/nvdiffrec/).

**Comment by ttsesm** [comment]
@fahimsun check on this recent work as well https://formyfamily.github.io/NeROIC/. They mention that will make the code available (hopefully soon).

**Comment by im-pain** [comment]
@fahimsun @Tom94 hi excuse me, how you can adjust an get the texture file, by default it give me a noise texture in .tga format, and the mesh is .obj format so no textures embedded

**Comment by Evilom** [comment]
Which platform are you operating on, the model I get on the window is very, very bad

**Comment by Tom94** [comment]
There's no code available yet, but a future release is planned.
