### ISSUE TITLE
error: argument of type "char" is incompatible with parameter of type "ImGuiKey".

### ISSUE THREAD

**Issue by Hao4977** [NVlabs/instant-ngp#1035]
Many errors occurred when building in "testbed.cu".

![image](https://user-images.githubusercontent.com/69423227/197535945-8ecdb58f-486c-456b-a6ed-ae3b8b8d54d7.png)

How to fix it?I would appreciate it if someone can help me.

**Comment by JiayingGaoo** [comment]
same problem

**Comment by Hao4977** [comment]
> same problem

I have solved it by re-downloading the imgui which is in depencies file.
