### ISSUE TITLE
Couldn't find CUDA library root

### ISSUE THREAD

**Issue by WXuanyang** [NVlabs/instant-ngp#104]
I followed the instruction to install and added CUDA installation to my PATH, but the CMake still couldn't find CUDA
![image](https://user-images.githubusercontent.com/69446297/152066291-3615fe79-61d8-4c23-bf22-f08fa647438e.png)
nvcc -V and nvidia-smi works just fine
![image](https://user-images.githubusercontent.com/69446297/152066137-0394b7c2-7868-4667-ace1-534e4200308c.png)
What could be the problem?
environment:
Ubuntu 18.04
CUDA 11.4
CMake 3.22

**Comment by WXuanyang** [comment]
And here's the output of the log

The system is: Linux - 5.4.0-96-generic - x86_64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: /usr/bin/cc 
Build flags: 
Id flags:  

The output was:
0


Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"

The C compiler identification is GNU, found in "/home/wxy/3D/instant-ngp/build/CMakeFiles/3.22.1/CompilerIdC/a.out"

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler: /usr/bin/c++ 
Build flags: 
Id flags:  

The output was:
0


Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"

The CXX compiler identification is GNU, found in "/home/wxy/3D/instant-ngp/build/CMakeFiles/3.22.1/CompilerIdCXX/a.out"

Checking whether the CUDA compiler is NVIDIA using "" matched "nvcc: NVIDIA \(R\) Cuda compiler driver":
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

**Comment by teachyourselfcoding** [comment]
what was the issue?

**Comment by robin-programmer** [comment]
the same error on ubuntu 22.04
