### ISSUE TITLE
When to add mask images?

### ISSUE THREAD

**Issue by JiayingGaoo** [NVlabs/instant-ngp#1049]
I have prepared the mask images due to ReadMe.md. But i do not sure when to load them. I put the mask images into train_dir and then run: python scripts/colmap2nerf.py --colmap_matcher exhaustive --run_colmap --aabb_scale 16 --images ./train_dir. Is that right?

**Comment by dozeri83** [comment]
@JiayingGaoo 
note that the mask images have to have specific name
https://github.com/NVlabs/instant-ngp#:~:text=Q%3A%20How%20to,indicate%20masked%2Daway%20regions.

it has nothing to do with colmap2nerf script. The nerf loader automatically loads them.

(Look for "loaded dynamic masks" in the log)

**Comment by JiayingGaoo** [comment]
> @JiayingGaoo note that the mask images have to have specific name https://github.com/NVlabs/instant-ngp#:~:text=Q%3A%20How%20to,indicate%20masked%2Daway%20regions.
> 
> it has nothing to do with colmap2nerf script. The nerf loader automatically loads them.
> 
> (Look for "loaded dynamic masks" in the log)

Thanks! it works.
