### ISSUE TITLE
Training view error and exposure values are always 0

### ISSUE THREAD

**Issue by jhurlbut** [NVlabs/instant-ngp#107]
I'm not sure if this is a bug or if my training views have no error but the values in the testbed graph are always 0 as I cycle through the training view slider

**Comment by Tom94** [comment]
Training errors (and corresponding error maps) were only accumulated when the `sample focal plane ~error` option was enabled to save computation.

Again, this is something that's confusing. I've benchmarked the overhead again, which seems negligibly small. Seems like this was a premature optimization. So I've enabled error accumulation _always_ with the latest commit. You should now see the values correctly reflected. (https://github.com/NVlabs/instant-ngp/commit/1852d68020b3f39d8110f12f60644e89c7659d7b)

**Comment by Tom94** [comment]
As for exposure values: those only differ from 0 when `Train exposure` is enabled.
