### ISSUE TITLE
How to export the result to a 3d model and display it in a web page

### ISSUE THREAD

**Issue by solracmendo** [NVlabs/instant-ngp#1072]
Hi, I´m trying to display one of my NERF results in a web page using React. Is there any kind of way to do this? I´ve been searching but all I couldn´t find anything like this.
Thank you!

**Comment by solracmendo** [comment]
Bump

**Comment by ogradyso** [comment]
You can use the 'Mesh It' button to in the GUI to create a 3D mesh .obj that you can then import into a ThreeJS as in this stack post: [Add model.obj to three.MESH](https://stackoverflow.com/questions/21536622/add-model-obj-to-three-mesh) 

Just be warned that you will have to clean up the objects using some post-processing/3D design software like Blender or Meshlab.

I don't think there is currently a way to pipe the nerf output directly to the browser (although I wouldn't be surprised if the NVIDIA team finds a way to do it!).  The difficulty with using NeRF in a web page is that the visualization still needs a hefty amount of computational power even after stopping training. For example, when I run the viewer and stop training my GPU is still churning away at 95%.  To render the object for a user (or possibly multiple users if that is your plan) over the web (mobile, multi-browser, cross-platform) would be both costly and technically challenging.

**Comment by solracmendo** [comment]
Okay, we´ll give a try, thank you so much!
