### ISSUE TITLE
cmake error No Cuda Toolset Found

### ISSUE THREAD

**Issue by jcobreros** [NVlabs/instant-ngp#108]
Windows 11 21H2
Visual Studio Community 2019 installed with "Desktop Development with C++" default modules installed.
If I do: Developer Command Prompt for VS 2019 --> cmake --version
I get: cmake version 3.20.21032501-MSVC_2

Installed CUDA 11.6.0.511.23_windows using 2.5gb installer. Made sure it installed Visual Studio Integration 11.6
If I do: Windows Power Shell --> nvcc.exe --version
I get:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Fri_Dec_17_18:28:54_Pacific_Standard_Time_2021
Cuda compilation tools, release 11.6, V11.6.55
Build cuda_11.6.r11.6/compiler.30794723_0

I added the following Environment Variables:
CMAKE_CUDA_COMPILER = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc.exe
CUDA_PATH = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6
CUDA_PATH_V11_6 = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6

I've also copied the files in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\extras\visual_studio_integration\MSBuildExtensions to here C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations

I've tried reinstalling VS2019 and CUDA countless times. I've restarted my PC between steps. I've made sure the files are there, the environment variables are set. I don't know what else to do.

I've also tried uninstalling CUDA 11.6 and installing CUDA 11.4.4 and following the same procedure (update environment variables, copy the files, etc).

**Comment by Tom94** [comment]
Hi there, your setup sounds like it _should_ work. The only thing I can think of is trying a newer version of CMake. My machine has the same CUDA, MSVC, and Windows versions as yours, but I happen to have CMake 3.21.1 installed.

**Comment by jcobreros** [comment]
Yes! Using cmake 3.21.5 works. Or at least I made it past the "cmake . -B build" command.
Now I'm getting "namespace "optix_ptx" has no member "raystab_ptx"" errors when I run "cmake --build build --config RelWithDebInfo -j 16"

**Comment by Tom94** [comment]
Hi, could you pull and try again? I found a problem in OptiX detection that could render it half-enabled, leading to exactly the kind of error you're seeing.

**Comment by jcobreros** [comment]
I got it to work by changing my driver's from Game ready to Studio and doing a clean install. I will follow this repository closely and report if I see any related issues.

**Comment by Tom94** [comment]
Thanks!

**Comment by EdenShadow** [comment]
@Tom94 I have the same problem, the same configuration, have you solved it?
`D:\ngp\instant-ngp>cmake . -B build
-- The C compiler identification is MSVC 19.29.30141.0
-- The CXX compiler identification is MSVC 19.29.30141.0
CMake Error at D:/Program Files/CMake/share/cmake-3.21/Modules/CMakeDetermineCompilerId.cmake:460 (message):
  No CUDA toolset found.
Call Stack (most recent call first):
  D:/Program Files/CMake/share/cmake-3.21/Modules/CMakeDetermineCompilerId.cmake:6 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  D:/Program Files/CMake/share/cmake-3.21/Modules/CMakeDetermineCompilerId.cmake:59 (__determine_compiler_id_test)
  D:/Program Files/CMake/share/cmake-3.21/Modules/CMakeDetermineCUDACompiler.cmake:283 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:18 (PROJECT)`
