### ISSUE TITLE
colmap can calculate the correct pose, but there is a problem with colmap2nerf.

### ISSUE THREAD

**Issue by XJTU-JP** [NVlabs/instant-ngp#1081]
This is a very meaningful project, I learned a lot from it!

I'm having some problems computing poses using colmap2nerf.
On the left is the pose calculated by colmap2nerf, and on the right is the pose calculated by colmap.
Obviously, colmap gets the correct pose but colmap2nerf doesn't.
I have a conjecture: in my data, the central object is axisymmetric, so there will be a problem with the pose calculation? But colmap is not miscalculated.

Do you have any suggestions, looking forward to reply.
![res](https://user-images.githubusercontent.com/85154110/202485809-fb3eac20-a820-4a53-9c3e-3a74462cdda5.png)

**Comment by JiayingGaoo** [comment]
colmap2nerf.py also call colmap to estimate poses, are you sure the parameters are same with single running colmap?

**Comment by XJTU-JP** [comment]
Yes, I have taken these parameters in both  single running colmap and colmap2nerf
--colmap_matcher==exhaustive
--colmap_camera_model==OPENCV
I don't know why the output results are inconsistent

**Comment by yenchenlin** [comment]
What happens if you first run your own COLMAP command to get camera poses, and then run `colmap2nerf.py` without passing `--run_colmap`?

**Comment by XJTU-JP** [comment]
I think I've solved the problem.
I removed the "--SiftMatching.guided_matching=true" parameter of "colmap {args.colmap_matcher}_matcher" in colmap2nerf.py and got the correct pose.
Although I still don't understand why that is.
Excellent work! Thank you very much.
![re](https://user-images.githubusercontent.com/85154110/202838138-c21f6368-4b47-4a92-80e6-f17febdbdbec.png)
