### ISSUE TITLE
Must call Module::fwd before Module::bwd when calling `backward` for `Encoding` when using the same sets of points multiple times

### ISSUE THREAD

**Issue by kacperkan** [NVlabs/instant-ngp#1097]
Hi everyone,

Thank you for your amazing framework! I'm trying to use just `Encoding` class for my python project. The method works like this:
1. Sample points in the 3D space.
2. Iterate over these points (because of memory constraints).
3. For each iteration, use the `Encoding` encoder.

However, the iteration causes the gradients are not stored, from what I can see. Instead, the computation graph is reset for the latest batch that the backward was used for. It raises the following error:
`RuntimError: Must call Module::fwd before Module::bwd`

My setup:
- RTX 2080 Ti
- tiny-cuda-nn 1.4
- PyTorch 1.8.2
- CUDA 11.1
- Ubuntu 20.04

I'm sharing an MWE below to reproduce the error:
```python
import tinycudann as  tcnn
import torch

encoder = tcnn.Encoding(
    3,
    {
        "otype": "Grid",
        "type": "Hash",
        "n_levels": 16,
        "n_features_per_level": 2,
        "base_resolution": 16,
        "log2_hashmap_size": 20,
        "interpolation": "Linear",
        "dtype": "float32",
    }
).cuda()
sum(encoder(torch.ones((1, 3)).cuda()).sum() for _ in range(2)).backward() # this line should raise the error
```

I will appreciate any help here!

Best regards,
kacperkan

EDIT:
The error happens even with the line:
`sum(encoder(torch.rand((1, 3)).cuda()).sum() for _ in range(2)).backward()`,
so it's enough to call `Encoding` multiple times to break it.

**Comment by Tom94** [comment]
Hi, I think you meant to post over at https://github.com/nvlabs/tiny-cuda-nn

That said, I believe you are on an old version of tiny-cuda-nn and that updating to the latest will fix your issue.

**Comment by kacperkan** [comment]
Oops, sorry! I had tiny-cuda-nn tab open next to this one and misclicked!
