### ISSUE TITLE
Optix don't build in sdf mode

### ISSUE THREAD

**Issue by im-pain** [NVlabs/instant-ngp#110]
09:48:46 SUCCESS  Loaded mesh "data\sdf\armadillo.obj" file with 1 shapes.
09:48:46 SUCCESS  Built TriangleBvh: nodes=21845
**09:48:46 WARNING  OptiX was not built. Falling back to slower TriangleBVH::ray_intersect.**
09:48:46 SUCCESS  Built TriangleOctree: depth=10 nodes=209341 dual_nodes=839938. Populating dual nodes...
09:48:47 SUCCESS  Loaded mesh: triangles=99976 AABB=[min=[-0.695084,-0.825671,-0.632707], max=[0.695084,0.825671,0.632707]] after scaling=[min=[0.0865273,0.00744793,0.124301], max=[0.913473,0.992552,0.875699]]
09:48:47 INFO     Loading network config from: configs\sdf\base.json
09:48:47 INFO     GridEncoding:  Nmin=16 b=1.38191 F=2 T=2^19 L=16
09:48:47 INFO     Model:         3--[HashGrid]-->32--[FullyFusedMLP(neurons=64,layers=4)]-->1
09:48:47 INFO       total_encoding_params=12196240 total_network_params=7168

tried with setting the optix location in the evironments but the issue remains

**Comment by Tom94** [comment]
Hi there, since OptiX needs to be detected by CMake and built into the program, the best way to debug this is to clear your build folder, regenerate it via CMake, and use CMake's output (rather than instant-ngp's output) to diagnose why it can't find OptiX.

If you've only installed OptiX after having built instant-ngp, regenerating the build alone might be enough to fix your issue.

Cheers!

**Comment by Tom94** [comment]
Glad to hear that it works now!

Yes, TensorCores are used in all modes (including NeRF and SDF) for the neural network.

(To clarify just in case: OptiX provides access to the ray tracing cores, which are only used to generate SDF training data efficiently -- OptiX isn't actually used to run any of the models.)

**Comment by im-pain** [comment]
i ask because i uninstalled the optix sdk, modified the optix path to a wrong location reconfigured and generated the cmake files and the build folder from zero for test without optix and i just get the same performance in nerf

**Comment by Tom94** [comment]
OptiX doesn’t have anything to do with TensorCores. They‘re getting used if your GPU has them — regardless of OptiX installation.

OptiX is only for ray tracing cores, which in turn are only used for SDF training data generation.

**Comment by im-pain** [comment]
i understand now, thank you 👌
