### ISSUE TITLE
"Mesh It!" GUI broken through nomachine/WSL

### ISSUE THREAD

**Issue by pwais** [NVlabs/instant-ngp#111]
When I try hitting the "Mesh It" button in the GUI using the standard NeRF Lego scene, I get a crash with the following:
```
$ CUDA_VISIBLE_DEVICES=0 ./build/testbed --scene=data/nerf_synthetic/lego/transforms_train.json 
01:42:37 INFO     Loading NeRF dataset from
01:42:37 INFO       data/nerf_synthetic/lego/transforms_train.json
01:42:37 SUCCESS  Loaded 100 images of size 800x800 after 0s
01:42:37 INFO       cam_aabb=[min=[0.5,1.40742e+30,0.5], max=[0.5,1.40742e+30,0.5]]
01:42:37 INFO     Loading network config from: configs/nerf/base.json
01:42:37 INFO     GridEncoding:  Nmin=16 b=1.38191 F=2 T=2^19 L=16
Warning: FullyFusedMLP is not supported for the selected architecture 37. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Warning: FullyFusedMLP is not supported for the selected architecture 37. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
01:42:37 INFO     Density model: 3--[HashGrid]-->32--[FullyFusedMLP(neurons=64,layers=3)]-->1
01:42:37 INFO     Color model:   3--[SphericalHarmonics]-->16+16--[FullyFusedMLP(neurons=64,layers=4)]-->3
01:42:37 INFO       total_encoding_params=12196240 total_network_params=9728
01:42:56 INFO     #vertices=328330 #triangles=655128
01:42:56 ERROR    Failed to compile shader: vertex
01:42:56 ERROR    0:1(10): error: GLSL 4.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 1.00 ES, and 3.00 ES

01:42:56 ERROR    Failed to compile shader: pixel
01:42:56 ERROR    0:1(10): error: GLSL 4.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 1.00 ES, and 3.00 ES

01:42:56 ERROR    Failed to compile shader: shader program
01:42:56 ERROR    error: no shaders attached to the program

Got cutlass error: Error Internal at: 394
```

I'm running in an environment based upon `pytorch/pytorch:1.10.0-cuda11.3-cudnn8-devel`.  I seem to have OpenGL available...
```
$ glxinfo | grep "OpenGL version"
OpenGL version string: 3.1 Mesa 20.0.8
```

GPU is a 3090.  It looks like I've got plenty new enough OpenGL in my environment but perhaps the build is ignoring it?

Oddly `--save_mesh` in the python script _does_ work.

**Comment by pwais** [comment]
Unrelated but I'm also getting that `Warning: FullyFusedMLP is not supported for the selected architecture 37. Falling back to CutlassMLP` fallback even when using a 3090.  When I re-compile w/out arch 37 then I don't get the fallback tho and training is a lot faster (so it's not kidding about using the fallback!).  GPU arch prolly not being checked at runtime?

**Comment by Tom94** [comment]
Unfortunately, much of the architecture-specific stuff has to be configured at compile time. One option would be to compile separate objects for all the requested architectures, but this'll require a few deeper changes (e.g. templating everything and compiling for both full- and half precision) and it'd ~quadruple the already insane compile times. Still trying to come up with a better way.

As for OpenGL 4.5: I don't have a good idea what that wouldn't work on your card.

As a workaround: the mesh shader uses
```
#extension GL_NV_fragment_shader_barycentric : enable
```
to get barycentric coordinates for per-face texturing, which should be easy to replace with manual code for <=3.3 support. Going to put it on my todo list for after the weekend!

**Comment by pwais** [comment]
> Unfortunately, much of the architecture-specific stuff has to be configured at compile time....

Ah makes sense.  Doh I'm n00b to CUDA but sounds like if there was more poweful link-time optimization (which nvidia can afford to lean on??) then the templating tricks would be less necessary.

Maybe you might want the `CutlassMLP` code to barf at compile time if `TCNN_CUDA_ARCHITECTURES` (or whatever CUDA var it feeds) is a list of length 2 or more.  That's probably rare in practice, and in CI I think you just do one arch at a time, but I could imagine some researcher trying to use `TCNN_CUDA_ARCHITECTURES=a;b;c;d` and getting wonky experiment results cuz RTX was not using expected ops.  Such barfing will also discourage anybody from trying to build fat binaries w/out seeing this Github issue or whatnot in the breadcrumbs.


> As for OpenGL 4.5: I don't have a good idea what that wouldn't work on your card. It works fine on my 3090 on both Windows and Linux.

Thanks for the pointer!  I'm using nomachine ( https://www.nomachine.com/ ) which might be complicating the OpenGL context situation.  That said, if `draw_mesh_gl` might work in older OpenGL, then I think we could potentially get the GUI fully running in Google Colab via nomachine.  (the imgui websocket thing is probably "better", but VNC-on-Colab is at least something people have done before).

**Comment by Tom94** [comment]
I've considered hard-failing on multi-arch builds, but I feel like sometimes they're actually not too bad. For example mixed 86/80 systems, or even 86/75 can be quite close to optimal performance -- and are quite common.

So... for now, I think I'd like to keep emitting warnings left and right (in CMake as well as during runtime), but leave the code somewhat functional. At least until full runtime selection becomes feasible.

I suspect that `draw_mesh_gl` might still not work through nomachine, even when requiring only GL 3.3. Reason being that CUDA<->OpenGL interop is being used to avoid copying memory through the CPU... and said interop is often not supported in non-standard OGL contexts.

The regular GUI only works because I explicitly implemented a copy-over-CPU fallback for that case, which would unfortunately add additional annoyance to drawing the marching cubes mesh. I'm open for PRs in this direction, but not sure if I will spend the time myself to overhaul it sufficiently for this specific GUI use case.

**Comment by pwais** [comment]
@Tom94 Thanks!  I guess since I haven't seen it, is the GUI supposed to show the mesh after hitting Mesh It! ?  I recently discovered some of the hidden features / keybindings so I see there's actually a ton of viz / debug support ...  maybe the conclusions here is for this windowing solution, just render meshes with `scripts/run.py` rather than the GUI.  down the line, maybe show / hide the mesh-it button depending on OpenGL version, but idk.  

would love to see a demo video showing off all the GUI viz hidden features.  also, maybe for WASD, A and D rotate camera left/right instead of pan?  since middle click does pan.
