### ISSUE TITLE
Compilation error - it crashes at Building CUDA object CMakeFiles/ngp.dir/src/triangle_bvh.cu.o

### ISSUE THREAD

**Issue by MichalSzczekocki** [NVlabs/instant-ngp#1119]
After building with cmake --build build --config RelWithDebInfo -j 
the compilation process crashed several times, each time with the whole ubuntu shutting down.
After having upgraded the libsmbclient, libwbclient0, samba-libs (which was suggested by the crash report) I still cannot compile it 100% but at least the computer won't shut down and you can see the error log in console:

> [ 79%] Building CUDA object CMakeFiles/ngp.dir/src/triangle_bvh.cu.o
/home/michaels/CLionProjects/instant-ngp/include/neural-graphics-primitives/triangle_octree.cuh(74): warning: variable "rstep" was declared but never referenced

>/home/michaels/CLionProjects/instant-ngp/include/neural-graphics-primitives/triangle_octree.cuh(74): warning: variable "rstep" was declared but never referenced

>/home/michaels/CLionProjects/instant-ngp/include/neural-graphics-primitives/triangle_octree.cuh(74): warning: variable "rstep" was declared but never referenced

>Killed
gmake[2]: *** [CMakeFiles/ngp.dir/build.make:370: CMakeFiles/ngp.dir/src/triangle_bvh.cu.o] Error 137
gmake[2]: *** Waiting for unfinished jobs....
Killed
gmake[2]: *** [CMakeFiles/ngp.dir/build.make:272: CMakeFiles/ngp.dir/src/testbed_image.cu.o] Error 137
Killed
gmake[2]: *** [CMakeFiles/ngp.dir/build.make:202: CMakeFiles/ngp.dir/src/common_device.cu.o] Error 137
gmake[1]: *** [CMakeFiles/Makefile2:175: CMakeFiles/ngp.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2

I wonder if anyone experienced the same problem before?

**Comment by OlafenwaMoses** [comment]
Same for me. I am using wsl2 on Windows 11.

**Comment by wl8915** [comment]
https://colab.research.google.com/drive/10TgQ4gyVejlHiinrmm5XOvQQmgVziK3i?usp=sharing#scrollTo=B7E55zXYc1gD
I solved the problem through this website, you can also try！

**Comment by OlafenwaMoses** [comment]
I was able to fix it by running the compile command with adding `-j2`

```
cmake --build build --config RelWithDebInfo -j2
```

**Comment by Tom94** [comment]
The compiler seems to be running out of memory when compiling too many files in parallel. Using -j2 (or outright omitting the -j) helps, because it forces the compiler to compile at most 2 files at a time (or just one). I wish it gave a more descriptive error than "Error 2"... but I've added instructions to the readme in any case.
