### ISSUE TITLE
Have trouble running code on a server

### ISSUE THREAD

**Issue by WXuanyang** [NVlabs/instant-ngp#113]
I've successfully run the code locally, but when move it to a server with better gpu, I get the following message when I run the testbed
![image](https://user-images.githubusercontent.com/69446297/152617641-121fdc53-46c0-4bbd-823c-e731fc66096a.png)
Could anyone give me some advise? Thx
Information that might be useful:
![image](https://user-images.githubusercontent.com/69446297/152617877-495ca63a-39a2-4bd2-994c-943525e7d6da.png)

**Comment by WXuanyang** [comment]
And if I run the code with the --no_gui flag, how could I adjust the parameters and save the mesh?

**Comment by Tom94** [comment]
You can use the `compute_marching_cubes_mesh` Python binding to get the resulting mesh in numpy array form or `compute_and_save_marching_cubes_mesh` to directly save the mesh.

See `src/python_api.cu` for more detailed documentation of these functions as well as additional Python bindings.

You can check `scripts/run.py` for an example of how testbed can be set up using Python.
