### ISSUE TITLE
ERROR    Uncaught exception:

### ISSUE THREAD

**Issue by yukaariki** [NVlabs/instant-ngp#1134]
HI,
I could not  train ./build/instant-ngp --scene data/nerf/fox on latest version ( previous version I can testbed)
I hvae error :
Uncaught exception: instant-ngp/src/testbed_nerf.cu:2694 cudaMemsetAsync(density_grid_tmp, 0, sizeof(float)*n_elements, stream) failed with error invalid argumen

How to fix it ?

**Comment by yuefeng21** [comment]
I also have the same issue.

**Comment by Tom94** [comment]
Fixed on latest `master`. To solve the issue, you can compile the latest code or you can wait for ~1h and download the then newly built binaries.
