### ISSUE TITLE
Inference Performance

### ISSUE THREAD

**Issue by pure-water** [NVlabs/instant-ngp#114]
Hi there,

 Is there an offical data for performance between the vanilan nerf (two "big" MLP) versus hash-griding (hash+2 "tiny" MLP)? 

Regards
Yao

**Comment by Tom94** [comment]
You can use `--network frequency.json` to load a two-big-MLP config that somewhat approximates the architecture of original NeRF.

The paper's Table 2 has equal time training comparisons: `Ours: Hash` corresponds to the default config (`base.json`) and `Ours: Frequency` corresponds to `frequency.json`.
