### ISSUE TITLE
Each camera fits one scene?

### ISSUE THREAD

**Issue by KamiCalcium** [NVlabs/instant-ngp#1140]
Hi,

Amazing work! I have a naive question.

I'm trying to training the nerf with my own dataset. For one frame, I have multiple cameras' views (~30) and the cameras are calibrated so the extrinsic are known. Thus, I skip the COLMAP step and write a transforms.json myself.

However, when I try to train the scene, I found that each of the camera is trying to reconstruct the individual small scene, and stitching them does not yield the whole big scene. This is obviously wrong because the correct case should be all the cameras reconstruct to one big scene. The wrong visualization is shown below:

<img width="705" alt="image" src="https://user-images.githubusercontent.com/61800479/209624475-6042bc96-d935-4caa-8aec-fd70023f1450.png">

If I zoom into each of the 'cone' (each camera), I will see a small scene inside.

I suspect it is either my extrinsic has problem or the near/far plane has some problem? It should be a naive bug tho. Could you please give me some suggestions? Thanks a lot!

**Comment by KamiCalcium** [comment]
Update: Even if I'm using the camera parameters estimated by COLMAP, it is still fitting small scenes for each camera, like this:
<img width="1701" alt="3" src="https://user-images.githubusercontent.com/61800479/209633036-c75c6305-6829-43dc-afce-0cf6e6eb011a.png">
<img width="954" alt="2" src="https://user-images.githubusercontent.com/61800479/209633109-add42970-7985-492b-93b8-e75adacddd76.png">
<img width="804" alt="1" src="https://user-images.githubusercontent.com/61800479/209633163-d63b9614-9827-4fd1-b3f2-b298067c0b3e.png">

**Comment by JPaulMora** [comment]
What's happening is that your NeRF isn't converging, basically the neural net isn't able of reconstructing the 3D space (for some reason). 

I would suggest you let it train for longer, or use greater batch sizes when training.

PS. What you say about the "small scenes inside the cones" is expected, as NeRFs (AFAIK) work by tracing rays from each camera source and guessing where they collide in space, so this shouldn't be related to your issue.

**Comment by KamiCalcium** [comment]
> What's happening is that your NeRF isn't converging, basically the neural net isn't able of reconstructing the 3D space (for some reason).
> 
> I would suggest you let it train for longer, or use greater batch sizes when training.
> 
> PS. What you say about the "small scenes inside the cones" is expected, as NeRFs (AFAIK) work by tracing rays from each camera source and guessing where they collide in space, so this shouldn't be related to your issue.

Thanks. The problem is that all my camera have different intrinsics and by default the transforms.json only accept a single intrinsic. After modifying that manually I was able to get good results.

**Comment by Mabel0403** [comment]
Hi, KamiCalcium
I have the same problem as you. I need to use NGP to process a batch of images with different intrinsics. Could you please tell me how you solved it? Thanks a lot!

**Comment by Mabel0403** [comment]
> 

Hi, KamiCalcium
I have the same problem as you. I need to use NGP to process a batch of images with different intrinsics. Could you please tell me how you solved it? Thanks a lot!

**Comment by ZJLi2013** [comment]
same questions, is there an official support on multi camera intrinsic ?

**Comment by cccober** [comment]
Hi, KamiCalcium,  I have the same question too.
