### ISSUE TITLE
CMake Error: The source directory "SOURCES/CMakeFiles/CMakeTmp" does not exist.

### ISSUE THREAD

**Issue by paracanthurus25** [NVlabs/instant-ngp#1141]
So I am trying to run the "cmake . -B build" command and I get these errors: 
  
   **C:\ngp\instant-ngp>cmake . -B build
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19045.
-- The C compiler identification is MSVC 19.29.30146.0
-- The CXX compiler identification is MSVC 19.29.30146.0
-- The CUDA compiler identification is NVIDIA 11.7.64
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7/bin/nvcc.exe - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Obtained CUDA architectures automatically from installed GPUs
CMake Error: The source directory "SOURCES/CMakeFiles/CMakeTmp" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
CMake Error at dependencies/tiny-cuda-nn/CMakeLists.txt:107 (try_run):
  Failed to configure test project build system.
Call Stack (most recent call first):
  dependencies/tiny-cuda-nn/CMakeLists.txt:146 (TCNN_AUTODETECT_CUDA_ARCHITECTURES)

-- Configuring incomplete, errors occurred!
See also "C:/ngp/instant-ngp/build/CMakeFiles/CMakeOutput.log".**

I have installed Visual Studio 2019, CUDA toolkit 11.7, Python 3.10, and Optix 7.5

**Comment by mrsky007** [comment]
same problem

**Comment by matthewhilton** [comment]
I was able to fix this by doing the following:

in the `/depdencies/tiny-cuda-nn` folder, run `git checkout ae6361103d9b18ddfee74668f5ba3d80410df2ac`

This checks out an older verion of the `tiny-cuda-nn` depdency. The newer version seems to have a bug in it.

**Comment by Tom94** [comment]
Should be fixed on latest master. I had accidentally broken backward compatibility with pre-3.25 versions of CMake, my bad.
