### ISSUE TITLE
Confusing comments

### ISSUE THREAD

**Issue by KamiCalcium** [NVlabs/instant-ngp#1145]
Hi,

In https://github.com/NVlabs/instant-ngp/blob/988de4257cd61ca7094493abf2f082be44bca409/scripts/colmap2nerf.py#L269,

the comment is swap y and z axis, however, in the code it swaps axis 0 and axis 1. Shouldn't it be swapping x and y axis?

**Comment by Tom94** [comment]
Thanks, the comment is now removed.
