### ISSUE TITLE
run.py: error: ambiguous option: --video could match --video_camera_path, --video_camera_smoothing, --video_loop_animation, --video_fps, --video_n_seconds, --video_spp, --video_output

### ISSUE THREAD

**Issue by paracanthurus25** [NVlabs/instant-ngp#1148]
When I try to run this command: 

"python scripts/run.py --mode nerf --scene data/truck --load_snapshot data/truck/base.msgpack --video_camera_path data/truck/base_cam.json --video_n_seconds 4 --video fps 60 --video_output test.mp4 -- height 1080 --width 1920"

I get this error:

usage: run.py [-h] [--scene SCENE] [--network NETWORK] [--load_snapshot LOAD_SNAPSHOT] [--save_snapshot SAVE_SNAPSHOT] [--nerf_compatibility]
              [--test_transforms TEST_TRANSFORMS] [--near_distance NEAR_DISTANCE] [--exposure EXPOSURE] [--screenshot_transforms SCREENSHOT_TRANSFORMS]
              [--screenshot_frames [SCREENSHOT_FRAMES ...]] [--screenshot_dir SCREENSHOT_DIR] [--screenshot_spp SCREENSHOT_SPP]
              [--video_camera_path VIDEO_CAMERA_PATH] [--video_camera_smoothing] [--video_loop_animation] [--video_fps VIDEO_FPS]
              [--video_n_seconds VIDEO_N_SECONDS] [--video_spp VIDEO_SPP] [--video_output VIDEO_OUTPUT] [--save_mesh SAVE_MESH]
              [--marching_cubes_res MARCHING_CUBES_RES] [--width WIDTH] [--height HEIGHT] [--gui] [--train] [--n_steps N_STEPS] [--second_window]
              [--sharpen SHARPEN]
              [files ...]
run.py: error: ambiguous option: --video could match --video_camera_path, --video_camera_smoothing, --video_loop_animation, --video_fps, --video_n_seconds, --video_spp, --video_output

I created the ngp environment in python=3.10 and installed OpenEXR-1.3.2-cp310-cp310-win_amd64.whl, in order to fix another issue.

**Comment by Tom94** [comment]
That's because you're missing an underscore between `--video` and `fps`

**Comment by paracanthurus25** [comment]
Ah. Thank you :)
