### ISSUE TITLE
distance_to_next_voxel seems to have bug when mip=7?

### ISSUE THREAD

**Issue by chanket** [NVlabs/instant-ngp#1154]
Hello,

I just found that `distance_to_next_voxel` may give incorrect results when `mip=7`. 

Here is a simple example. I try to trace in direction `(0, 1, 0)` at `mip=7`, and `distance_to_next_voxel` should tell me the how far it is before I enter another voxel. My code and output is:

```cpp
const uint32_t mip = 7;
std::cout << cascaded_grid_idx_at(Eigen::Vector3f(0.01f, -0.01f, 0.01f), mip) << std::endl; // 262143
std::cout << cascaded_grid_idx_at(Eigen::Vector3f(0.01f,  0.49f, 0.01f), mip) << std::endl; // 262143, still in the same voxel
std::cout << cascaded_grid_idx_at(Eigen::Vector3f(0.01f,  0.51f, 0.01f), mip) << std::endl; // 711533, the voxel changes when Y dimension crosses 0.5

Eigen::Vector3f dir(0, 1, 0);
Eigen::Vector3f idir = dir.cwiseInverse();
uint32_t res = NERF_GRIDSIZE()>>mip;
std::cout << distance_to_next_voxel(Eigen::Vector3f(0.01f, -0.01f, 0.01f), dir, idir, res) << std::endl; // 0.01, should be 0.51
std::cout << distance_to_next_voxel(Eigen::Vector3f(0.01f,  0.49f, 0.01f), dir, idir, res) << std::endl; // 0.51, should be 0.01
std::cout << distance_to_next_voxel(Eigen::Vector3f(0.01f,  0.51f, 0.01f), dir, idir, res) << std::endl; // 0.49, should be 0.99
```

It seems that the occupy grid's boundary at `mip=7` is `-0.5, 0.5, 1.5, ...`, but `distance_to_next_voxel` at `mip=7` instead leads the ray to `0.0, 1.0, 2.0, ...`. 

As a result, `advance_to_next_voxel` may also give unexpected results when `mip=7`.

**Comment by Tom94** [comment]
Great catch, thanks! It looks like `distance_to_next_voxel` is missing a subtraction of the voxel grid center (which is at 0.5), which doesn't cause a bug until the resolution of voxel grid becomes coarse enough to no longer be a multiple of 2 (which is at mip level 7).

Since you have the test setup: could you try modifying the first line of `distance_to_next_voxel` from
```cpp
Vector3f p = res * pos;
```
to
```cpp
Vector3f p = res * (pos - 0.5f);
```
and let me know whether this helped? I'll push the fix once you confirm.

**Comment by chanket** [comment]
> Great catch, thanks! It looks like `distance_to_next_voxel` is missing a subtraction of the voxel grid center (which is at 0.5), which doesn't cause a bug until the resolution of voxel grid becomes coarse enough to no longer be a multiple of 2 (which is at mip level 7).
> 
> Since you have the test setup: could you try modifying the first line of `distance_to_next_voxel` from
> 
> ```c++
> Vector3f p = res * pos;
> ```
> 
> to
> 
> ```c++
> Vector3f p = res * (pos - Vector3f::Constant(0.5f));
> ```
> 
> and let me know whether this helped? I'll push the fix once you confirm or if I get to testing it first.

This patch works. Thank you!
