### ISSUE TITLE
Bad gateway, download problem

### ISSUE THREAD

**Issue by FOXY-graphiste** [NVlabs/instant-ngp#1160]
Hi,
I need help...
The problem is that when I want to download instant ngp for GTX 1000 series, and even the others, the redirect does not work and it redirects me to a white page with the error bad gateway
is there some body who can give me directly the file, to download ?
thaankks for help

**Comment by FOXY-graphiste** [comment]
its says : 502 Bad Gateway
nginx/1.20.2

**Comment by Tobe2d** [comment]
I cant download as well..

502 Bad Gateway

**Comment by Tom94** [comment]
Fixed now!

**Comment by FOXY-graphiste** [comment]
> Fixed now!

yeah it's work
tanks
