### ISSUE TITLE
Uncaught exception: instant-ngp/src/testbed_nerf.cu:2705 cudaMemsetAsync(density_grid_tmp, 0, sizeof(float)*n_elements, stream) failed with error invalid argument

### ISSUE THREAD

**Issue by qiuyu96** [NVlabs/instant-ngp#1165]
After pull latest master code and build the project, I run with  `./instant-ngp data/nerf/fox`. Finally the following error occurs:

13:48:10 SUCCESS  Initialized CUDA. Active GPU is #1: NVIDIA RTX A6000 [86]
13:48:10 INFO     Loading NeRF dataset from
13:48:10 INFO       data/nerf/fox/transforms.json
13:48:10 SUCCESS  Loaded 50 images after 0s
13:48:10 INFO       cam_aabb=[min=[1.0229,-1.33309,-0.378748], max=[2.46175,1.00721,1.41295]]
13:48:11 WARNING  Vulkan validation layer is not available. Vulkan errors will be difficult to diagnose.
13:48:11 WARNING  Could not initialize Vulkan and NGX. DLSS not supported. (DLSS not available: NVSDK_NGX_Result_FAIL_FeatureNotFound)
13:48:11 INFO     Loading network config from: ./configs/nerf/base.json
13:48:11 INFO     GridEncoding:  Nmin=16 b=1.51572 F=2 T=2^19 L=16
13:48:11 INFO     Density model: 3--[HashGrid]-->32--[FullyFusedMLP(neurons=64,layers=3)]-->1
13:48:11 INFO     Color model:   3--[Composite]-->16+16--[FullyFusedMLP(neurons=64,layers=4)]-->3
13:48:11 INFO       total_encoding_params=13074912 total_network_params=10240
13:48:12 **ERROR    Uncaught exception: ~/code/instant-ngp/src/testbed_nerf.cu:2705 cudaMemsetAsync(density_grid_tmp, 0, sizeof(float)*n_elements, stream) failed with error invalid argument**

**Comment by qiuyu96** [comment]
And my OS is linux, my GPU is NVIDIA RTX A6000, my cuda version is 11.3.

**Comment by Tom94** [comment]
Hi, based on the first line of the log, my guess is that you have 2 (or more) GPUs in your system and your monitor connected to the second? If you could confirm, this would help in troubleshooting on my end.

**Comment by qiuyu96** [comment]
Yes, excatly! Then how to resolve this problem?

**Comment by qiuyu96** [comment]
> Hi, based on the first line of the log, my guess is that you have 2 (or more) GPUs in your system and your monitor connected to the second? If you could confirm, this would help in troubleshooting on my end.

Yes, excatly! Then how to resolve this problem?

**Comment by qiuyu96** [comment]
> Hi, based on the first line of the log, my guess is that you have 2 (or more) GPUs in your system and your monitor connected to the second? If you could confirm, this would help in troubleshooting on my end.

Yes, exactly! 
And Thanks to your instant reply.
Then how to resolve this problem?

**Comment by qiuyu96** [comment]
Yes, exactly!
And I simply add `CUDA_VISIBLE_DEVICES=1` before the original command line, it works!

> Hi, based on the first line of the log, my guess is that you have 2 (or more) GPUs in your system and your monitor connected to the second? If you could confirm, this would help in troubleshooting on my end.

**Comment by qiuyu96** [comment]
> Hi, based on the first line of the log, my guess is that you have 2 (or more) GPUs in your system and your monitor connected to the second? If you could confirm, this would help in troubleshooting on my end.

Yes, exactly!
And I simply add `CUDA_VISIBLE_DEVICES=1` before the original command line, it works!

**Comment by Tom94** [comment]
No need for that -- the problem should be fixed on latest `master` now.
