### ISSUE TITLE
Question: How save and load model ?

### ISSUE THREAD

**Issue by delldu** [NVlabs/instant-ngp#117]
**Dear friends,**
 **Thank you for your great job !**
 Here we have one question: **how save and re-load model ?** Would you like give us some hint ?
 **Many thanks.**

**Comment by Tom94** [comment]
Hi! You can use the GUI's snapshot loading/saving buttons or you can use the Python bindings' `testbed.load_snapshot` / `testbed.save_snapshot` (see `scripts/run.py` for example usage).
