### ISSUE TITLE
Path bug for python bindings

### ISSUE THREAD

**Issue by dennisushi** [NVlabs/instant-ngp#1212]
Related to [https://github.com/NVlabs/instant-ngp/issues/1208](this) but separate. as it is no longer related to colab.

Every time a run script using NGP is used outside the instant-ngp folder, I get an json error:
```    
while testbed.frame():
RuntimeError: [json.exception.type_error.306] cannot use value() with null
```

Steps to reproduce:

```
cd <instant-ngp path>
cd ..
python3 ./instant-ngp/scripts/run.py {scene_path} --n_steps {train_steps} --save_snapshot {snapshot_path}
```

Workaround is to use `os.chdir(<path to instant-ngp>)` but it's barbaric. Not sure what the root of the cause is.

**Comment by Tom94** [comment]
Hi, this should be fixed on latest `master` now. Please feel free to re-open the issue if the problem surfaces again.

**Comment by dennisushi** [comment]
I still get the error if I don't use `os.chdir`. 

```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "run.py", line 48, in <module>
    while testbed.frame():
RuntimeError: [json.exception.type_error.306] cannot use value() with null
```

**Comment by Tom94** [comment]
Can you post the full console log? Also, can you open `scripts/run.py`, add `print(testbed.root_dir)` right before the offending line, and let me know what the output is?
