### ISSUE TITLE
Error Coping File from nvngx_dlss.dll

### ISSUE THREAD

**Issue by vaibhavdevstuff** [NVlabs/instant-ngp#1213]
Getting this Error while building
  
  Creating library D:/GitRepo/ngp/instant-ngp/build/RelWithDebInfo/instant-ngp.lib and object D:/GitRepo/ngp/inst
  ant-ngp/build/RelWithDebInfo/instant-ngp.exp
  instant-ngp.vcxproj -> D:\GitRepo\ngp\instant-ngp\build\instant-ngp.exe
  Error copying file "D:/GitRepo/ngp/instant-ngp/dependencies/dlss/lib/Windows_x86_64//nvngx_dlss.dll" to "D:/GitRep
  o/ngp/instant-ngp".

**Comment by Tom94** [comment]
Hi, I just pushed a fix -- latest `master` should work now. Please feel free to re-open the issue if the problem persists.
