### ISSUE TITLE
VR Mode Crashing

### ISSUE THREAD

**Issue by pyetras** [NVlabs/instant-ngp#1218]
instant-ngp crashes as soon as I click connect to the headset and put the headset on. I've tried it with both Quest Link and SteamVR. No error message is displayed in the command prompt or otherwise, can you suggest how to debug this? I'm not very familiar with debugging on Windows.

I'm using the precompiled instant-ngp on a Windows 10 PC with a 4090 and Oculus Quest 2.

**Comment by pyetras** [comment]
After some digging I managed to find the following log 
```
Faulting application name: instant-ngp.exe, version: 3.4.0.0, time stamp: 0x63dbfa15
Faulting module name: XR_APILAYER_NOVENDOR_toolkit.dll, version: 1.2.4.0, time stamp: 0x63d8c8fa
Exception code: 0xc0000005
Fault offset: 0x00000000000c5e47
Faulting process ID: 0x6304
Faulting application start time: 0x01d937534ad31bf6
Faulting application path: C:\Users\Pietras\Desktop\Instant-NGP-for-RTX-3000-and-4000\instant-ngp.exe
Faulting module path: C:\Program Files\OpenXR-Toolkit\XR_APILAYER_NOVENDOR_toolkit.dll
Report ID: 335c0564-29f3-4296-808d-7ab69baa6df6
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by pyetras** [comment]
It works after disabling OpenXR-toolkit

**Comment by Ednaordinary** [comment]
I am not sure about on windows, but on linux I had to go to SteamVR hamburger menu > Settings > Developer > set the current OpenXR runtime to SteamVR. OpenGL does not seem to be enabled on the default OpenXR runtime (or the run time is not available, attached, etc), but it is on the SteamVR OpenXR runtime.
