### ISSUE TITLE
VR Under Linux

### ISSUE THREAD

**Issue by reynoldscem** [NVlabs/instant-ngp#1220]
Hi,

Just to confirm, the VR Mode is supported under Linux, Windows, or both?

**Comment by Tom94** [comment]
Hi, VR is supported and tested under Windows.

In _theory_, it should also work on Linux (over SteamVR), but I don't have a Linux system with SteamVR-compatible headset at hand. So here be dragons.

If you (or someone else) runs into issues while trying to use VR on Linux, please feel free to report them here and I'll do my best to fix things remotely.

**Comment by reynoldscem** [comment]
That's great - thanks. We've got no problem with running under Windows, just wanted to know the level of support!

If we end up running it under Linux and it requires much changing I'll try to submit a PR.

Thanks for the great software & the useful reply
