### ISSUE TITLE
Error: identifier "update_vr_performance_settings" is undefined  when building with -DNGP_BUILD_WITH_GUI=OFF

### ISSUE THREAD

**Issue by nalim2** [NVlabs/instant-ngp#1225]
Hi everyone,

sry to bother you all. But i try to build the headless variant with the -DNGP_BUILD_WITH_GUI=OFF flag. But i get a compile error in the cmake build. 

As far as i was able to understand the flag removes the definition of the required function which will break the build.
I also removed the -j flag but the build still failes.

Commands i use: 
cmake . -B build -DNGP_BUILD_WITH_GUI=OFF
cmake --build build --config RelWithDebInfo

Error: 
/home/jovyan/work/instant-ngp/notebooks/instant-ngp/src/testbed.cu(214): error: identifier "update_vr_performance_settings" is undefined

1 error detected in the compilation of "/home/jovyan/work/instant-ngp/notebooks/instant-ngp/src/testbed.cu".
make[2]: *** [CMakeFiles/ngp.dir/build.make:171: CMakeFiles/ngp.dir/src/testbed.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:187: CMakeFiles/ngp.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

Full log: 

[  2%] Building CUDA object CMakeFiles/optix_program.dir/src/optix/pathescape.ptx
[  5%] Building CUDA object CMakeFiles/optix_program.dir/src/optix/raystab.ptx
[  7%] Building CUDA object CMakeFiles/optix_program.dir/src/optix/raytrace.ptx
[  7%] Built target optix_program
[ 10%] Building CXX object dependencies/tiny-cuda-nn/dependencies/fmt/CMakeFiles/fmt.dir/src/format.cc.o
[ 12%] Building CXX object dependencies/tiny-cuda-nn/dependencies/fmt/CMakeFiles/fmt.dir/src/os.cc.o
[ 15%] Linking CXX static library libfmt.a
[ 15%] Built target fmt
[ 17%] Building CUDA object dependencies/tiny-cuda-nn/CMakeFiles/tiny-cuda-nn.dir/src/common.cu.o
[ 20%] Building CUDA object dependencies/tiny-cuda-nn/CMakeFiles/tiny-cuda-nn.dir/src/common_device.cu.o
[ 22%] Building CUDA object dependencies/tiny-cuda-nn/CMakeFiles/tiny-cuda-nn.dir/src/cpp_api.cu.o
[ 25%] Building CUDA object dependencies/tiny-cuda-nn/CMakeFiles/tiny-cuda-nn.dir/src/cutlass_mlp.cu.o
[ 27%] Building CUDA object dependencies/tiny-cuda-nn/CMakeFiles/tiny-cuda-nn.dir/src/encoding.cu.o
[ 30%] Building CUDA object dependencies/tiny-cuda-nn/CMakeFiles/tiny-cuda-nn.dir/src/loss.cu.o
[ 32%] Building CUDA object dependencies/tiny-cuda-nn/CMakeFiles/tiny-cuda-nn.dir/src/network.cu.o
[ 35%] Building CUDA object dependencies/tiny-cuda-nn/CMakeFiles/tiny-cuda-nn.dir/src/object.cu.o
[ 37%] Building CUDA object dependencies/tiny-cuda-nn/CMakeFiles/tiny-cuda-nn.dir/src/optimizer.cu.o
[ 40%] Building CUDA object dependencies/tiny-cuda-nn/CMakeFiles/tiny-cuda-nn.dir/src/reduce_sum.cu.o
[ 42%] Building CUDA object dependencies/tiny-cuda-nn/CMakeFiles/tiny-cuda-nn.dir/src/fully_fused_mlp.cu.o
[ 45%] Linking CXX static library libtiny-cuda-nn.a
[ 45%] Built target tiny-cuda-nn
[ 47%] Converting PTX files to a C header
[ 50%] Building CUDA object CMakeFiles/ngp.dir/src/camera_path.cu.o
[ 52%] Building CUDA object CMakeFiles/ngp.dir/src/common.cu.o
[ 55%] Building CUDA object CMakeFiles/ngp.dir/src/common_device.cu.o
Warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed
          detected during:
            instantiation of "void Eigen::internal::triangular_solver_selector<Lhs, Rhs, Side, Mode, 0, -1>::run(const Lhs &, Rhs &) [with Lhs=Eigen::Ref<Eigen::Matrix<float, -1, -1, 0, -1, -1>, 0, Eigen::OuterStride<-1>>, Rhs=Eigen::Ref<Eigen::Matrix<float, -1, -1, 0, -1, -1>, 0, Eigen::OuterStride<-1>>, Side=1, Mode=5]" 
/home/jovyan/work/instant-ngp/notebooks/instant-ngp/dependencies/eigen/Eigen/src/Core/SolveTriangular.h(183): here
            instantiation of "void Eigen::TriangularViewImpl<MatrixType_, Mode_, Eigen::Dense>::solveInPlace<Side,OtherDerived>(const Eigen::MatrixBase<OtherDerived> &) const [with MatrixType_=Eigen::Ref<Eigen::Matrix<float, -1, -1, 0, -1, -1>, 0, Eigen::OuterStride<-1>>, Mode_=5U, Side=1, OtherDerived=Eigen::Ref<Eigen::Matrix<float, -1, -1, 0, -1, -1>, 0, Eigen::OuterStride<-1>>]" 
/home/jovyan/work/instant-ngp/notebooks/instant-ngp/dependencies/eigen/Eigen/src/Core/TriangularMatrix.h(525): here
            instantiation of "void Eigen::TriangularViewImpl<MatrixType_, Mode_, Eigen::Dense>::solveInPlace(const Eigen::MatrixBase<OtherDerived> &) const [with MatrixType_=Eigen::Ref<Eigen::Matrix<float, -1, -1, 0, -1, -1>, 0, Eigen::OuterStride<-1>>, Mode_=5U, OtherDerived=Eigen::Ref<Eigen::Matrix<float, -1, -1, 0, -1, -1>, 0, Eigen::OuterStride<-1>>]" 
/home/jovyan/work/instant-ngp/notebooks/instant-ngp/dependencies/eigen/Eigen/src/LU/PartialPivLU.h(492): here
            instantiation of "Eigen::Index Eigen::internal::partial_lu_impl<Scalar, StorageOrder, PivIndex, SizeAtCompileTime>::blocked_lu(Eigen::Index, Eigen::Index, Scalar *, Eigen::Index, PivIndex *, PivIndex &, Eigen::Index) [with Scalar=float, StorageOrder=0, PivIndex=int, SizeAtCompileTime=4]" 
/home/jovyan/work/instant-ngp/notebooks/instant-ngp/dependencies/eigen/Eigen/src/LU/PartialPivLU.h(514): here
            instantiation of "void Eigen::internal::partial_lu_inplace(MatrixType &, TranspositionType &, TranspositionType::StorageIndex &) [with MatrixType=Eigen::Matrix<float, 4, 4, 0, 4, 4>, TranspositionType=Eigen::Transpositions<4, 4, int>]" 
/home/jovyan/work/instant-ngp/notebooks/instant-ngp/dependencies/eigen/Eigen/src/LU/PartialPivLU.h(540): here
            [ 22 instantiation contexts not shown ]
            instantiation of "void Eigen::internal::Assignment<DstXprType, SrcXprType, Functor, Eigen::internal::Dense2Dense, Weak>::run(DstXprType &, const SrcXprType &, const Functor &) [with DstXprType=Eigen::Matrix<float, 3, 4, 0, 3, 4>, SrcXprType=Eigen::Block<const Eigen::Product<Eigen::ReturnByValue<Eigen::MatrixExponentialReturnValue<Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<float, float>, const Eigen::Matrix<float, 4, 4, 0, 4, 4>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, const Eigen::Matrix<float, 4, 4, 0, 4, 4>>>>>, Eigen::Matrix<float, 4, 4, 0, 4, 4>, 0>, 3, 4, false>, Functor=Eigen::internal::assign_op<float, float>, Weak=void]" 
/home/jovyan/work/instant-ngp/notebooks/instant-ngp/dependencies/eigen/Eigen/src/Core/AssignEvaluator.h(891): here
            instantiation of "void Eigen::internal::call_assignment_no_alias(Dst &, const Src &, const Func &) [with Dst=Eigen::Matrix<float, 3, 4, 0, 3, 4>, Src=Eigen::Block<const Eigen::Product<Eigen::ReturnByValue<Eigen::MatrixExponentialReturnValue<Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<float, float>, const Eigen::Matrix<float, 4, 4, 0, 4, 4>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, const Eigen::Matrix<float, 4, 4, 0, 4, 4>>>>>, Eigen::Matrix<float, 4, 4, 0, 4, 4>, 0>, 3, 4, false>, Func=Eigen::internal::assign_op<float, float>]" 
/home/jovyan/work/instant-ngp/notebooks/instant-ngp/dependencies/eigen/Eigen/src/Core/PlainObjectBase.h(800): here
            instantiation of "Derived &Eigen::PlainObjectBase<Derived>::_set_noalias(const Eigen::DenseBase<OtherDerived> &) [with Derived=Eigen::Matrix<float, 3, 4, 0, 3, 4>, OtherDerived=Eigen::Block<const Eigen::Product<Eigen::ReturnByValue<Eigen::MatrixExponentialReturnValue<Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<float, float>, const Eigen::Matrix<float, 4, 4, 0, 4, 4>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, const Eigen::Matrix<float, 4, 4, 0, 4, 4>>>>>, Eigen::Matrix<float, 4, 4, 0, 4, 4>, 0>, 3, 4, false>]" 
/home/jovyan/work/instant-ngp/notebooks/instant-ngp/dependencies/eigen/Eigen/src/Core/PlainObjectBase.h(599): here
            instantiation of "Eigen::PlainObjectBase<Derived>::PlainObjectBase(const Eigen::DenseBase<OtherDerived> &) [with Derived=Eigen::Matrix<float, 3, 4, 0, 3, 4>, OtherDerived=Eigen::Block<const Eigen::Product<Eigen::ReturnByValue<Eigen::MatrixExponentialReturnValue<Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<float, float>, const Eigen::Matrix<float, 4, 4, 0, 4, 4>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, const Eigen::Matrix<float, 4, 4, 0, 4, 4>>>>>, Eigen::Matrix<float, 4, 4, 0, 4, 4>, 0>, 3, 4, false>]" 
/home/jovyan/work/instant-ngp/notebooks/instant-ngp/dependencies/eigen/Eigen/src/Core/Matrix.h(418): here
            instantiation of "Eigen::Matrix<Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_>::Matrix(const Eigen::EigenBase<OtherDerived> &) [with Scalar_=float, Rows_=3, Cols_=4, Options_=0, MaxRows_=3, MaxCols_=4, OtherDerived=Eigen::Block<const Eigen::Product<Eigen::ReturnByValue<Eigen::MatrixExponentialReturnValue<Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<float, float>, const Eigen::Matrix<float, 4, 4, 0, 4, 4>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, const Eigen::Matrix<float, 4, 4, 0, 4, 4>>>>>, Eigen::Matrix<float, 4, 4, 0, 4, 4>, 0>, 3, 4, false>]" 
/home/jovyan/work/instant-ngp/notebooks/instant-ngp/src/common_device.cu(36): here

[ 57%] Building CUDA object CMakeFiles/ngp.dir/src/marching_cubes.cu.o
[ 60%] Building CUDA object CMakeFiles/ngp.dir/src/nerf_loader.cu.o
[ 62%] Building CUDA object CMakeFiles/ngp.dir/src/render_buffer.cu.o
[ 65%] Building CUDA object CMakeFiles/ngp.dir/src/testbed.cu.o
/home/jovyan/work/instant-ngp/notebooks/instant-ngp/src/testbed.cu(214): error: identifier "update_vr_performance_settings" is undefined

1 error detected in the compilation of "/home/jovyan/work/instant-ngp/notebooks/instant-ngp/src/testbed.cu".
make[2]: *** [CMakeFiles/ngp.dir/build.make:171: CMakeFiles/ngp.dir/src/testbed.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:187: CMakeFiles/ngp.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

System config: 

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:05:00.0 Off |                  N/A |
| 27%   23C    P8    19W / 260W |      6MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  On   | 00000000:06:00.0 Off |                  N/A |
| 27%   23C    P8    12W / 260W |      6MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce ...  On   | 00000000:43:00.0 Off |                  N/A |
| 27%   21C    P8    21W / 260W |      6MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA GeForce ...  On   | 00000000:44:00.0 Off |                  N/A |
| 27%   23C    P8     3W / 260W |      6MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA GeForce ...  On   | 00000000:87:00.0 Off |                  N/A |
| 27%   23C    P8     1W / 260W |      6MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA GeForce ...  On   | 00000000:88:00.0 Off |                  N/A |
| 27%   22C    P8    13W / 260W |      6MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  NVIDIA GeForce ...  On   | 00000000:C3:00.0 Off |                  N/A |
| 27%   23C    P8    11W / 260W |      6MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  NVIDIA GeForce ...  On   | 00000000:C4:00.0 Off |                  N/A |
| 27%   23C    P8     1W / 260W |      6MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

**Comment by Tom94** [comment]
Hi, my bad, this should be fixed on latest `master`. Could you try pulling and then compiling again?

**Comment by nalim2** [comment]
Hey @Tom94,

thank you for your fast response :)

Unfortunately now i get another error for the "init_vr" function.

../instant-ngp/src/main.cu(181): error: class "ngp::Testbed" has no member "init_vr"

1 error detected in the compilation of "/home/jovyan/work/instant-ngp/notebooks/instant-ngp/src/main.cu".
make[2]: *** [CMakeFiles/instant-ngp.dir/build.make:77: CMakeFiles/instant-ngp.dir/src/main.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:215: CMakeFiles/instant-ngp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by nalim2** [comment]
I added the same strategy to the init_vr function but it seems not correct for the whole tool? :D
So now it works but i do not know which frag combination would be correct in that case.

Here my wrong fix for the Line 181 in main.cu. Perhaps the VR flag has to be set false without a GUI?

#ifdef NGP_GUI
	if (vr_flag) {
		testbed.init_vr();
	}
#endif

**Comment by nalim2** [comment]
After this now i get following error when i execute it on custom sample data.

12:53:29 SUCCESS  Initialized CUDA. Active GPU is #0: NVIDIA GeForce RTX 2080 Ti [75]
12:53:30 SUCCESS  Detected auxiliary GPUs:
12:53:30 SUCCESS    #1: NVIDIA GeForce RTX 2080 Ti [75]
12:53:30 SUCCESS    #2: NVIDIA GeForce RTX 2080 Ti [75]
12:53:30 SUCCESS    #3: NVIDIA GeForce RTX 2080 Ti [75]
12:53:30 SUCCESS    #4: NVIDIA GeForce RTX 2080 Ti [75]
12:53:30 SUCCESS    #5: NVIDIA GeForce RTX 2080 Ti [75]
12:53:30 SUCCESS    #6: NVIDIA GeForce RTX 2080 Ti [75]
12:53:30 SUCCESS    #7: NVIDIA GeForce RTX 2080 Ti [75]
12:53:30 INFO     Loading NeRF dataset from
12:53:30 INFO       /home/jovyan/work/instant-ngp/notebooks/video/transforms.json
12:53:30 PROGRESS [                                       ]   0% ( 0/25)  0s/inf12:53:30 PROGRESS [==>                                      ]   4% ( 1/25) 0s/1s12:53:30 PROGRESS [===>                                     ]   8% ( 2/25) 0s/0s12:53:30 PROGRESS [=====>                                   ]  12% ( 3/25) 0s/0s12:53:30 PROGRESS [=======>                                 ]  16% ( 4/25) 0s/0s12:53:30 PROGRESS [========>                                ]  20% ( 5/25) 0s/0s12:53:30 PROGRESS [==========>                              ]  24% ( 6/25) 0s/0s12:53:30 PROGRESS [===========>                             ]  28% ( 7/25) 0s/0s12:53:30 PROGRESS [=============>                           ]  32% ( 8/25) 0s/0s12:53:30 PROGRESS [===============>                         ]  36% ( 9/25) 0s/0s12:53:30 PROGRESS [================>                        ]  40% (10/25) 0s/0s12:53:30 PROGRESS [==================>                      ]  44% (11/25) 0s/0s12:53:30 PROGRESS [====================>                    ]  48% (12/25) 0s/0s12:53:30 PROGRESS [=====================>                   ]  52% (13/25) 0s/0s12:53:30 PROGRESS [=======================>                 ]  56% (14/25) 0s/0s12:53:30 PROGRESS [=========================>               ]  60% (15/25) 0s/0s12:53:30 PROGRESS [==========================>              ]  64% (16/25) 0s/0s12:53:30 PROGRESS [============================>            ]  68% (17/25) 0s/0s12:53:30 PROGRESS [==============================>          ]  72% (18/25) 0s/0s12:53:30 PROGRESS [===============================>         ]  76% (19/25) 0s/0s12:53:30 PROGRESS [=================================>       ]  80% (20/25) 0s/0s12:53:30 PROGRESS [==================================>      ]  84% (21/25) 0s/0s12:53:30 PROGRESS [====================================>    ]  88% (22/25) 0s/0s12:53:30 PROGRESS [======================================>  ]  92% (23/25) 0s/0s12:53:30 PROGRESS [=======================================> ]  96% (24/25) 0s/0s12:53:30 PROGRESS [=========================================] 100% (25/25) 0s/0s12:53:30 SUCCESS  Loaded 25 images after 0s
12:53:30 INFO       cam_aabb=[min=[1.27657,-0.348987,0.00428447], max=[1.73063,0.368763,1.09568]]
Training:   0%|                                      | 0/2000 [00:00<?, ?step/s]12:53:31 INFO     Loading network config from: /home/jovyan/work/instant-ngp/notebooks/instant-ngp/configs/nerf/base.json
12:53:31 INFO     GridEncoding:  Nmin=16 b=1.82344 F=2 T=2^19 L=16
12:53:31 INFO     Density model: 3--[HashGrid]-->32--[CutlassMLP(neurons=64,layers=3)]-->1
12:53:31 INFO     Color model:   3--[Composite]-->16+16--[CutlassMLP(neurons=64,layers=4)]-->3
12:53:31 INFO       total_encoding_params=14008608 total_network_params=10240
Training:   0%|                                      | 0/2000 [00:00<?, ?step/s]
Traceback (most recent call last):
  File "/home/jovyan/work/instant-ngp/notebooks/instant-ngp/./scripts/run.py", line 183, in <module>
    while testbed.frame():
RuntimeError: /home/jovyan/work/instant-ngp/notebooks/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/cutlass_matmul.h:332 status failed with error Error Internal

The sample data was a simple mp4 video which was processed by the provided script and the default params: 
python ./instant-ngp/scripts/colmap2nerf.py --video_in input.mp4 --video_fps 2 --run_colmap --aabb_scale 64 --overwrite
