### ISSUE TITLE
CMake Error - No Known features for CXX compiler "GNU"

### ISSUE THREAD

**Issue by davideger** [NVlabs/instant-ngp#124]
I'm running Ubuntu 21.10 (Impish Indra) and CMake fails with the following

```
$ cmake . -B build
...
-- Configuring done
CMake Error in CMakeLists.txt:
  No known features for CXX compiler

  "GNU"

  version 11.2.0.

CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Probably I'm doing something silly wrong?  Here's my cmake and g++ install info:

apt info cmake
Package: cmake
Version: 3.22.2-0kitware1ubuntu20.04.1
APT-Manual-Installed: yes
APT-Sources: https://apt.kitware.com/ubuntu focal/main amd64 Packages

apt info g++
Package: g++
Version: 4:11.2.0-1ubuntu1
APT-Manual-Installed: yes
APT-Sources: http://us.archive.ubuntu.com/ubuntu impish/main amd64 Packages

**Comment by davideger** [comment]
Bizarre.  After downgrading cmake and deleting build/..., both an older cmake (=3.21.3-0kitware1ubuntu20.04.1) and the newer ones work.  Feels like a holdover of a failed cmake run when CUDA SDK was not installed.

**Comment by Ednaordinary** [comment]
Just deleting ./build worked to solve this error for me, thanks for making this issue or I might not have figured it out

**Comment by wzqvip** [comment]
<img width="581" alt="image" src="https://github.com/NVlabs/instant-ngp/assets/30136639/0f8906b2-33d6-439b-b352-f20623ddf7e9">

Same problem too.

**Comment by wzqvip** [comment]
Met the same. And deal with the same.

**Comment by MitchellAugustin** [comment]
For future people googling this same issue:

Deleting build/ and running cmake from the cuda_samples root dir also worked for me, for the same error on GCC 13 and Ubuntu 24.04.
