### ISSUE TITLE
OculusVR does not work

### ISSUE THREAD

**Issue by mspark2023** [NVlabs/instant-ngp#1244]
Hi, my device is oculus quest2, software is windows11 oculus .

I got this message when I  click **connect to VR/AR headset** button.
![image](https://user-images.githubusercontent.com/81412733/220233443-8b07f2f7-2702-425d-a34f-7b2bde6388d7.png)

It looks like I did not have OpenXR runtime, but openXR runtime was working.

I checked following ...

1. I connected my device using usb cable
2.  active  **OpenXR Runtime** in oculus

![image](https://user-images.githubusercontent.com/81412733/220233010-eb0579c4-53db-4b74-8cbe-6ddb3b2ef54f.png)

3. check openXR toolkit, it seems like working normally..

![image](https://user-images.githubusercontent.com/81412733/220233189-1459da0a-50a5-4a46-b019-a7450613dc0d.png)

log shows it is running.
![image](https://user-images.githubusercontent.com/81412733/220234066-bc48abdf-7c27-4307-974b-d2780f3494af.png)

**But** my instant-ngp can not connect VR headset. What did I miss? Any suggestions? 

Should I rebuild my instant-npg repo?

**Comment by Tom94** [comment]
Hi, it looks like you've set things up correctly, but there is one step missing above: to connect your headset to your computer, you need to not just plug in the cable, but also start Quest Link from _within_ your headset. See the following screenshot from the [official docs](https://www.meta.com/help/quest/articles/headsets-and-accessories/oculus-link/connect-link-with-quest-2/):
![image](https://user-images.githubusercontent.com/4923655/220263279-96c7b876-debc-425b-9c93-3481c8be974d.png)

Once Quest Link is running in your headset, you should be able to connect __instant-ngp__ to VR.

**Comment by mspark2023** [comment]
> Hi, it looks like you've set things up correctly, but there is one step missing above: to connect your headset to your computer, you need to not just plug in the cable, but also start Quest Link from _within_ your headset. See the following screenshot from the [official docs](https://www.meta.com/help/quest/articles/headsets-and-accessories/oculus-link/connect-link-with-quest-2/): ![image](https://user-images.githubusercontent.com/4923655/220263279-96c7b876-debc-425b-9c93-3481c8be974d.png)
> 
> Once Quest Link is running in your headset, you should be able to connect **instant-ngp** to VR.

Thank you. It works!
