### ISSUE TITLE
VR Quest Pro Passthrough not working

### ISSUE THREAD

**Issue by NEONFIVE** [NVlabs/instant-ngp#1248]
Hi Tom,

Quest Pro VR Session : there are no Blend modes available or even a dropdown list visible.

Is the passthrough API also available in InstantNGP?

**Comment by Tom94** [comment]
Hi, the quest pro unfortunately doesn't permit passthrough if you're running via quest link -- I don't know why.

Apparently, if you register your account as a quest pro developer, you can enable it ([see here](https://developer.oculus.com/documentation/unity/unity-passthrough-over-link/)), but I've never tried this myself.

**Comment by NEONFIVE** [comment]
Thanks for the answer, Thomas.
