### ISSUE TITLE
image2bin help

### ISSUE THREAD

**Issue by ammartist** [NVlabs/instant-ngp#125]
Is there any gide to use scripts/image2bin.py
I downloaded tokyo image to reproduce the gigapixel however I am stuck on converting the image to bin correctly

Any guide will be appreciated

**Comment by Tom94** [comment]
Hi there, I've simplified / generalized the script a little bit. You can now find it under `scripts/convert_image.py` and you can use it as follows:

```sh
python scripts/convert_image.py --input image.tga --output image.bin
```

**Comment by ammartist** [comment]
Thank you so much. it did work now..

**Comment by zhangsirya** [comment]
> 
Excuse me, what does this .tga image represent? I'm  not quite sure what this .tga image represents right now.
