### ISSUE TITLE
Adding Camera path sets view port upside down and reverse direction. 

### ISSUE THREAD

**Issue by ttesla** [NVlabs/instant-ngp#1261]
When I try to add a camera path for video render the viewport gets messed up. 
Here is the video clip:

https://streamable.com/hlbi7l

**Comment by Tom94** [comment]
Hi, thanks for reporting! This should be fixed with the latest binaries / code. Please feel free to re-open the issue if the problem resurfaces.

**Comment by TheLordSaiyan** [comment]
I kinda have the same problem #1286
