### ISSUE TITLE
Exporting RGBA-PNGs fails, when data is loaded from snapshot (ingp)

### ISSUE THREAD

**Issue by JoeLoginIsAlreadyTaken** [NVlabs/instant-ngp#1267]
I can successfully export RGBA-slices when the scene is rendered from transforms.json.

When i try to export the RGBA-slices from a saved snapshot. instant-ngp crashes with the exception:

Uncaught exception: D:/a/instant-ngp/instant-ngp/dependencies/tiny-cuda-nn/include\tiny-cuda-nn/object.h:148 check failed input.m() == input_width()

I save the snapshots to have free gpu memory for export meshes and RGBA-PNGs in higher resolution.
This works good for meshes.

**Comment by JoeLoginIsAlreadyTaken** [comment]
BTW, the same exception occurs when the  new feature "per-image latents" is used, from the gui or from the transforms.json ("n_extra_learnable_dims": 16)
In this case the exception comes up even when rendered directly from the transforms.json

**Comment by tsande01** [comment]
I see this issue whenever I try to save_mesh. I'm running using the python bindings on a list of jpgs.

**Comment by JoeLoginIsAlreadyTaken** [comment]
Yes, it is working now :-)
Thank you very much!
