### ISSUE TITLE
run.py script renders a blank video while the GUI successfully renders the video using the same cam.json and snapshot

### ISSUE THREAD

**Issue by joelitreview** [NVlabs/instant-ngp#1269]
I am trying to render a video, on a Linux machine, given a base_cam.json file and a snapshot programmatically using the run.py script and not the GUI. However, I even get a blank video or a video that shows a weird chunk of the scene from a weird angle, while the GUI , on a windows machine, actually generates a decent video.

-GPU: RTX A6000  (Driver Version: 520.56.06    CUDA Version: 11.8)
-Env: Docker container using the provided [Dockerfile](https://github.com/NVlabs/instant-ngp/blob/master/.devcontainer/Dockerfile)
-Build: Following the same installation and build instructions from the provided [notebook](https://github.com/NVlabs/instant-ngp/blob/master/notebooks/instant_ngp.ipynb)
-Data: The provided [fox](https://github.com/NVlabs/instant-ngp/tree/master/data/nerf/fox) dataset

Process:
1. I generate the snapshot on the Linux env using:
`python3 ./scripts/run.py {path_to_fox}  --n_steps 35000 --save_snapshot "{path_to_fox}/35000.msgpack"`
3. I load that snapshot into the instant-ngp GUI on the Windows machine, and I use the GUI to generate the base_cam.json file by using the "Add from cam" capability many times while rotating the scene.
4. I render in the GUI and the video is good: https://user-images.githubusercontent.com/126729809/222355543-3f3dd0cd-9008-48ff-af1b-f51b367c073c.mp4
5. I try to render on the Linux machine using the same generated base_cam.json file and snapshot and the command bellow, and I get the blank video: https://user-images.githubusercontent.com/126729809/222355617-a23d1183-3b67-4632-9e24-24b83e7d1d76.mp4
`python3 scripts/run.py --load_snapshot {path_to_fox}/35000.msgpack  --video_camera_path {path_to_fox}/base_cam.json  --video_n_seconds 5 --video_fps 25 --video_output {output_video_path}.mp4 `

base_cam.json:
```JSON
{
    "loop": false,
    "path": [
        {
            "R": [
                0.7741313576698303,
                -0.017077388241887093,
                0.6324496865272522,
                0.020903080701828003
            ],
            "T": [
                -8.476486206054688,
                0.9950648546218872,
                2.326902389526367
            ],
            "aperture_size": 0.0,
            "fov": 20.0,
            "glow_mode": 0,
            "glow_y_cutoff": 0.0,
            "scale": 9.255000114440918,
            "slice": 0.0
        },
        {
            "R": [
                0.9460394382476807,
                -0.020394137129187584,
                0.3176550269126892,
                0.06073775514960289
            ],
            "T": [
                -4.9910359382629395,
                1.6731290817260742,
                7.75481653213501
            ],
            "aperture_size": 0.0,
            "fov": 20.0,
            "glow_mode": 0,
            "glow_y_cutoff": 0.0,
            "scale": 9.173867225646973,
            "slice": 0.0
        },
        {
            "R": [
                0.9966998100280762,
                0.00054595508845523,
                -0.006726603489369154,
                0.08089596778154373
            ],
            "T": [
                0.6221901774406433,
                1.9794270992279053,
                9.552973747253418
            ],
            "aperture_size": 0.0,
            "fov": 20.0,
            "glow_mode": 0,
            "glow_y_cutoff": 0.0,
            "scale": 9.173867225646973,
            "slice": 0.0
        },
        {
            "R": [
                0.9516403675079346,
                0.031186671927571297,
                -0.2876908481121063,
                0.1031610369682312
            ],
            "T": [
                5.464170455932617,
                2.4658560752868652,
                7.960047721862793
            ],
            "aperture_size": 0.0,
            "fov": 20.0,
            "glow_mode": 0,
            "glow_y_cutoff": 0.0,
            "scale": 9.173867225646973,
            "slice": 0.0
        }
    ],
    "time": 1.0
}```

**Comment by Tom94** [comment]
There was a regression regarding camera paths a couple of days ago -- any chance you have not recompiled your linux build since? I get identical results, rendering your `base_cam.json` in the GUI and in the command line.

**Comment by joelitreview** [comment]
@Tom94 Excellent. I just got the newest code version and it worked. Thank you very much.
