### ISSUE TITLE
Import OBJ into Blender throws an error, fails to import

### ISSUE THREAD

**Issue by genereddick** [NVlabs/instant-ngp#1271]
Creating a mesh from the default Fox dataset (Windows RTX 3000 app version) and saving it creates what seems to be a valid OBJ. It can be loaded into Unity and other applications. However, attempting to import into Blender throws the following error and the OBJ does not import:

Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\io_scene_obj\__init__.py", line 151, in execute
    return import_obj.load(context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\io_scene_obj\import_obj.py", line 1063, in load
    context_multi_line = handle_vec(line_start, context_multi_line, line_split,
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\io_scene_obj\import_obj.py", line 938, in handle_vec
    vec[:] = [float_func(v) for v in line_split[1:]]
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\io_scene_obj\import_obj.py", line 938, in <listcomp>
    vec[:] = [float_func(v) for v in line_split[1:]]
ValueError: could not convert string to float: b'-nan(ind)'

location: <unknown location>:-1

**Comment by genereddick** [comment]
The same error occurs with Blender 3.4.1

**Comment by genereddick** [comment]
OK, updated code, updated NVidia. Some combination has fixed it. Thanks.

**Comment by genereddick** [comment]
I went through and updated everything and reinstalled with latest releases. This included Blender as well as the instant-ngp-exe, CUDA, CMake, Python, and my Nvidia graphics drivers. One or more of those seems to have fixed the issue and I can now import the obj file into Blender.

**Comment by LeoRainly** [comment]
facing the same issue! I export the .ply file, and when I open it with mesh lab:
![企业微信截图_20230516154623](https://github.com/NVlabs/instant-ngp/assets/34095097/a8f92795-8fad-4184-b4ac-e6ba8245f24e)
