### ISSUE TITLE
NeRFCapture Online/Stream mode makes Instant-ngp crash.

### ISSUE THREAD

**Issue by smallfly** [NVlabs/instant-ngp#1291]
Hello,

I'm trying to run NeRFCapture with the current master branch of instant-ngp.

I'm able to connect the two applications - NeRFCapture on iOS and instant-ngp on Windows - but as soon as I tap the 'send' button (to send the 1st image) instant-ngp closes.

Here is the error I get:
`TypeError: set_camera_extrinsics(): incompatible function arguments. The following argument types are supported:
    1. (self: pyngp.Testbed.Nerf.Training, frame_idx: int, camera_to_world: mat4x3, convert_to_ngp: bool = True) -> None`

**Comment by Tom94** [comment]
Thanks for reporting; should be fixed with the latest version.
