### ISSUE TITLE
Does this operator support second order differentiation? (hashgrid) 

### ISSUE THREAD

**Issue by Dengzhi-USTC** [NVlabs/instant-ngp#131]
Hi, this is excellent work;
Does this operator support second order differentiation (hashgrid)? and do you implement it?

Thank you very much.

**Comment by Tom94** [comment]
Hi there, thank you for the kind words!

Whether higher-order derivatives are smooth depends entirely on the interpolation scheme.

The default linear interpolation is only C^0-smooth, but we discuss efficient approaches for arbitrary smoothness in Appendix A and at the end of Section 3 of [the paper](https://nvlabs.github.io/instant-ngp/assets/mueller2022instant.pdf). We've implemented a C^1-smooth interpolation that you can enable by setting `"interpolation" : "Smoothstep"` in the json config.

However, we _haven't_ implemented actual 2nd-order derivatives anywhere in the codebase/framework. Those would have to be implemented by you.

Cheers!

**Comment by Dengzhi-USTC** [comment]
Ok, thank you very much.
