### ISSUE TITLE
How to obtain camera's position (x,y,z)

### ISSUE THREAD

**Issue by jdiazram** [NVlabs/instant-ngp#1311]
Hi, excellent work.
I have a question. I am trying to find a way to draw the camera and position, like the picture below:

![nerfboxrobot](https://user-images.githubusercontent.com/45439493/229561309-a1395961-6fef-4fa4-acde-ef7f86cedb25.jpg)

This is created from the transformation matrix in the `transform.json`, right? If correct, how do you do it?
Thx

**Comment by Tom94** [comment]
See the red box that highlights the GUI checkboxed you need to activate.

**Comment by Lokesh-26** [comment]
> Thanks, but I mean the code... how do you implement it, or in which file do you do it?

@jdiazram, Were you able to find out the script?
