### ISSUE TITLE
Broken run.py --help command

### ISSUE THREAD

**Issue by swtyree** [NVlabs/instant-ngp#1315]
Currently the `--help` command in `scripts/run.py` is broken because of the following line:

https://github.com/NVlabs/instant-ngp/blob/76db82a7b38ac5c29ffc1aeefee69058991cb677/scripts/run.py#L55

When creating the help string, `argparse` interprets the `%` in `video_%04d.png` as a format string. Replacing that with `video_%%04d.png`(using `%%` to escape) solves the issue.

**Comment by Tom94** [comment]
Thank you very much -- fixed!
