### ISSUE TITLE
Error in cyclonedds while trying to launch nerfcapture2nerf.py

### ISSUE THREAD

**Issue by Eurasia33** [NVlabs/instant-ngp#1324]
/instant-ngp$ python3 scripts/nerfcapture2nerf.py --stream
1681325834.499222 [0]    python3: config: //CycloneDDS/Domain/Internal/MinimumSocketReceiveBufferSize: setting moved to //CycloneDDS/Domain/Internal/SocketReceiveBufferSize[@min] (CYCLONEDDS_URI+0 line 1)
1681325834.499342 [0]    python3: config: Domain/General/MulticastRecvNetworkInterfaceAddresses/#text: preferred {}
1681325834.499353 [0]    python3: config: Domain/General/ExternalNetworkAddress/#text: auto {}
1681325834.499358 [0]    python3: config: Domain/General/ExternalNetworkMask/#text: 0.0.0.0 {}
1681325834.499363 [0]    python3: config: Domain/General/AllowMulticast/#text: default {}
1681325834.499369 [0]    python3: config: Domain/General/MulticastTimeToLive/#text: 32 {}
1681325834.499374 [0]    python3: config: Domain/General/DontRoute/#text: false {}
1681325834.499379 [0]    python3: config: Domain/General/Transport/#text: udp {}
1681325834.499384 [0]    python3: config: Domain/General/EnableMulticastLoopback/#text: true {}
1681325834.499390 [0]    python3: config: Domain/General/MaxMessageSize/#text: 14720 B {}
1681325834.499396 [0]    python3: config: Domain/General/MaxRexmitMessageSize/#text: 1456 B {}
1681325834.499403 [0]    python3: config: Domain/General/FragmentSize/#text: 1344 B {}
1681325834.499407 [0]    python3: config: Domain/General/RedundantNetworking/#text: false {}
1681325834.499413 [0]    python3: config: Domain/General/EntityAutoNaming/#text: empty {}
1681325834.499419 [0]    python3: config: Domain/General/EntityAutoNaming[@seed]: 3573500938 2156505753 836053083 246786082 344480237 4185591631 2466657679 1455497689 {}
1681325834.499426 [0]    python3: config: Domain/Sizing/ReceiveBufferSize/#text: 1 MiB {}
1681325834.499431 [0]    python3: config: Domain/Sizing/ReceiveBufferChunkSize/#text: 128 KiB {}
1681325834.499437 [0]    python3: config: Domain/Compatibility/StandardsConformance/#text: lax {}
1681325834.499442 [0]    python3: config: Domain/Compatibility/ExplicitlyPublishQosSetToDefault/#text: false {}
1681325834.499447 [0]    python3: config: Domain/Compatibility/ManySocketsMode/#text: single {}
1681325834.499452 [0]    python3: config: Domain/Compatibility/AssumeRtiHasPmdEndpoints/#text: false {}
1681325834.499457 [0]    python3: config: Domain/Discovery/Tag/#text:  {}
1681325834.499468 [0]    python3: config: Domain/Discovery/ExternalDomainId/#text: 0 {}
1681325834.499474 [0]    python3: config: Domain/Discovery/DSGracePeriod/#text: 30 s {}
1681325834.499480 [0]    python3: config: Domain/Discovery/ParticipantIndex/#text: none {}
1681325834.499485 [0]    python3: config: Domain/Discovery/MaxAutoParticipantIndex/#text: 9 {}
1681325834.499490 [0]    python3: config: Domain/Discovery/SPDPMulticastAddress/#text: 239.255.0.1 {}
1681325834.499495 [0]    python3: config: Domain/Discovery/SPDPInterval/#text: 30 s {}
1681325834.499501 [0]    python3: config: Domain/Discovery/DefaultMulticastAddress/#text: auto {}
1681325834.499507 [0]    python3: config: Domain/Discovery/Ports/Base/#text: 7400 {}
1681325834.499512 [0]    python3: config: Domain/Discovery/Ports/DomainGain/#text: 250 {}
1681325834.499518 [0]    python3: config: Domain/Discovery/Ports/ParticipantGain/#text: 2 {}
1681325834.499523 [0]    python3: config: Domain/Discovery/Ports/MulticastMetaOffset/#text: 0 {}
1681325834.499528 [0]    python3: config: Domain/Discovery/Ports/UnicastMetaOffset/#text: 10 {}
1681325834.499533 [0]    python3: config: Domain/Discovery/Ports/MulticastDataOffset/#text: 1 {}
1681325834.499539 [0]    python3: config: Domain/Discovery/Ports/UnicastDataOffset/#text: 11 {}
1681325834.499544 [0]    python3: config: Domain/Discovery/EnableTopicDiscoveryEndpoints/#text: false {}
1681325834.499549 [0]    python3: config: Domain/Discovery/LeaseDuration/#text: 10 s {}
1681325834.499559 [0]    python3: config: Domain/Tracing/Category/#text: fatal,error,warning,info,config {1}
1681325834.499565 [0]    python3: config: Domain/Tracing/OutputFile/#text: stdout {1}
1681325834.499570 [0]    python3: config: Domain/Tracing/AppendToFile/#text: false {}
1681325834.499575 [0]    python3: config: Domain/Tracing/PacketCaptureFile/#text:  {}
1681325834.499581 [0]    python3: config: Domain/Internal/DeliveryQueueMaxSamples/#text: 256 {}
1681325834.499586 [0]    python3: config: Domain/Internal/PrimaryReorderMaxSamples/#text: 128 {}
1681325834.499591 [0]    python3: config: Domain/Internal/SecondaryReorderMaxSamples/#text: 128 {}
1681325834.499596 [0]    python3: config: Domain/Internal/DefragUnreliableMaxSamples/#text: 4 {}
1681325834.499602 [0]    python3: config: Domain/Internal/DefragReliableMaxSamples/#text: 16 {}
1681325834.499607 [0]    python3: config: Domain/Internal/BuiltinEndpointSet/#text: writers {}
1681325834.499612 [0]    python3: config: Domain/Internal/MeasureHbToAckLatency/#text: false {}
1681325834.499617 [0]    python3: config: Domain/Internal/UnicastResponseToSPDPMessages/#text: true {}
1681325834.499622 [0]    python3: config: Domain/Internal/SynchronousDeliveryPriorityThreshold/#text: 0 {}
1681325834.499627 [0]    python3: config: Domain/Internal/SynchronousDeliveryLatencyBound/#text: inf {}
1681325834.499632 [0]    python3: config: Domain/Internal/MaxParticipants/#text: 0 {}
1681325834.499637 [0]    python3: config: Domain/Internal/AccelerateRexmitBlockSize/#text: 0 {}
1681325834.499642 [0]    python3: config: Domain/Internal/RetransmitMerging/#text: never {}
1681325834.499648 [0]    python3: config: Domain/Internal/RetransmitMergingPeriod/#text: 5 ms {}
1681325834.499653 [0]    python3: config: Domain/Internal/HeartbeatInterval/#text: 100 ms {}
1681325834.499659 [0]    python3: config: Domain/Internal/HeartbeatInterval[@min]: 5 ms {}
1681325834.499665 [0]    python3: config: Domain/Internal/HeartbeatInterval[@minsched]: 20 ms {}
1681325834.499670 [0]    python3: config: Domain/Internal/HeartbeatInterval[@max]: 8 s {}
1681325834.499676 [0]    python3: config: Domain/Internal/MaxQueuedRexmitBytes/#text: 512 KiB {}
1681325834.499682 [0]    python3: config: Domain/Internal/MaxQueuedRexmitMessages/#text: 200 {}
1681325834.499687 [0]    python3: config: Domain/Internal/WriterLingerDuration/#text: 1 s {}
1681325834.499693 [0]    python3: config: Domain/Internal/SocketReceiveBufferSize[@min]: 10 MiB {1}
1681325834.499698 [0]    python3: config: Domain/Internal/SocketReceiveBufferSize[@max]: default {}
1681325834.499704 [0]    python3: config: Domain/Internal/SocketSendBufferSize[@min]: 64 KiB {}
1681325834.499709 [0]    python3: config: Domain/Internal/SocketSendBufferSize[@max]: default {}
1681325834.499714 [0]    python3: config: Domain/Internal/NackDelay/#text: 100 ms {}
1681325834.499720 [0]    python3: config: Domain/Internal/AckDelay/#text: 10 ms {}
1681325834.499726 [0]    python3: config: Domain/Internal/AutoReschedNackDelay/#text: 3 s {}
1681325834.499731 [0]    python3: config: Domain/Internal/PreEmptiveAckDelay/#text: 10 ms {}
1681325834.499736 [0]    python3: config: Domain/Internal/ScheduleTimeRounding/#text: 0 s {}
1681325834.499741 [0]    python3: config: Domain/Internal/DDSI2DirectMaxThreads/#text: 1 {}
1681325834.499746 [0]    python3: config: Domain/Internal/SquashParticipants/#text: false {}
1681325834.499751 [0]    python3: config: Domain/Internal/SPDPResponseMaxDelay/#text: 0 s {}
1681325834.499757 [0]    python3: config: Domain/Internal/LateAckMode/#text: false {}
1681325834.499762 [0]    python3: config: Domain/Internal/RetryOnRejectBestEffort/#text: false {}
1681325834.499767 [0]    python3: config: Domain/Internal/GenerateKeyhash/#text: false {}
1681325834.499772 [0]    python3: config: Domain/Internal/MaxSampleSize/#text: 2147483647 B {}
1681325834.499778 [0]    python3: config: Domain/Internal/WriteBatch/#text: false {}
1681325834.499783 [0]    python3: config: Domain/Internal/LivelinessMonitoring/#text: false {}
1681325834.499788 [0]    python3: config: Domain/Internal/LivelinessMonitoring[@StackTraces]: true {}
1681325834.499794 [0]    python3: config: Domain/Internal/LivelinessMonitoring[@Interval]: 1 s {}
1681325834.499800 [0]    python3: config: Domain/Internal/MonitorPort/#text: -1 {}
1681325834.499805 [0]    python3: config: Domain/Internal/PrioritizeRetransmit/#text: true {}
1681325834.499810 [0]    python3: config: Domain/Internal/UseMulticastIfMreqn/#text: 0 {}
1681325834.499815 [0]    python3: config: Domain/Internal/RediscoveryBlacklistDuration/#text: 0 s {}
1681325834.499820 [0]    python3: config: Domain/Internal/RediscoveryBlacklistDuration[@enforce]: false {}
1681325834.499826 [0]    python3: config: Domain/Internal/MultipleReceiveThreads/#text: default {}
1681325834.499831 [0]    python3: config: Domain/Internal/MultipleReceiveThreads[@maxretries]: 4294967295 {}
1681325834.499837 [0]    python3: config: Domain/Internal/Test/XmitLossiness/#text: 0 {}
1681325834.499843 [0]    python3: config: Domain/Internal/Watermarks/WhcLow/#text: 1 KiB {}
1681325834.499848 [0]    python3: config: Domain/Internal/Watermarks/WhcHigh/#text: 500 KiB {}
1681325834.499854 [0]    python3: config: Domain/Internal/Watermarks/WhcHighInit/#text: 30 KiB {}
1681325834.499859 [0]    python3: config: Domain/Internal/Watermarks/WhcAdaptive/#text: true {}
1681325834.499864 [0]    python3: config: Domain/Internal/BurstSize/MaxRexmit/#text: 1 MiB {}
1681325834.499870 [0]    python3: config: Domain/Internal/BurstSize/MaxInitTransmit/#text: 4294967295 {}
1681325834.499875 [0]    python3: config: Domain/Internal/EnableExpensiveChecks/#text:  [ignored] {}
1681325834.499880 [0]    python3: config: Domain/TCP/NoDelay/#text: true {}
1681325834.499885 [0]    python3: config: Domain/TCP/Port/#text: -1 {}
1681325834.499890 [0]    python3: config: Domain/TCP/ReadTimeout/#text: 2 s {}
1681325834.499896 [0]    python3: config: Domain/TCP/WriteTimeout/#text: 2 s {}
1681325834.499900 [0]    python3: config: Domain/TCP/AlwaysUsePeeraddrForUnicast/#text: false {}
1681325834.499906 [0]    python3: config: Domain[@Id]: 0 {1}
1681325834.499931 [0]    python3: started at 1681325834.06499912 -- 2023-04-13 02:57:14+08:00
1681325834.499936 [0]    python3: udp initialized
1681325834.500385 [0]    python3: interfaces: lo udp/127.0.0.1(q1) eno2 udp/101.6.69.23(q9) docker0 udp/172.17.0.1(q9)
1681325834.500394 [0]    python3: using network interface eno2 (udp/101.6.69.23) selected arbitrarily from: eno2, docker0
1681325834.500394 [0]    python3: using network interface eno2 (udp/101.6.69.23) selected arbitrarily from: eno2, docker0
1681325834.500401 [0]    python3: selected interfaces: eno2 (index 3 priority 0)
1681325834.500406 [0]    python3: presumed robust multicast support, use for everything
1681325834.500420 [0]    python3: ownip: udp/101.6.69.23
1681325834.500424 [0]    python3: extmask: invalid/0 (not applicable)
1681325834.500429 [0]    python3: SPDP MC: udp/239.255.0.1
1681325834.500433 [0]    python3: default MC: udp/239.255.0.1
1681325834.500436 [0]    python3: SSM support included
1681325834.500536 [0]    python3: failed to increase socket receive buffer size to at least 10485760 bytes, current is 425984 bytes
1681325834.500536 [0]    python3: failed to increase socket receive buffer size to at least 10485760 bytes, current is 425984 bytes
1681325834.500569 [0]    python3: udp finalized
Traceback (most recent call last):
  File "scripts/nerfcapture2nerf.py", line 233, in <module>
    domain = Domain(domain_id=0, config=dds_config)
  File "/home/wangyihe/.local/lib/python3.8/site-packages/cyclonedds/domain.py", line 34, in __init__
    super().__init__(self._create_domain(dds_c_t.domainid(domain_id), config.encode("ascii")))
  File "/home/wangyihe/.local/lib/python3.8/site-packages/cyclonedds/core.py", line 181, in __init__
    raise DDSException(
cyclonedds.core.DDSException: [DDS_RETCODE_ERROR] Non specific error. Occurred upon initialisation of a cyclonedds.domain.Domain

the version of cyclonedds is 0.10.2

**Comment by Eurasia33** [comment]
solved by change the net.core.wmem_max & net.core.rmem_max

**Comment by Marco-Nguyen** [comment]
Hi @Eurasia33 , where and how did you change the net.core.wmem_max & net.core.rmem_max?

**Comment by hitcm** [comment]
@Marco-Nguyen  

sudo sysctl -w net.core.wmem_max=12582912
sudo sysctl -w net.core.rmem_max=12582912
