### ISSUE TITLE
GLFW error #65542: WGL: The driver does not appear to support OpenGL

### ISSUE THREAD

**Issue by YanMednis** [NVlabs/instant-ngp#1328]
Hi! I have the Nvidia L4 GPU on the Windows server 2022 in VM Google Cloud. Connecting through RDC.
This is a new GPU as I understand it for Cloud & Data Center, the drivers are new as well. It is also strange that NVIDIA L4 GPU does not show in taskmanager and graphics preference, only in device manager and Nvidia control panel but without the ability to change the settings (screen attached).

Please tell me how to solve this problem.

(ngp) C:\Users\yan\ngp\instant-ngp>C:\Users\yan\ngp\instant-ngp\build\instant-ngp.exe --scene data/wa
09:16:25 SUCCESS  Initialized CUDA. Active GPU is #0: NVIDIA L4 [89]
09:16:25 INFO     Loading NeRF dataset from
09:16:25 INFO       data\wa\transforms.json
09:21:00 SUCCESS  Loaded 516 images after 4m34s
09:21:00 INFO       cam_aabb=[min=[-0.92625,-1.22333,0.233323], max=[1.96481,1.85531,0.753785]]
09:22:07 ERROR    GLFW error #65542: WGL: The driver does not appear to support OpenGL
09:22:07 ERROR    Uncaught exception: GLFW window could not be created.

Link with screenshots
https://drive.google.com/drive/folders/1zxHhCKdD32UyE_B3pHaDBKdDx3zuZ6aR?usp=share_link

Thank you for your attention to my question.

**Comment by YanMednis** [comment]
It looks like the drivers are still raw for this GPU and it's in preview. Works on another GPU.

**Comment by qinhang3** [comment]
Same at Nvidia A30..
