### ISSUE TITLE
error when use cmake --build build --config RelWithDebInfo  

### ISSUE THREAD

**Issue by youqugit** [NVlabs/instant-ngp#1336]
my system info：
gcc (GCC) 11.2.0
cmake version 3.26.0
cuda version 12.0

The error info：
[  3%] Built target optix_program
[  5%] Building C object dependencies/glfw/src/CMakeFiles/glfw_objects.dir/x11_init.c.o
/ai/user/tmp/instant-ngp/dependencies/glfw/src/x11_init.c: In function ‘createKeyTables’:
/ai/user/tmp/instant-ngp/dependencies/glfw/src/x11_init.c:366:13: error: ‘for’ loop initial declarations are only allowed in C99 mode
             for (int i = 0;  i < sizeof(keymap) / sizeof(keymap[0]);  i++)
             ^
/ai/user/tmp/instant-ngp/dependencies/glfw/src/x11_init.c:366:13: note: use option -std=c99 or -std=gnu99 to compile your code
/ai/user/tmp/instant-ngp/dependencies/glfw/src/x11_init.c:378:22: error: redefinition of ‘i’
             for (int i = 0;  i < desc->names->num_key_aliases;  i++)
                      ^
/ai/user/tmp/instant-ngp/dependencies/glfw/src/x11_init.c:366:22: note: previous definition of ‘i’ was here
             for (int i = 0;  i < sizeof(keymap) / sizeof(keymap[0]);  i++)
                      ^
/ai/user/tmp/instant-ngp/dependencies/glfw/src/x11_init.c:378:13: error: ‘for’ loop initial declarations are only allowed in C99 mode
             for (int i = 0;  i < desc->names->num_key_aliases;  i++)
             ^
/ai/user/tmp/instant-ngp/dependencies/glfw/src/x11_init.c:390:17: error: ‘for’ loop initial declarations are only allowed in C99 mode
                 for (int j = 0;  j < sizeof(keymap) / sizeof(keymap[0]);  j++)
                 ^
/ai/user/tmp/instant-ngp/dependencies/glfw/src/x11_init.c: In function ‘hasUsableInputMethodStyle’:
/ai/user/tmp/instant-ngp/dependencies/glfw/src/x11_init.c:445:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (unsigned int i = 0;  i < styles->count_styles;  i++)
     ^
/ai/user/tmp/instant-ngp/dependencies/glfw/src/x11_init.c: In function ‘inputMethodInstantiateCallback’:
/ai/user/tmp/instant-ngp/dependencies/glfw/src/x11_init.c:487:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (_GLFWwindow* window = _glfw.windowListHead;  window;  window = window->next)
         ^
/ai/user/tmp/instant-ngp/dependencies/glfw/src/x11_init.c: In function ‘getAtomIfSupported’:
/ai/user/tmp/instant-ngp/dependencies/glfw/src/x11_init.c:500:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (unsigned long i = 0;  i < atomCount;  i++)
     ^
gmake[2]: *** [dependencies/glfw/src/CMakeFiles/glfw_objects.dir/x11_init.c.o] Error 1
gmake[1]: *** [dependencies/glfw/src/CMakeFiles/glfw_objects.dir/all] Error 2
gmake: *** [all] Error 2

**Comment by youqugit** [comment]
在Cmakelist.txt中增加set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c99")即可

**Comment by QXmX29** [comment]
It helps!!! Thank you very much!!! ❤
