### ISSUE TITLE
When running "cmake . -B build" it asks for nvcc file in Cuda.  I use a MacBook pro with Monterey OS and Cuda v10.

### ISSUE THREAD

**Issue by slancheros** [NVlabs/instant-ngp#134]
instant-ngp macpro15$ cmake . -B build
CMake Error at /usr/local/Cellar/cmake/3.22.2/share/cmake/Modules/CMakeDetermineCUDACompiler.cmake:115 (message):
  Could not find nvcc executable in path specified by environment variable
  CUDAToolkit_ROOT=/usr/local/cuda
Call Stack (most recent call first):
  CMakeLists.txt:11 (PROJECT)

-- Configuring incomplete, errors occurred!
See also "/Users/macpro15/instant-ngp/build/CMakeFiles/CMakeOutput.log".
See also "/Users/macpro15/instant-ngp/build/CMakeFiles/CMakeError.log".
:instant-ngp macpro15$

In which installation should it find the nvcc executable?  have tried both v 11 and v10

Thank you

**Comment by Tom94** [comment]
Hi there, unfortunately macOS isn't supported by this codebase due to not running CUDA-compatible GPUs these days.

**Comment by slancheros** [comment]
Thanks for clarifying
