### ISSUE TITLE
Crop Box, Mesh and Save without GUI

### ISSUE THREAD

**Issue by panoslepen** [NVlabs/instant-ngp#1351]
Hey it is possible to customize the Crop Box size and then to Mesh my object and save only via script **without GUI**?

**Comment by nianjiuhuiyi** [comment]
You can add "--no-gui" to start it without GUI. And you can change the "Translate  crop box" of  initial value by modify source code.

**Comment by Lanson426** [comment]
Hello, have you solved it yet

**Comment by Lanson426** [comment]
> 您可以添加“--no-gui”以在没有 GUI 的情况下启动它。并且您可以通过修改源代码来更改“翻译裁剪框”的初始值。

May I ask which file code should be modified?

**Comment by panoslepen** [comment]
about bounding box in path InstantNGP\include\neural-graphics-primitives in bounding_box.cuh i just made changes in struct BoundingBox at NGP_HOST_DEVICE BoundingBox() function... About mesh it and save it  in path InstantNGP\src i made changes in testbed.cu to automate the buttons. When you make your changes you must build all that again.

**Comment by Lanson426** [comment]
I understand what you mean. I also tried to change the m_render_aabb part of tesdbed-cu yesterday and only changed the error when I recmake. I think I must have corrected the mistake,I can't read the code,Could you tell me in detail how to modify it? Thank you very much!!
<img width="644" alt="Snipaste_2023-05-31_19-54-56" src="https://github.com/NVlabs/instant-ngp/assets/126304570/d2b69955-8429-45e0-98ed-4368f6b6ef64">
