### ISSUE TITLE
Missing XR_KHR_OPENGL extension

### ISSUE THREAD

**Issue by lWilbert2** [NVlabs/instant-ngp#1354]
Hey, I'm facing weird issues when connecting to my VR headset.
It was working before and has now suddenly stopped ( I use the HP Reverb 2) . I tracked the issue down to be originating from the missing extension: `XR_KHR_OPENGL_ENABLE_EXTENSION_NAME` which expands to _"XR_KHR_opengl_enable"_  in:
src/openxr_hmd.cu : 199 and the corresponding check at:
src/openxr_hmd.cu : 276

I really can't see how this extension suddenly vanished and I'm too unexperienced with this stuff to investigate any further from here.

This problems is probably not originating from here, but maybe someone  could lead me to the right direction on how to enable this extension or where it has gone/vanished in the first place. I'll attach a screenshot of the _Open-XR-Tools for Windows Mixed Reality_, where it lists all extensions. The mentioned opengl extension is not listed there ...

![image](https://github.com/NVlabs/instant-ngp/assets/73698592/c028e768-5aa4-4f74-bf6a-970d63a3476a)

Any help would be greatly appreciated :)

**Comment by deeedob** [comment]
I have the same issue! Does anyone know what's going on?

**Comment by MartinMisiak** [comment]
The OpenXR runtime implemented by Windows Mixed Reality does not seem to support the opengl extension. You can use the SteamVR OpenXR runtime instead. For this to work, SteamVR should be set as the default OpenXR runtime. This can be set in the developer settings of SteamVR.
