### ISSUE TITLE
Error when trying to download GTX-1000.zip

### ISSUE THREAD

**Issue by CaveSurveys** [NVlabs/instant-ngp#1374]
The GTX-1000  Installation section do not have any style information associated with it. 
RTX 2000, and 3/4000 compiled links are however working 

https://github.com/NVlabs/instant-ngp/releases/download/continuous/Instant-NGP-for-GTX-1000.zip

**Comment by Tom94** [comment]
Hi, thanks for letting me know. Should be fixed now.
