### ISSUE TITLE
How can I save and load the state?

### ISSUE THREAD

**Issue by resurgo97** [NVlabs/instant-ngp#141]
I hope to save the current state of the model (i.e. trained parameters) and load it to resume training (or only inference) in future.
Is there any available API that does the trick?

Thanks.

**Comment by Tom94** [comment]
Hi there, you can use the GUI's snapshot loading/saving buttons or you can use the Python bindings' `testbed.load_snapshot` / `testbed.save_snapshot` (see `scripts/run.py` for example usage).

Cheers!

**Comment by resurgo97** [comment]
Perfect, Thanks!
