### ISSUE TITLE
Non-zero samples' dir gradient when using Empty dir_encoding

### ISSUE THREAD

**Issue by vincentcartillier** [NVlabs/instant-ngp#1415]
Hello,

I am noticing that when training iNGP without direction encoding the `coords_gradient_matrix` variable ($\frac{\partial \mathcal{L}}{\partial \vec{inputs}}$) - in `train_nerf_step` [here](https://github.com/NVlabs/instant-ngp/blob/090aed613499ac2dbba3c2cede24befa248ece8a/src/testbed_nerf.cu#L2867)) - still shows gradient values for the direction vector. 

I think that's counter intuitive - since we're not using the dir vector as input there shouldn't be any gradients or jacobian $\frac{\partial \mathcal{L}}{\partial \vec{dir}}$.

Interestingly enough that's only happening for when I use a `target_batch_size` lower than 256000. 

Here is an example where I report 10 randomly selected samples from `coords_gradient_matrix` (each sample returns 7 variables - 3 for pos, 1 for dt, and 3 for dir) without dir encoding:

```
       "dir_encoding": {
             "otype": "Empty"
       },
```

- batch_size=256000:
```
[[ 2.00812428e-04  5.24832401e-04 -1.61436576e-04  0.00000000e+00 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.04228174e-03 -2.43640025e-04  1.35364709e-03  0.00000000e+00 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.70485553e-04 -2.66102143e-05  5.18667861e-04  0.00000000e+00 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 9.54439020e-05 -1.56564347e-04 -9.86027531e-04  0.00000000e+00 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 7.87385739e-04  1.82316336e-03  8.15070962e-05  0.00000000e+00 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 4.92581108e-04  3.26355163e-04 -1.54399010e-03  0.00000000e+00 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.00558483e-04 -1.29924098e-03 -1.30350841e-03  0.00000000e+00 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.36448396e-03  9.98350675e-04 -5.35742322e-04  0.00000000e+00 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.48878701e-03  1.72411371e-03  7.70722283e-04  0.00000000e+00 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 2.74705281e-03  5.20685222e-03 -3.21195368e-03  0.00000000e+00 0.00000000e+00  0.00000000e+00  0.00000000e+00]]
```

- batch_size=128000:
```
[[ 8.12243111e-03 -9.44881467e-05  9.63091094e-04  2.18999885e-05 -2.27798225e-08  3.01677646e-04  1.04643519e-07]
 [ 6.45978423e-03 -5.08802431e-03 -1.30060334e-02 -5.14333333e-05 1.78471328e-05 -2.84837345e-08  7.94079911e-04]
 [ 4.19362485e-02  1.27936052e-02 -1.16119431e-02 -2.26123211e-05 -2.85775550e-05  1.43475299e-05 -8.50662119e-08]
 [-1.49408937e-04  1.40267303e-02 -1.19566526e-02  3.63920117e-06 -1.10082665e-05 -2.65509352e-05  1.99925980e-05]
 [-1.17289592e-02  1.73727330e-02 -6.42052526e-03  1.66149228e-04 3.05805042e-06 -1.90361316e-05 -3.59355690e-05]
 [-1.15968902e-02  4.06329846e-03  2.47230958e-02  1.56834297e-08 8.87960778e-05  1.02238243e-06 -7.29212934e-06]
 [-4.36887378e-03 -5.47620002e-04  3.64330448e-02  1.95145985e-04 5.31778310e-09  4.15364011e-05  2.17204402e-07]
 [ 6.94419665e-04  2.15195562e-03  1.17028495e-02 -3.41510864e-09 5.88082512e-05  1.43855539e-09  1.30660619e-05]
 [ 1.23307272e-03 -9.87538719e-04 -1.47786166e-03  8.51975301e-07-1.54744761e-09  4.33116948e-05  8.97529329e-10]
 [ 1.66139667e-04  9.51323251e-04  1.78541103e-03 -1.30918602e-06 4.37159883e-07 -1.79485971e-09  1.60537857e-05]]
```
Clearly something is going on. The last 3 columns, which correspond to the gradients w.r.t the dir vector is different in both cases.

I am wondering if the `floats_per_coords` should be different for that matrix in that specific case - like 4 instead of 7. Or if something is missing in the Empty encoder backward implementation. I haven't looked much into the tiny-cuda-nn code yet. 

That said I wanted to check here whether I missed anything or if you had any pointers to help me clarify this!

Thanks again for the amazing work!

**Comment by vincentcartillier** [comment]
I still haven't found the source of the issue - I have checked the implementation of the `Empty` encoder and the backward implementation does seem to return 0. 

While I am not sure what's the issue (might be something I am missing) - I have implemented a quick workaround. Here is how it is if anyone is interested:

You can check within the `train_nerf_step()` function whether we are using an empty dir encoding as follow:

```
	std::string dir_encoding = m_network_config["dir_encoding"].value("otype", "none");
	bool is_dir_encoding_empty = dir_encoding == "Empty";
```

Then pass it as an argument to the cuda function `compute_cam_gradient_train_nerf()`. And within that function just zero out the gradients w.r.t the dir.

```
		if (is_dir_encoding_empty) {
			dir_gradient = {0.,0.,0.};
		}
```

That's super hacky but seems to have solved my problem - I can now properly train and optimize for camera poses without dir encoding. 

(leaving open in case the authors want to provide additional feedback - happy to close otherwise).

**Comment by Tom94** [comment]
Hi Vincent, even pure translational gradients of the samples along rays induce a rotational gradient in the camera (i.e. in `coords_gradient_matrix`). See this diagram, where x is a sample along a ray, o is the ray origin and d is the ray direction

<img width="970" alt="Screenshot 2023-08-05 at 06 34 47" src="https://github.com/NVlabs/instant-ngp/assets/4923655/aeb9cca2-325d-4e30-98bf-4f66c8e15af4">

To make more intuitive sense of it, consider that tweaking the camera orientation (i.e. d) causes a translation of x and so the chain rule between the two variables should not be zero.

The effect of the MLPs output (which is indeed decoupled from the ray direction when using `EmptyEncoding`) is an additional additive term.

**Comment by vincentcartillier** [comment]
Hi Thomas,

Thanks for you reply. I confirm that this fixes the issue.

To clarify (if others are reading this), in the title of this issue when I mentioned "samples" I meant samples along a ray (vs pixel samples or rays). These should have a zero gradient w.r.t the dir when using Empty dir encoding. However, the ultimate camera pose gradient can still have a non-zero gradient w.r.t to the dir. 

Thanks again Thomas for your help!
