### ISSUE TITLE
problem with opening certain jpg files

### ISSUE THREAD

**Issue by dozeri83** [NVlabs/instant-ngp#1434]
The current stb_image code in the dependencies (v2.7) fail to open some JPG files.
it fails with the error "unknown marker".
 
The images came from DJI drone.

when I update the code of stb_image to v2.8 the problem is resolved.
(for your consideration)

**Comment by Tom94** [comment]
Thanks for letting me know (and apologies for the late response). stb_image is now updated -- it's nice that they fixed this!
