### ISSUE TITLE
"TypeError: unsupported operand type(s) for /: 'str' and 'str'" when using detectron2 masks in Windows

### ISSUE THREAD

**Issue by neonascent** [NVlabs/instant-ngp#1447]
Error: 
`Traceback (most recent call last):
  File "F:\Instant-NGP-for-RTX-3000-and-4000\scripts\colmap2nerf.py", line 434, in <module>
    category2id = json.load(open(SCRIPTS_FOLDER / "category2id.json", "r"))
`

Seems to be because it's forming the json file name wrong.  Fixed it with 

`category2id = json.load(open(os.path.join(SCRIPTS_FOLDER, "category2id.json"), "r"))`

at this line

https://github.com/NVlabs/instant-ngp/blob/7d5e858bba5885bbc593fc65e337e4410b992bef/scripts/colmap2nerf.py#L434C3-L434C74

**Comment by Tom94** [comment]
Thanks for reporting -- this looks like an oversight when switching from `pathlib` back to `os.path`. Fixed on master.
