### ISSUE TITLE
cmake config not working

### ISSUE THREAD

**Issue by anton-brandl** [NVlabs/instant-ngp#1448]
The README way of setting cmake build type does not seem to work for me but I might have found another way.

### Problem

I wanted to have debug flags to be able to step through inside vscode using the NSight toolkit which didn't seem to work out of the box.
I compile instant-ngp as explained in the readme. I run the two lines inside a Dockerfile:
```
instant-ngp$ cmake . -B build
instant-ngp$ cmake --build build --config RelWithDebInfo -j 16
```
However, the build config flag `RelWithDebInfo` doesn't seem to create any debug flags for me and it seems to compile in `Release` mode instead.
Even when changing to `--config Debug`, I will not have any debug flags in the created shared object file:

```
instant-ngp/build# file pyngp.cpython-311-x86_64-linux-gnu.so
pyngp.cpython-311-x86_64-linux-gnu.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=7ad1956ce66565528c9e982915c954afb6369458, not stripped
```

### Possible Solution?
What **does work** for getting debug flags is the following using the `CMAKE_BUILD_TYPE` flag during configuration:
```
RUN cmake -DNGP_BUILD_WITH_GUI=off -DPython_EXECUTABLE=/usr/bin/python3.11 -DCMAKE_BUILD_TYPE=RelWithDebInfo ./ -B ./build
RUN cmake --build build --target pyngp -j 16
```

### Versions
cmake version 3.22.1

**Comment by Tom94** [comment]
Hi, the trouble is that _some_ generators (like `msbuild` on Windows) expect the config at build time via `--config RelWithDebInfo` and some others (like `make` on Linux) at configure time via `-DCMAKE_BUILD_TYPE=RelWithDebInfo`. It doesn't hurt to use both to make it work anywhere -- and that's what the README should have listed. Thanks for reporting, I fixed it.
