### ISSUE TITLE
Testbed directory and files missing after Instant-ngp install

### ISSUE THREAD

**Issue by Rubenbe75** [NVlabs/instant-ngp#1451]
Hello!

I have a Windows 10 system where I have installed Instant-ngp per the GitHub instructions, but at the end of the process I checked the contents of the C:\ngp\instant-ngp\build directory and I realized the testbed directory and files were missing. In addition I am missing the pyngp directory and files. 

![image](https://github.com/NVlabs/instant-ngp/assets/50259499/71596173-4f7a-427e-aa96-f9a5dec76272)

According to the YouTube tutorial from Bycloudai (https://www.youtube.com/watch?v=kq9xlvz73Rg), the absence of these files means I need to debug the install and make it generate the testbed file successfully. 

I will greatly appreciate any suggestion to do the debugging. 

Thank you kindly!

**Comment by Rubenbe75** [comment]
I no longer have this issue as it appears that the testbed.exe file is no longer used in the current version of instant-ngp.

**Comment by willcel** [comment]
thanks, i'm learning from a jupyterNotebook in 2022, went across the same issue "can't find testbed".
I'm wondering, where can i find a updated notebook.... i will have to go through some discussions here
