### ISSUE TITLE
Compilation error: src/optix/pathescape.cu(77): error: identifier "to_float3" is undefined

### ISSUE THREAD

**Issue by duklin** [NVlabs/instant-ngp#1514]
The fail happens because of the [Fix CI compilation](https://github.com/NVlabs/instant-ngp/commit/829e20ff09ff6ebbdbacd39bf0629ebe5ae4f83d) commit.

The methods `to_float3` and `to_float4` are still used in the repository and are removed in the commit. 

By simply restoring the two methods, the build is successful.

**Comment by Tom94** [comment]
The reason the functions were removed is that they are now part of the tiny-cuda-nn submodule. You should be able to fix compilation by running ‘git submodule update —-recursive’ rather than adding the functions back.
