### ISSUE TITLE
Which TurboSquid Models Were Used For SDF Evaluation?

### ISSUE THREAD

**Issue by ThumbmasWalker** [NVlabs/instant-ngp#1548]
Dear Authors,

Thank you for your work!

You evaluate the SDF fitting experiment on certain TurboSquid models (as well as NGLOD), however I cannot find exactly which models you use for comparisons. Could you kindly point me towards the models you used? I cannot find this information in both this publication or NGLOD.

Many thanks

**Comment by Tom94** [comment]
Here you go:
- Lizard: https://www.turbosquid.com/de/3d-models/3d-model-mech-lizard/915002
- Cow: https://www.turbosquid.com/de/3d-models/cow-steampunk-robot-model-1144070
- Clockwork: I can't find the source link myself at the moment, sorry.

And here's the bearded man:
- https://www.myminifactory.com/object/3d-print-portrait-of-a-bearded-man-27383
