### ISSUE TITLE
Disney cloud format seems to be different from your demo

### ISSUE THREAD

**Issue by Jiakai-Zhang** [NVlabs/instant-ngp#161]
Hi guys, congrats on your great work!

Now I am trying to play with your cloud demo and I have successfully downloaded the raw dataset from your provided page.

The question is in your command line: the file name is ``wdas_cloud_quarter.nvdb`` but the raw data is ``wdas_cloud_quarter.vdb``, it seems to be not a typo as I have tried modifying it but I get an internal error, could you please tell me how to fix it, maybe there are some tools to convert these two types?

**Comment by Tom94** [comment]
Hi there, you have to download the nano-VDB volume (`.nvdb`) from [here](https://drive.google.com/drive/folders/1SuycSAOSG64k2KLV7oWgyNWyCvZAkafK) -- not the VDB volume from the original Disney source.

The README links to both, which is admittedly a little confusing. I'll have a go a clearing it up.
