### ISSUE TITLE
issue running colmap2nerf.py

### ISSUE THREAD

**Issue by wtpro** [NVlabs/instant-ngp#174]
while running 

python colmap2nerf.py --colmap_matcher exhaustive --run_colmap --aabb_scale 16

on my own images, an error popped out:

==== running: mkdir colmap_sparse
==== running: colmap mapper --database_path colmap.db --image_path images --output_path colmap_sparse
ERROR: Failed to parse options: unrecognised option '--output_path'.
FATAL: command failed

It seems output_path is not a valid argument for some reason.

**Comment by Tom94** [comment]
COLMAP documentation suggests that it is: https://colmap.github.io/cli.html

Shot in the dark: could you be running an older version?

**Comment by wtpro** [comment]
Yes, I am using COLMAP 3.4 and the correct argument should be ''export_path'' instead of ''output_path''. 

Thanks, your shot in the dark is very precise.

**Comment by flow-dev** [comment]
The same applies if COLMAP 3.3 is used. The correct argument must be ''export_path'', not ''output_path''.

**Comment by Howie-Ye** [comment]
> The same applies if COLMAP 3.3 is used. The correct argument must be ''export_path'', not ''output_path''.

I encountered the same issue. Could you tell me more specifically which ''output_path'' should be replaced by ''export_path''? 
I have tried several times and the ERROR became:  Failed to parse options:  unrecognised option '--export_path'.
