### ISSUE TITLE
CMake Error in CMakeLists.txt

### ISSUE THREAD

**Issue by BaldPolnareff** [NVlabs/instant-ngp#188]
```
CMake Error in CMakeLists.txt:
  No known features for CXX compiler

  "GNU"

  version 11.2.0.
```

**Comment by Ednaordinary** [comment]
Delete ./instant-ngp/build/ and try again, see if that works

**Comment by BaldPolnareff** [comment]
> Delete ./instant-ngp/build/ and try again, see if that works

It worked! I didn't notice there was a cache file related to Cmake inside of /build/ that might have caused issues! Thank you!
