### ISSUE TITLE
Build problem: the generated default constructor cannot be used in an initializer for its own data member

### ISSUE THREAD

**Issue by qwopqwop200** [NVlabs/instant-ngp#19]
It succeeded until I did "cmake . -B build". But at "cmake --build build --config RelWithDebInfo -j 16" I get an error.

> (MAD) root@qwopqwop-B560M-AORUS-PRO-AX:/home/qwopqwop/project/instant-ngp# cmake --build build --config RelWithDebInfo -j 16
Consolidate compiler generated dependencies of target tiny-cuda-nn
Consolidate compiler generated dependencies of target glfw_objects
[ 29%] Built target glfw_objects
[ 50%] Built target tiny-cuda-nn
Consolidate compiler generated dependencies of target ngp
[ 52%] Building CUDA object CMakeFiles/ngp.dir/src/testbed.cu.o
[ 54%] Building CUDA object CMakeFiles/ngp.dir/src/testbed_image.cu.o
[ 56%] Building CUDA object CMakeFiles/ngp.dir/src/testbed_nerf.cu.o
[ 58%] Building CUDA object CMakeFiles/ngp.dir/src/testbed_sdf.cu.o
[ 60%] Building CUDA object CMakeFiles/ngp.dir/src/testbed_volume.cu.o
/home/qwopqwop/project/instant-ngp/include/neural-graphics-primitives/testbed.h(629): error: the generated default constructor for "ngp::Testbed::Volume" cannot be used in an initializer for its own data member
/home/qwopqwop/project/instant-ngp/include/neural-graphics-primitives/testbed.h(601): error: the generated default constructor for "ngp::Testbed::Image" cannot be used in an initializer for its own data member
/home/qwopqwop/project/instant-ngp/include/neural-graphics-primitives/testbed.h(575): error: the generated default constructor for "ngp::Testbed::Sdf" cannot be used in an initializer for its own data member
/home/qwopqwop/project/instant-ngp/include/neural-graphics-primitives/testbed.h(525): error: the generated default constructor for "ngp::Testbed::Nerf" cannot be used in an initializer for its own data member
/home/qwopqwop/project/instant-ngp/include/neural-graphics-primitives/testbed.h(629): error: the generated default constructor for "ngp::Testbed::Volume" cannot be used in an initializer for its own data member
/home/qwopqwop/project/instant-ngp/include/neural-graphics-primitives/testbed.h(601): error: the generated default constructor for "ngp::Testbed::Image" cannot be used in an initializer for its own data member
/home/qwopqwop/project/instant-ngp/include/neural-graphics-primitives/testbed.h(575): error: the generated default constructor for "ngp::Testbed::Sdf" cannot be used in an initializer for its own data member
/home/qwopqwop/project/instant-ngp/include/neural-graphics-primitives/testbed.h(525): error: the generated default constructor for "ngp::Testbed::Nerf" cannot be used in an initializer for its own data member
/home/qwopqwop/project/instant-ngp/include/neural-graphics-primitives/testbed.h(629): error: the generated default constructor for "ngp::Testbed::Volume" cannot be used in an initializer for its own data member
/home/qwopqwop/project/instant-ngp/include/neural-graphics-primitives/testbed.h(601): error: the generated default constructor for "ngp::Testbed::Image" cannot be used in an initializer for its own data member
/home/qwopqwop/project/instant-ngp/include/neural-graphics-primitives/testbed.h(575): error: the generated default constructor for "ngp::Testbed::Sdf" cannot be used in an initializer for its own data member
/home/qwopqwop/project/instant-ngp/include/neural-graphics-primitives/testbed.h(525): error: the generated default constructor for "ngp::Testbed::Nerf" cannot be used in an initializer for its own data member
/home/qwopqwop/project/instant-ngp/include/neural-graphics-primitives/testbed.h(629): error: the generated default constructor for "ngp::Testbed::Volume" cannot be used in an initializer for its own data member
/home/qwopqwop/project/instant-ngp/include/neural-graphics-primitives/testbed.h(601): error: the generated default constructor for "ngp::Testbed::Image" cannot be used in an initializer for its own data member
/home/qwopqwop/project/instant-ngp/include/neural-graphics-primitives/testbed.h(575): error: the generated default constructor for "ngp::Testbed::Sdf" cannot be used in an initializer for its own data member
/home/qwopqwop/project/instant-ngp/include/neural-graphics-primitives/testbed.h(525): error: the generated default constructor for "ngp::Testbed::Nerf" cannot be used in an initializer for its own data member
/home/qwopqwop/project/instant-ngp/include/neural-graphics-primitives/testbed.h(629): error: the generated default constructor for "ngp::Testbed::Volume" cannot be used in an initializer for its own data member
/home/qwopqwop/project/instant-ngp/include/neural-graphics-primitives/testbed.h(601): error: the generated default constructor for "ngp::Testbed::Image" cannot be used in an initializer for its own data member
/home/qwopqwop/project/instant-ngp/include/neural-graphics-primitives/testbed.h(575): error: the generated default constructor for "ngp::Testbed::Sdf" cannot be used in an initializer for its own data member
/home/qwopqwop/project/instant-ngp/include/neural-graphics-primitives/testbed.h(525): error: the generated default constructor for "ngp::Testbed::Nerf" cannot be used in an initializer for its own data member
4 errors detected in the compilation of "/home/qwopqwop/project/instant-ngp/src/testbed_volume.cu".
make[2]: *** [CMakeFiles/ngp.dir/build.make:300: CMakeFiles/ngp.dir/src/testbed_volume.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
4 errors detected in the compilation of "/home/qwopqwop/project/instant-ngp/src/testbed_image.cu".
make[2]: *** [CMakeFiles/ngp.dir/build.make:258: CMakeFiles/ngp.dir/src/testbed_image.cu.o] Error 1
4 errors detected in the compilation of "/home/qwopqwop/project/instant-ngp/src/testbed_sdf.cu".
make[2]: *** [CMakeFiles/ngp.dir/build.make:286: CMakeFiles/ngp.dir/src/testbed_sdf.cu.o] Error 1
4 errors detected in the compilation of "/home/qwopqwop/project/instant-ngp/src/testbed.cu".
make[2]: *** [CMakeFiles/ngp.dir/build.make:244: CMakeFiles/ngp.dir/src/testbed.cu.o] Error 1
4 errors detected in the compilation of "/home/qwopqwop/project/instant-ngp/src/testbed_nerf.cu".
make[2]: *** [CMakeFiles/ngp.dir/build.make:272: CMakeFiles/ngp.dir/src/testbed_nerf.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:172: CMakeFiles/ngp.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by HauNan** [comment]
The same error occurs in 
CUDA11.1 
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.

[build.log](https://github.com/NVlabs/instant-ngp/files/7880586/build.log)
0

**Comment by jkzhu** [comment]
It can be solved by deleting the variable like m_volume at the end of struct, then add a new line:

struct Volume m_volume;

**Comment by Tom94** [comment]
I just pushed an attempted fix to `master`. Could you build again and let me know if it resolves the issue?

**Comment by HauNan** [comment]
@Tom94 Thanks for the fix and I seem to have successfully completed the compilation.
![2022-01-17 21-56-15 的屏幕截图](https://user-images.githubusercontent.com/39771156/149793671-b3a927e6-2e79-4a56-8f00-b125d59e4657.png)

**Comment by Tom94** [comment]
Awesome, glad to hear! :)
