### ISSUE TITLE
I am on pop os and get this error when i am tring to build:

### ISSUE THREAD

**Issue by Manni1000** [NVlabs/instant-ngp#196]
Error Message:
CMake Error at /usr/local/share/cmake-3.23/Modules/CMakeDetermineCUDACompiler.cmake:310 (message):
  CMAKE_CUDA_ARCHITECTURES must be valid if set.
Call Stack (most recent call first):
  CMakeLists.txt:11 (PROJECT)
i instaled cuda with this guide:
https://support.system76.com/articles/cuda/
I am not sure if i instaled cuda wrong or if i did somthing other wrong cani please get help

**Comment by Manni1000** [comment]
i have the cuda version 11.4
and the cmake version 3.23.0-rc1

**Comment by Manni1000** [comment]
[CMakeError.log](https://github.com/NVlabs/instant-ngp/files/8104142/CMakeError.log)

**Comment by Manni1000** [comment]
i have a laptop so i have two gpus baby thats the problem also cuda migt is on a place wher cmake dosnt think it is. but i am not sure to solve this

**Comment by Manni1000** [comment]
i added set(CMAKE_CUDA_ARCHITECTURES 61) to the cmakelist.txt and now i get this error 
The CMAKE_CUDA_ARCHITECTURES:

    61

  do not all work with this compiler.  Try:

    

  instead.

**Comment by Ghanimalg** [comment]
Try: ?

I am currently struggling w the cmake CUDA architecture, getting a response like:

-- Selecting Windows SDK version  to target Windows 10.0.19042.
CMake Error at C:/Program Files/CMake/share/cmake-3.23/Modules/CMakeDetermineCUDACompiler.cmake:310 (message):
  CMAKE_CUDA_ARCHITECTURES must be valid if set.
Call Stack (most recent call first):
  CMakeLists.txt:11 (PROJECT)

**Comment by Marmiya** [comment]
Try this:
set(CMAKE_CUDA_ARCHITECTURES 52 60 61 75 86)

**Comment by Ghanimalg** [comment]
I tried restarting the code tutorial from start, but I'm getting this now:

-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.31.31104.0
-- The CXX compiler identification is MSVC 19.31.31104.0
-- The CUDA compiler identification is unknown
CMake Error at C:/Program Files/CMake/share/cmake-3.23/Modules/CMakeDetermineCUDACompiler.cmake:632 (message):
  Failed to detect a default CUDA architecture.



  Compiler output:

Call Stack (most recent call first):
  CMakeLists.txt:11 (PROJECT)

**Comment by Ghanimalg** [comment]
> Try this: set(CMAKE_CUDA_ARCHITECTURES 52 60 61 75 86)
So I ended up on the same boat that I started on, use your suggestion but unfortunately it was not defined:

"Environment variable (CMAKE_CUDA_ARCHITECTURES 52 60 61 75 86) not defined"

**Comment by Manni1000** [comment]
> Try this:
> set(CMAKE_CUDA_ARCHITECTURES 52 60 61 75 86)
> 


I added it to the text file and now I get the same error but instead of 61 the other numbers are also there. 

And I know it's strange that betwen
 try: 
And
 insted
Is nothing

**Comment by Manni1000** [comment]
Ther is also the message the Cuda compiler identification is unknown

**Comment by Ghanimalg** [comment]
is it a part of the NVIDIA CUDA installer?

**Comment by Ghanimalg** [comment]
im sorry, i never really touched github or anything coding in my life, I'm j trying out new things

**Comment by Ghanimalg** [comment]
now its saying:

CMAKE_CUDA_ARCHITECTURES must be valid if set

**Comment by Ghanimalg** [comment]
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
CMake Error at C:/Program Files/CMake/share/cmake-3.23/Modules/CMakeDetermineCUDACompiler.cmake:310 (message):
  CMAKE_CUDA_ARCHITECTURES must be valid if set.
Call Stack (most recent call first):
  CMakeLists.txt:11 (PROJECT)

**Comment by Ghanimalg** [comment]
I solved my problem, I just did everything on the internet in regards to my previous comments.

**Comment by Manni1000** [comment]
but my problem isnt solved :c

**Comment by Rovexx** [comment]
I had the same issue where i got the error `CMAKE_CUDA_ARCHITECTURES must be valid if set` But i found that i installed CMake 3.23.0-rc1 instead of the latest stable version 3.22.2 at the time of writing this.
After installing the previous version i didnt get the error anymore.

_*I am now getting an error that the C compiler cant compile a simple test program but that is probably unrelated._

**Comment by Tom94** [comment]
Glad to hear it got resolved!

**Comment by Camilochiang** [comment]
This problem persist with Cmake 3.23 . Had to downgrade to make it work

**Comment by JonasDeSchouwer** [comment]
> This problem persist with Cmake 3.23 . Had to downgrade to make it work

After downgrading, I ran into the error `Failed to find a working CUDA architecture.` This may have been caused by Cmake 3.23 leaving some traces in build/CMakeFiles. Recloning the repo solved the issue.

**Comment by LanHao0** [comment]
> > This problem persist with Cmake 3.23 . Had to downgrade to make it work
> 
> After downgrading, I ran into the error `Failed to find a working CUDA architecture.` This may have been caused by Cmake 3.23 leaving some traces in build/CMakeFiles. Recloning the repo solved the issue.

delete the `build` folder will do the trick too

**Comment by cilence** [comment]
The new version of CMAKE will have this problem. It is recommended to use version 3.22

**Comment by KnightOfTheMoonlight** [comment]
For me  cmake 3.25.2, cuda  11.2 I have added `set(CMAKE_CUDA_ARCHITECTURES "70")` just before the following block of  `CMakeLists.txt
```
if(CUDA_ENABLED AND CUDA_FOUND)
    if(NOT DEFINED CMAKE_CUDA_ARCHITECTURES)
        message(
            FATAL_ERROR "You must set CMAKE_CUDA_ARCHITECTURES to e.g. 'native', 'all-major', '70', etc. "
            "More information at https://cmake.org/cmake/help/latest/prop_tgt/CUDA_ARCHITECTURES.html")
    endif()

    add_definitions("-DCUDA_ENABLED")
```
