### ISSUE TITLE
space in path building bug

### ISSUE THREAD

**Issue by Krulknul** [NVlabs/instant-ngp#198]
I just spent a while trying to get the program to build, as I kept getting the error:

`[Fatal: A single input file is required for a non-link phase when an outputfile is specified`

in the second cmake command. It was difficult to fix but eventually I found the solution. There was a space in the path I was working in. This caused cmake to give the error. 

My path was:   `:C:\Users\Krulknul\Desktop\nvidia ai\instant-ngp`
Changing it to `:C:\Users\Krulknul\Desktop\nvidia-ai\instant-ngp`
fixed the problem

Maybe this can be added to the list for troubleshooting?

This is my first ever Github contribution so please excuse me if I'm doing it wrong. Thought this would be important to share :)

**Comment by Tom94** [comment]
Wow, I hadn't thought spaces in paths were still a problem for build systems these days.

You're definitely doing the "GitHub contribution" thing right. Thanks for letting me know. Will add. :)
