### ISSUE TITLE
compiling problems trying to build

### ISSUE THREAD

**Issue by ThomasCodeMonkey** [NVlabs/instant-ngp#202]
I worked through everything up to the build, working through a few other errors, resolved by getting CUDA setup, etc. but now this one isn't in the common build diagnostic. There's a bunch of red in the command line after the build, and the seem to break out into 4 categories:

error : more than one conversion function from "tcnn::network_precision_t" to a built-in type applies
error : name followed by "::" must be a class or namespace name
exited with code 1
error : no operator "+=" matches these operands

with a bunch of various file paths, but those appear to be the core of the error messages, there's dozens of each (over 4k lines of output in the shell, most of it not errors)

No idea where to start on this. Am I still missing a dependency somewhere, even though creating the build file went OK?

Thanks,

**Comment by ThomasCodeMonkey** [comment]
Ok, I'm still a noob, so some more context that's probably super important, but was super hard to see digging through the command line. Pasted everything into a code editor for better searching through, and pattern pops out right away:

Search "errors" (4 hits in 1 file of 1 searched)
  new 1 (4 hits)
	Line 1240:   24 errors detected in the compilation of "C:/Work/Code/Python/instant-ngp/dependencies/tiny-cuda-nn/src/cutlass_mlp.c
	Line 1591:   8 errors detected in the compilation of "C:/Work/Code/Python/instant-ngp/dependencies/tiny-cuda-nn/src/encoding.cu".
	Line 4083:   100 errors detected in the compilation of "C:/Work/Code/Python/instant-ngp/dependencies/tiny-cuda-nn/src/fully_fused_
	Line 4142:   26 errors detected in the compilation of "C:/Work/Code/Python/instant-ngp/dependencies/tiny-cuda-nn/src/cutlass_resne


So, all problems look like they trace back to a "tiny-cuda-nn" dependency. I did a git --recursive dependency update right before, though, so I think I should still have the most up to date version of everything.

**Comment by Xiragi** [comment]
Had the same issue but the answer at #194 worked for me.

**Comment by ThomasCodeMonkey** [comment]
Just realized this is a duplicate of #194, which was opened less than 24 hrs ago. I will close now.
