### ISSUE TITLE
Composite Kernel Nerf

### ISSUE THREAD

**Issue by jc211** [NVlabs/instant-ngp#203]
In this code snippet:
https://github.com/NVlabs/instant-ngp/blob/cd1cf2edf9170653fb60bb281f10d9ef59e05fea/src/testbed_nerf.cu#L811-L821

Seems like https://github.com/NVlabs/instant-ngp/blob/cd1cf2edf9170653fb60bb281f10d9ef59e05fea/src/testbed_nerf.cu#L811 is ignored when https://github.com/NVlabs/instant-ngp/blob/cd1cf2edf9170653fb60bb281f10d9ef59e05fea/src/testbed_nerf.cu#L821 is hit.

Maybe L811 should be:
```cpp
local_rgba = local_rgba /local_rgba.w();
```

**Comment by Tom94** [comment]
Good catch, fixed. Thank you!

Thankfully, this doesn't meaningfully affect our results (we've used `min_alpha = 1e-4f`), but it's good to have it behave as intended.
