### ISSUE TITLE
TypeError: Invalid arg for PNG writer: 'quality' and 'subsampling' 

### ISSUE THREAD

**Issue by bruinxiong** [NVlabs/instant-ngp#206]
There are some inappropriate parameters (quality and subsampling) in imageio.imwrite function of scripts/common.py (line 124).
They should be removed. Please refer this link https://github.com/imageio/imageio/blob/master/imageio/plugins/pillow_legacy.py , the description of "Parameters for saving" or line 437-447.

The code snippet should be modified as follow:

def write_image_imageio(img_file, img, quality):
	img = (np.clip(img, 0.0, 1.0) * 255.0 + 0.5).astype(np.uint8)
	# imageio.imwrite(img_file, img, quality=quality, subsampling=0)
	imageio.imwrite(img_file, img)

**Comment by Tom94** [comment]
Good catch! Already fixed it (less than an hour ago) here: https://github.com/NVlabs/instant-ngp/commit/bcfe8502ac6935566a1daed48eab53c1093a7842
