### ISSUE TITLE
OSError: JPEG does not support alpha channel

### ISSUE THREAD

**Issue by bruinxiong** [NVlabs/instant-ngp#209]
if you want to save image file with .jpg or .jpeg.
it will raise IOError("JPEG does not support alpha channel.")

Please refer this link https://github.com/imageio/imageio/blob/master/imageio/plugins/pillow_legacy.py , the description of "Parameters for saving" or line 437-447.

The code snippet should be modified as follow:
	kwargs = {}
	if os.path.splitext(img_file)[1].lower() in [".jpg", ".jpeg"]:
		img = img[:,:,:3]
		kwargs["quality"] = quality
		kwargs["subsampling"] = 0
	imageio.imwrite(img_file, img, **kwargs)

**Comment by Tom94** [comment]
Fixed! Thanks again -- totally overlooked it when migrating from directly calling PIL.
