### ISSUE TITLE
Build problem on Windows: No known features for CXX compiler "MSVC"

### ISSUE THREAD

**Issue by ifilipis** [NVlabs/instant-ngp#21]
When running `cmake . -B build` I get

> CMake Error in CMakeLists.txt:
>   No known features for CXX compiler
> 
>   "MSVC"
> 
>   version 19.29.30136.0.

What features is it missing? Where do I look for that?

**Comment by jk4011** [comment]
Please look at https://github.com/NVlabs/instant-ngp/issues/18

**Comment by ifilipis** [comment]
> Please look at #18

It's a different one. I've found the solution for CUDA toolkit, too

**Comment by jk4011** [comment]
This might help. https://github.com/mitsuba-renderer/mitsuba2/issues/103#issuecomment-618378963

**Comment by ifilipis** [comment]
> This might help. [mitsuba-renderer/mitsuba2#103 (comment)](https://github.com/mitsuba-renderer/mitsuba2/issues/103#issuecomment-618378963)

I have a different issue that this

**Comment by WXuanyang** [comment]
Got the same problem here, did you find a solution? I'm using MSVC 342 btw

**Comment by WXuanyang** [comment]
> Got the same problem here, did you find a solution? I'm using MSVC 342 btw

Hummm I reinstalled vs2019 and it somehow works, I don't know why but maybe you can also have a try

**Comment by mhalber** [comment]
For whomever is encountering this problem:
Make sure you run a cmake in command line environment in which cl.exe can be found - if you have BuildTools installed, then Native Tools Command Prompt gives you this. Additionally, make sure to remove any previous cmake cache.

**Comment by ifilipis** [comment]
> if you have BuildTools installed, then Native Tools Command Prompt gives you this. Additionally, make sure to remove any previous cmake cache.

Yes! This worked!

**Comment by Ricky-Millar** [comment]
Hey, still getting this same issue with a reinstall and trying Native Tools. not sure how to further troubleshoot.

**Comment by compressionist** [comment]
Hey everyone, I'm having a similar issue on a Linux machine (ubuntu 22.04):

CMake Error in CMakeLists.txt:
  No known features for CXX compiler

  "GNU"

  version 9.3.0.

Do you know how to fix it?

**Comment by TheUniquePaulSmith** [comment]
![image](https://user-images.githubusercontent.com/19433370/160252974-87f3f807-025e-48a4-814d-9a4a994f40dd.png)


> Hey, still getting this same issue with a reinstall and trying Native Tools. not sure how to further troubleshoot.

Same here

**Comment by yuse94** [comment]
> ![image](https://user-images.githubusercontent.com/19433370/160252974-87f3f807-025e-48a4-814d-9a4a994f40dd.png)
> 
> > Hey, still getting this same issue with a reinstall and trying Native Tools. not sure how to further troubleshoot.
> 
> Same here

I right clicked inside the folder where I needed to run the compiler and clicked show more options, and selected the option to open with Visual Studio. A folder called .vs was created run the command line and it worked

**Comment by ciwolsey** [comment]
For anyone who still has issues after getting cl.exe into your path etc - make sure you remove the "build" directory before running cmake again.

**Comment by koktavy** [comment]
@ciwolsey What should the cl.exe path entry look like? What is the location of the "build" folder, should it have been created inside the "instant-ngp" repo folder?

**Comment by erich666** [comment]
> What should the cl.exe path entry look like? What is the location of the "build" folder, should it have been created inside the "instant-ngp" repo folder?

In case it's a help, I had the same error, evidently because Cmake tried to run Visual Studio 2022's compiler by default. I removed the "build" directory in GitHub\instant-ngp (which gets rid of the cached compiler settings), then did this:

`cmake . -B build -G "Visual Studio 16 2019"`

followed by the usual:

`cmake --build build --config RelWithDebInfo -j 16`

This worked for me.

**Comment by wowo0709** [comment]
> > What should the cl.exe path entry look like? What is the location of the "build" folder, should it have been created inside the "instant-ngp" repo folder?
> 
> In case it's a help, I had the same error, evidently because Cmake tried to run Visual Studio 2022's compiler by default. I removed the "build" directory in GitHub\instant-ngp (which gets rid of the cached compiler settings), then did this in the Developer Command Prompt (for VS 2022, which might have been the wrong one to use...):
> 
> `cmake . -B build -G "Visual Studio 16 2019"`
> 
> followed by the usual:
> 
> `cmake --build build --config RelWithDebInfo -j 16`
> 
> This worked for me.
> 
> Also, you'll find the Developer Command Prompt executable in "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Visual Studio 2019\Visual Studio Tools" (or 2022).

This worked for me! Thanks!

**Comment by Aimarl0** [comment]
> > What should the cl.exe path entry look like? What is the location of the "build" folder, should it have been created inside the "instant-ngp" repo folder?
> 
> In case it's a help, I had the same error, evidently because Cmake tried to run Visual Studio 2022's compiler by default. I removed the "build" directory in GitHub\instant-ngp (which gets rid of the cached compiler settings), then did this in the Developer Command Prompt (for VS 2022, which might have been the wrong one to use...):
> 
> `cmake . -B build -G "Visual Studio 16 2019"`
> 
> followed by the usual:
> 
> `cmake --build build --config RelWithDebInfo -j 16`
> 
> This worked for me.
> 
> Also, you'll find the Developer Command Prompt executable in "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Visual Studio 2019\Visual Studio Tools" (or 2022).

worked for me! Thanks!

**Comment by DmitriGoloubentsev** [comment]
I had same error message, but none of the above helped me.
I used shared folder between linux and windows guest to store source tree. After I moved source to C:\ the problem went away. huh.
