### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by minorai** [NVlabs/instant-ngp#210]
Hi, I am experiencing an out of memory error trying to create a mesh with 1024x1024x1024 resolution from the Lego sample. My hardware is

- 2x Intel Xeon Gold 6136
- 128 GB RAM
- NVIDIA RTX A6000 48GB VRAM

Error log
```
13:27:53 ERROR    Uncaught exception: E:\projects\fun\instant-ngp\dependencies\tiny-cuda-nn\include\tiny-cuda-nn/gpu_memory.h:523 cuMemCreate(&m_handles.back(), n_bytes_to_allocate, &prop, 0) failed with error CUDA_ERROR_OUT_OF_MEMORY
Could not free memory: E:\projects\fun\instant-ngp\dependencies\tiny-cuda-nn\include\tiny-cuda-nn/gpu_memory.h:449 cuMemRelease(handle) failed with error CUDA_ERROR_INVALID_VALUE
```

How much memory is required to meshify this sample at 1024^3 resolution?

**Comment by minorai** [comment]
Additional logging shows that parameter passed to cuMemCreate (n_bytes_to_allocate) is 18446744056429019136, that would be 16 million terabytes. Something tells me there is an overflow happening somewhere.

**Comment by Tom94** [comment]
Good catch; I just pushed a fix (see https://github.com/NVlabs/instant-ngp/commit/85281a3cc381ad014f8ba8e62de35d35c190c8df) and confimed able to create a 1024x1024x1024 on my 3090. I also bumped the maximum resolution of the GUI to 2048.

Thanks!

**Comment by CK85** [comment]
Hi, I also get this error, when I try too high values like 1024. I have a RTX 3070 and 64 GB RAM. Can I achieve 1024 by allocating extra memory via changing the code or is it hardware limited?

**Comment by Tom94** [comment]
It's hardware-limited. Your CPU-side RAM does not matter here -- it's the GPU RAM that's important, and the 3070 does not have enough for 1024^3

**Comment by CK85** [comment]
Thanks for clarifying it! Looks like I need to buy a new RTX ;-)

**Comment by CK85** [comment]
Is it possible to download the lego mesh somewhere (e.g. google drive) with a 2048 resolution? I'm interested in how detailed it looks with the max settings.

**Comment by jiayaozhang** [comment]
@CK85 I find it here. 
The project page  `https://www.matthewtancik.com/nerf `
The Blender code `https://drive.google.com/drive/folders/128yBriW1IG_3NJ5Rp7APSTZsJqdJdfc1`

Therefore you can render any resolution you want from the blender file

**Comment by FacuM** [comment]
If you're **still** having this issue, play around with the `aabb_scale` parameter within `scripts/colmap2nerf.py`'s arguments or by manually modifying the transforms.json file.
