### ISSUE TITLE
A little bug in the "gather_histograms" function

### ISSUE THREAD

**Issue by resurgo97** [NVlabs/instant-ngp#212]
Hi. I report a little bug in the `gather_histograms` function in `src/testbed.cu` file.
In hash table, the number of entries are different at the larger levels.
However, they assume the same number of entries at every level as below.
```
int nperlevel = (int)(grid.size() / m_num_levels);
```
This leads to wrong statistics including range, mean, and std at the moment. 
`nperlevel` should be defined level by level, as in the constructor of `GridEncodingTemplated` in `grid.h`.

Thanks!

**Comment by Tom94** [comment]
Good catch! The histogram code was written at a time where we didn't use dense storage for the coarser levels and was neglected since -- we absolutely should fix this up.

**Comment by Tom94** [comment]
Fixed (finally)!
