### ISSUE TITLE
scripts/convert_image.py for gigapixel opt not functioning/I am not functioning it properly

### ISSUE THREAD

**Issue by Ghanimalg** [NVlabs/instant-ngp#217]
I am currently stuck in the process of converting to .jpg/.exr to .bin, whenever I launch the script (with the image inside the same folder) and it just shuts off immediately with no output. am I doing something wrong?

script dir: /instant-ngp/scripts/convert_image.py

Note: @Tom94 's tutorial (grateful for that) labels the script name as `scripts/image2bin.py`

**Comment by Tom94** [comment]
Hi there, apologies for this -- I broke the script when switching from the PIL backend to imageio.

It should be fixed now (see https://github.com/NVlabs/instant-ngp/commit/644aa9ec231ce21918d5f16f9a0696979e24cb10)

(I also updated the readme accordingly. Thanks for reporting!)

**Comment by Ghanimalg** [comment]
Amazing, thank you so much! I'll check back on it once I get back to office early morning.
