### ISSUE TITLE
ERROR    GLFW error #65542: GLX: GLX version 1.3 is required 13:17:40 ERROR

### ISSUE THREAD

**Issue by dandingbudanding** [NVlabs/instant-ngp#220]
I can build the proj, but when I run the demo as "sudo ./build/testbed --scene data/nerf/fox", I meet these errors,how can I solve it?

ERROR    GLFW error #65542: GLX: GLX version 1.3 is required
ERROR    Uncaught exception: GLFW window could not be created.

**Comment by bolshoytoster** [comment]
@dandingbudanding does [this](https://github.com/IntelRealSense/librealsense/issues/7343#issuecomment-693247135) help?
