### ISSUE TITLE
Could not allocate memory

### ISSUE THREAD

**Issue by StarsTesla** [NVlabs/instant-ngp#221]
When I tried to use my own data to reconstruct the object, I found that use low piexl images would be ok to run,like 1920 x 1080, but when I used the high piexl images shot from Nikon or Sony Camera, the error cames out:

15:22:29 ERROR    Uncaught exception: Could not allocate memory: /home/michael/code/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:109 cudaMalloc(&rawptr, n_bytes+DEBUG_GUARD_SIZE*2) failed with error out of memory

Using iPhone with less picture like within 100 is ok, but like 273 images, the error shows up, and use professional camera by 6000 x 4000 piexl ,the program would always goes down.

And shot a video with 1080p 30p, 1080p 60p, 4k 30p would be fine, but the problem is that there's always some noisy points to influence my reconstrction model quality, which looks like a cloud.

**Comment by StarsTesla** [comment]
Runs on computer:
Ubuntu 21
3080ti
i7 12
cuda 11.3
RAM 96G

**Comment by Tom94** [comment]
Hi there, https://github.com/NVlabs/instant-ngp/discussions/189 clarifies how you can calculate how many images of what resolution can fit into memory. Cheers!
