### ISSUE TITLE
MarchingCubes for Neural SDF occasionally crashes

### ISSUE THREAD

**Issue by theNded** [NVlabs/instant-ngp#237]
Hi, thanks for open-sourcing the great library.

I observed crashes when calling "Mesh it!" for neural SDF from relatively noisy input. The program crashes by throwing illegal memory access errors. After debugging, I can identify the chain of error is:

[Testbed::marching_cubes](https://github.com/NVlabs/instant-ngp/blob/bc52f44629d1e624ab581339a61b6cd41654e116/src/testbed_nerf.cu#L3026) -> [Testbed::compute_mesh_vertex_colors](https://github.com/NVlabs/instant-ngp/blob/bc52f44629d1e624ab581339a61b6cd41654e116/src/testbed_nerf.cu#L2930) -> [m_network->inference](https://github.com/NVlabs/instant-ngp/blob/bc52f44629d1e624ab581339a61b6cd41654e116/src/testbed_nerf.cu#L2946)

I suspect the error is from potentially incorrect reuse of the `NerfCoordinate` for SDF, since SDF takes `Vector3f` as coordinates, but I'm not sure.

A temporary fix for neural SDF is to disable `compute_mesh_vertex_colors` and copy from the positions or normals to the colors.

**Comment by Tom94** [comment]
Good catch; should be fixed now!
