### ISSUE TITLE
Windows build: No CMakeLists.txt file

### ISSUE THREAD

**Issue by maschere** [NVlabs/instant-ngp#24]
When running `cmake . -B` I get error messages like these and no project file is generated:

CMake Error at CMakeLists.txt:96 (add_subdirectory):
  The source directory C:/Users/Max/Documents/GIT/github/instant-ngp/dependencies/glfw does not contain a CMakeLists.txt file.

**Comment by mmalex** [comment]
Did you clone the repo with --recursive?
if not, you can remedy the situation with `git submodule init --recursive`
and `git submodule update --recursive` I think.

**Comment by maschere** [comment]
Ah I see. Yep I overlooked that. Thanks for the quick help!
