### ISSUE TITLE
Build error on Windows: CUDA_ARCHITECTURES is empty for target "cmTC_0c70f"

### ISSUE THREAD

**Issue by useronym** [NVlabs/instant-ngp#25]
Visual Studio Community 2022 (MSVC 143)
Cuda 11.6
CMake 3.22.1

Lots of compile errors 
[CMakeError.log](https://github.com/NVlabs/instant-ngp/files/7882775/CMakeError.log)
[CMakeOutput.log](https://github.com/NVlabs/instant-ngp/files/7882789/CMakeOutput.log)

Am I using a too-new buildchain?

**Comment by liguanglin** [comment]
https://stackoverflow.com/questions/67966258/cuda-architectures-is-empty-for-target-cmtc-28d80

**Comment by useronym** [comment]
I have tried to set the architecture manually according to that, but it has no effect. I suspect the error message is not completely relevant here, as there's a lot of compile errors (seen in `CMakeError.log`) when compiling include files:

```
#$ cicc --microsoft_version=1930 --msvc_target_version=1930 --compiler_bindir "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.30.30705/bin/HostX86/x86/../../../../../../.." --sdk_dir "C:/Program Files (x86)/Windows Kits/10/" --display_error_number --orig_src_file_name "CMakeCUDACompilerId.cu" --orig_src_path_name "E:\instant-ngp\build\CMakeFiles\3.22.1\CompilerIdCUDA\CMakeCUDACompilerId.cu" --allow_managed  -arch compute_52 -m64 --no-version-ident -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 --include_file_name "CMakeCUDACompilerId.fatbin.c" -tused --gen_module_id_file --module_id_file_name "tmp/CMakeCUDACompilerId.module_id" --gen_c_file_name "tmp/CMakeCUDACompilerId.cudafe1.c" --stub_file_name "tmp/CMakeCUDACompilerId.cudafe1.stub.c" --gen_device_file_name "tmp/CMakeCUDACompilerId.cudafe1.gpu"  "tmp/CMakeCUDACompilerId.cpp1.ii" -o "tmp/CMakeCUDACompilerId.ptx"
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\vcruntime.h(197): error: invalid redeclaration of type name "size_t"

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\vcruntime_new.h(48): error: first parameter of allocation function must be of type "size_t"

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\vcruntime_new.h(53): error: first parameter of allocation function must be of type "size_t"

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\vcruntime_new.h(59): error: first parameter of allocation function must be of type "size_t"

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\vcruntime_new.h(64): error: first parameter of allocation function must be of type "size_t"

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\vcruntime_new.h(166): error: first parameter of allocation function must be of type "size_t"

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\vcruntime_new.h(181): error: first parameter of allocation function must be of type "size_t"

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\vcruntime_new_debug.h(26): error: first parameter of allocation function must be of type "size_t"

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\vcruntime_new_debug.h(34): error: first parameter of allocation function must be of type "size_t"

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\type_traits(381): error: class template "std::_Is_memfunptr" has already been defined

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\type_traits(381): error: class template "std::_Is_memfunptr" has already been defined

...
```

**Comment by somisawa** [comment]
I solved the same error by setting CMAKE_CUDA_COMPILER. When running cmake, I ran `cmake . -B build -DCMAKE_CUDA_COMPILER=/usr/local/cuda-<your cuda version>/bin/nvcc` and then, this was solved in my case.

**Comment by useronym** [comment]
Unfortunately that has no effect either, in fact `nvcc` is already on my path anyway

**Comment by jaymefosa** [comment]
I had this error on Ubuntu 18.04 and although NVCC was in the path, setting it directly as somisawa recommended worked

**Comment by somisawa** [comment]
@jaymefosa 
That's nice. And if you face other warnings such as GPU not detected, it is also possibility caused by environmental arguments. Then, see Issue #28 .

**Comment by useronym** [comment]
Managed to get it to build. Instead of using the VS2022 developer powershell to run CMake directly, I imported the folder into VS and use the CMake integration. VS managed to do the build without any extra settings. Sounds like maybe there is something wrong with the VS2022 developer shell ¯\_(ツ)_/¯

**Comment by liuchangf** [comment]
I solved the problem by following cod 
  cmake . -B build -DCMAKE_CUDA_COMPILER="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/bin/nvcc.exe" -G"Visual Studio 15 2017 Win64"

**Comment by limberc** [comment]
You may installed the nvidia driver and nvcc in some way. For latest version, you can install nvidia driver using the 3rd party softwares. They may not identify you as a programmer and modify the CUDA path to somewhere else.
