### ISSUE TITLE
Build fails on W10x64: "static assertion failed with "MIN_GPU_ARCH=750 must bound __CUDA_ARCH__=520 from below, but doesn't"

### ISSUE THREAD

**Issue by Sam-Izdat** [NVlabs/instant-ngp#253]
- Windows 10 x64
- GTX 1650 (2 GPUs, second is AMD Radeon R7 200 Series)
- CUDA 11.6
- Optix 7.4.0 (env. path set)
- Visual Studio 17.1.0 2022 (initially)
- Visual Studio 16.11.10 2019 

Appears similar to #241 but I can't say for certain.

Tried building for VS 17 2022 from Developer Command Prompt for 2022.

    cmake . -G "Visual Studio 17 2022" -B build // OK
    cmake --build build --config RelWithDebInfo -j 16 // FAILURE

First error reads:

    Compiling CUDA source file ..\..\..\..\dependencies\tiny-cuda-nn\src\object.cu...
    <....>\instant-ngp\dependencies\tiny-cuda-nn\include\tiny-cuda-nn/common.h(224): error : static assertion
    failed with "MIN_GPU_ARCH=750 must bound __CUDA_ARCH__=520 from below, but doesn't." [<....>\instant-ngp
    \build\dependencies\tiny-cuda-nn\src\tiny-cuda-nn.vcxproj]

\- followed by long cascade of other errors.

Installed VS 16 2019. Reinstalled CUDA 11.6. Rebooted. Deleted cmake cache. Tried building for VS 16 2019 from Developer Command Prompt for 2019.

    cmake . -G "Visual Studio 16 2019" -B build // OK
    cmake --build build --config RelWithDebInfo -j 16 // FAILURE

Same error. Suspected multiple GPU confusion. Tried setting environment variables:

    TCNN_CUDA_ARCHITECTURES=75
    NVIDIA_VISIBLE_DEVICES=$gpu_id
    CUDA_VISIBLE_DEVICES=0

No change.

**Comment by Tom94** [comment]
Shot in the dark: are you using CMake's latest stable release or rc1?

Based on similar issues cropping up in the past couple of days, it seems that rc1 passes incorrect flags to nvcc, resulting in your error. In case this applies to you, could you try installing CMake 3.22.2 (latest release) to see whether it resolves the issue?

**Comment by Sam-Izdat** [comment]
Yes, looks like cmake version is 3.23.0-rc1.

**Comment by thopedam** [comment]
I had the same issue using cmake 3.23.0-rc1 and can confirm that 3.22.2 works.

**Comment by Sam-Izdat** [comment]
@Tom94 That worked! Looks like your shot in the dark was right on target. Thank you.

**Comment by Tom94** [comment]
Thanks for confirming. I'll add a "loud and clear" error to the cmake file that points this out

**Comment by WPCJATH** [comment]
> I had the same issue using cmake 3.23.0-rc1 and can confirm that 3.22.2 works.

This makes sense in my case: Win10 x64 3080
