### ISSUE TITLE
Failed to detect a default CUDA architecture. Build Error

### ISSUE THREAD

**Issue by Hat-The-Second** [NVlabs/instant-ngp#262]
Hello,
I have a gtx 1650 graphics card, cuda 11.6, cmake 3.23 and visual studio 2019.
When i try to build instant-ngp i get the following error
`
J:\Programme\instant-ngp>cmake . -B build
-- Building for: NMake Makefiles
-- The C compiler identification is MSVC 19.29.30140.0
-- The CXX compiler identification is MSVC 19.29.30140.0
-- The CUDA compiler identification is unknown
CMake Error at C:/Program Files/CMake/share/cmake-3.23/Modules/CMakeDetermineCUDACompiler.cmake:632 (message):
  Failed to detect a default CUDA architecture. Compiler output:
`
 `
Call Stack (most recent call first):
  CMakeLists.txt:11 (PROJECT)
`
`
-- Configuring incomplete, errors occurred!
See also "J:/Programme/instant-ngp/build/CMakeFiles/CMakeOutput.log".
See also "J:/Programme/instant-ngp/build/CMakeFiles/CMakeError.log".
`
Cuda nvcc compiler is in Path

Everything except for the instant-ngp folder is saved in C:\

 Help is apreciated

**Comment by kdand35** [comment]
Hi, same problem for me. How did you solve this problem?

**Comment by Fqlox** [comment]
Got the same issue, with VS 2019, cmake 3.23, cuda 11.6, and a RTX 2070.

**Comment by fl0w2Bloom** [comment]
error message: `Compiling the CUDA compiler identification source file "CMakeCUDACompilerId.cu" failed.`, but I don't know how to solve it

**Comment by VibraniumQ** [comment]
> error message: `Compiling the CUDA compiler identification source file "CMakeCUDACompilerId.cu" failed.`, but I don't know how to solve it

Changing Generator to "Visual Studio 17 2022" rather than "ninja" works for me, which means that you need to add the argument `-G "Visual Studio 17 2022 Win64"`
