### ISSUE TITLE
Docker/VScode container fails to launch

### ISSUE THREAD

**Issue by JPaulMora** [NVlabs/instant-ngp#263]
The image builds successfully* on Windows 11 WSL2, but it fails to launch and displays the error below.

```
Error response from daemon: Unknown runtime specified nvidia
```

For context, here's my specs:
AMD 3900x
GPU RTX 3060
RAM 32GB

*I had to setup my `~/.wslconfig` to 24GB of RAM, otherwise compiler was being killed due to OOM.

**Comment by JPaulMora** [comment]
Update, I've fixed this by removing `platform: nvidia` from the docker compose script. Seems now you have to use `gpus: all`.

**Comment by Tom94** [comment]
Fixed by https://github.com/NVlabs/instant-ngp/pull/287
