### ISSUE TITLE
Error: Must specify either a mode or a scene

### ISSUE THREAD

**Issue by WaltReu** [NVlabs/instant-ngp#276]
![image](https://user-images.githubusercontent.com/85451729/155880431-9a9887a1-ac9b-4a13-b6b3-176478cd561a.png)

Also if i use the command given in the example for Fox scene, I get:

![image](https://user-images.githubusercontent.com/85451729/155880401-e37497f5-6347-4145-9262-317e885de11c.png)

**Comment by JoanCharmant** [comment]
Try using absolute path first. And the "data" directory is not under the build directory so this would never work.

**Comment by WaltReu** [comment]
Thanks for the quick reply! I got this:

![image](https://user-images.githubusercontent.com/85451729/155881770-dfaff40d-10a7-447b-95c5-1c50c11b882c.png)

**Comment by JoanCharmant** [comment]
Use --config argument and point it to the absolute path of the json config file.

**Comment by WaltReu** [comment]
I'm having issues with both: 
![image](https://user-images.githubusercontent.com/85451729/155882020-615302fa-9a82-4732-b5b3-5dd8b967f86d.png)

**Comment by WaltReu** [comment]
![image](https://user-images.githubusercontent.com/85451729/155882781-9892e931-1fa8-4d3c-9ea6-ec7cbb4ff56d.png)

**Comment by Hurleyworks** [comment]
I got around the config path errors by making specifying an absolute path to the config folder in main.cu at line  197
// Otherwise, load the network config and prepare for training
fs::path network_config_path = fs::path{"D:/ActiveWorks/OpenSource/ai/instant-ngp/configs"}/mode_str;

**Comment by WaltReu** [comment]
That worked, thank you!

**Comment by WaltReu** [comment]
> I got around the config path errors by specifying an absolute path to the config folder in main.cu at line 197 // Otherwise, load the network config and prepare for training fs::path network_config_path = fs::path{"D:/ActiveWorks/OpenSource/ai/instant-ngp/configs"}/mode_str;

Strangely this stopped working for some reason after I rebooted my computer. I tested with the edited and original main.cu file both..

**Comment by llluuulll** [comment]
Hi,

There is no need to overwrite anything in the main.cu
On Windows, just start from the main dir instant-npg and pass all your paths as relative
exemple:
C:\Dev\nvidia\instant-ngp>build\testbed.exe --scene data\nerf\fox
the .exe is purely optional it is working fine without
exemple:
C:\Dev\nvidia\instant-ngp>build\testbed --scene data\nerf\fox
