### ISSUE TITLE
Nothing is being rendered to the GUI

### ISSUE THREAD

**Issue by ECE-Engineer** [NVlabs/instant-ngp#280]
I'm running on:
- windows 10
- cuda 11.6
- visual studio 2022
- python 3.10.2
- cmake v3.22
- optix 7.4
- gpu type: rtx 30 series (cuda supported)

There are no errors at any point in the build process or when running the exe.
The "mesh it" option works and displays a mesh, but the image render never shows at any point. I just get a black screen.
The same behavior is observed for all 3 applications: nerf, sdf, image.

* I have tried removing the repo and re-cloning the repo several times to no avail of resolving the issue

**Comment by MarcoG5** [comment]
I am suffering the same issue with Ubuntu 18.04 and RTX 2080Ti GPU
The description is same as: https://github.com/NVlabs/instant-ngp/issues/207
I also tried compile for multiple times and it did not solve this issue

**Comment by danzeeeman** [comment]
any updates on this?  I've tried different versions of OptiX but nothing seems to work?

**Comment by sepigraph** [comment]
Getting the same issue with A6000 RTX card. I can see camera data, etc, in GUI but no rendered result.

**Comment by ernlavr** [comment]
Same here, has anyone managed to troubleshoot this?
Running this with Windows 10 and NVidia Rtx 3090 x2

**Comment by ernlavr** [comment]
I just realized that for some reason when I minimize and then maximize the GUI, the rendered image appears.

@ECE-Engineer  @sepigraph Maybe this works for you as well?

**Comment by sepigraph** [comment]
@ernlavr It appears you are right. I minimized then maximized, and now I can see the cloud data visualized.

I'm guessing this might have to do with 4K monitors...

**Comment by ECE-Engineer** [comment]
> I just realized that for some reason when I minimize and then maximize the GUI, the rendered image appears.
> 
> @ECE-Engineer @sepigraph Maybe this works for you as well?

it did!
Idk if this was initially a specific issue with 4k monitors or not... it definitely wasn't my first thought..

Thank you for letting myself & others know about this!

**Comment by taeyeop-lee** [comment]
@ECE-Engineer @ernlavr @sepigraph 
I have the same problem with the 4K monitor and I wonder how to solve the problem.
If I make the GUI small shared by @ernlavr, it's a little visible, but it's still not as good as I thought it would be.
Does your problem solved by @ernlavr solution or changing the resolution or a monitor??
