### ISSUE TITLE
No module named "imageio"

### ISSUE THREAD

**Issue by WaltReu** [NVlabs/instant-ngp#281]
![image](https://user-images.githubusercontent.com/85451729/155941448-336b4e29-4213-4b8c-abe1-16121c5dda98.png)

I get this when trying to use the convert-image script. Am I doing something wrong here?

**Comment by Tom94** [comment]
You need to install the required Python packages, which include imageio.

```sh
pip install -r requirements.txt
```

Cheers!

**Comment by WaltReu** [comment]
> 

Thank you! I'm impressed how quickly I get help here.

**Comment by SimonCL17** [comment]
Hi there, when I run "pip install -r requirements.txt", I get the following

![image](https://user-images.githubusercontent.com/56849085/175362040-b52e059b-bcd2-417b-a5bf-2efc4f681397.png)


Any suggestions?
