### ISSUE TITLE
Bugs: batch_cam.json related

### ISSUE THREAD

**Issue by Kreevoz** [NVlabs/instant-ngp#30]
**Bug 1)** When a `batch_cam.json` was saved out from Testbed and is present in the dataset root dir, attempting to initialize testbed with the `--scene data/nerf/etc` argument will lead to:
`ERROR    Uncaught exception: [json.exception.type_error.302] type must be number, but is null`

because the` batch_cam.json` is incorrectly parsed in place of the `transforms.json` file.

**Workaround:** Move that camera path file into another location outside of the main dataset directory.

**Bug 2)** When Testbed is instructed to load a `batch_cam.json` file when none exists, it crashes:
`ERROR    Uncaught exception: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal`

**Workaround:** Ensure the file exists in the specified path before attempting to load it.

**Comment by mmalex** [comment]
thanks for the detailed report! I'll look into (and most likely fix) these
issues tomorrow and report back here.
appreciate it.
