### ISSUE TITLE
cmake build fails

### ISSUE THREAD

**Issue by msollami-sf** [NVlabs/instant-ngp#304]
I followed the setup instructions but this command `$ cmake --build build --config RelWithDebInfo -j 16` fails with
```...
[ 98%] Linking CXX executable testbed
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
CMakeFiles/testbed.dir/build.make:115: recipe for target 'testbed' failed
make[2]: *** [testbed] Error 1
```

This was run on a fresh P3 instance 
AMI:amazon/Deep Learning AMI (Ubuntu 18.04) Version 56.1.  
NVIDIA-SMI 450.142.00   
CUDA Version: 11.0

Which libGL is required to install?

**Comment by msollami-sf** [comment]
This fixed it: `sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev`

**Comment by klae01** [comment]
I ran into the same problem. But it is not enough to solve.
workaround:  https://stackoverflow.com/a/45573185
```
sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev libgl1 -y
sudo ln -s /usr/lib/x86_64-linux-gnu/libGL.so.1 /usr/lib/x86_64-linux-gnu/libGL.so
```
with cuda11.4, driver `470.103.01`, commit `0dd18e2`, cmake `3.22.4`
