### ISSUE TITLE
Q: Batch render frames along the spline path?

### ISSUE THREAD

**Issue by Kreevoz** [NVlabs/instant-ngp#31]
The Testbed can make camera splines, but those splines are not a valid data type outside of it - the run.py script won't parse them. It expects a json of fixed transforms for the screenshot_transforms argument.

- Is there a way to instruct testbed to parse the camera path and save out a desired number of nerf-style transforms that may be used for the screenshot function?
- Is there a way to instruct testbed to save out a controllable number of screenshots along the path from within the GUI (but with the UI hidden), taking as much time as it needs to render a frame?

I'd love to generate lovely smooth high quality movies like you did for your presentation 😵

**Comment by Tom94** [comment]
The Python bindings allow this. Here's a relevant excerpt from our internal scripts. (We're working on pushing more of them public in the future.)

```
def render_video(resolution, numframes, spp, fps, exposure=0):
	for i in tqdm(list(range(min(numframes, last_frame+1))), unit="frames", desc=f"Rendering"):
		testbed.camera_smoothing = i > 0
		frame = testbed.render(resolution[0], resolution[1], spp, True, float(i)/numframes, float(i + 1)/numframes, fps, shutter_fraction=0.5)
		write_image(f"{outpath}/{i:04d}.jpg", np.clip(frame * 2**exposure, 0.0, 1.0), quality=100)

testbed.load_camera_path(<path to camera_path.json>)

n_seconds = 5
fps = 60
render_video([1920, 1080], int(n_seconds/fps), spp=8, fps=fps)
```
