### ISSUE TITLE
system of windows10, the problem of cmake

### ISSUE THREAD

**Issue by yangrui12321** [NVlabs/instant-ngp#310]
**I really appreciate this great project! I got the following error when compiling instant-ngp on winndows10, where is the possible problem? thank you very much!** 
F:\Tutorial\ngp\instant-ngp>cmake . -B build
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
CMake Error at CMakeLists.txt:111 (add_subdirectory):
  The source directory

    F:/Tutorial/ngp/instant-ngp/dependencies/glfw

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:113 (set_target_properties):
  set_target_properties Can not find target to add properties to: glfw

-- OptiX_INSTALL_DIR value: C:\ProgramData\NVIDIA Corporation\OptiX SDK 7.4.0
CMake Error at CMakeLists.txt:189 (add_subdirectory):
  The source directory

    F:/Tutorial/ngp/instant-ngp/dependencies/pybind11

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:197 (add_subdirectory):
  The source directory

    F:/Tutorial/ngp/instant-ngp/dependencies/tiny-cuda-nn

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:301 (pybind11_extension):
  Unknown CMake command "pybind11_extension".

-- Configuring incomplete, errors occurred!
See also "F:/Tutorial/ngp/instant-ngp/build/CMakeFiles/CMakeOutput.log".

**Comment by Tom94** [comment]
It seems that you do not have submodules cloned. You can remedy this by re-cloning using the `--recursive` flag, or executing the following in your root directory:
```sh
git submodule init
git submodule update --recursive
```
