### ISSUE TITLE
Error during cmake build.

### ISSUE THREAD

**Issue by tym0027** [NVlabs/instant-ngp#324]
Hey,

I am following the install instructions. The cmake . -B build doesn't give any errors and completes. Then I get to:
cmake --build build --config RelWithDebInfo -j 16

I get the following error:

[ 98%] Linking CXX executable testbed
/usr/bin/ld: cannot find -lcublas
collect2: error: ld returned 1 exit status
CMakeFiles/testbed.dir/build.make:115: recipe for target 'testbed' failed

make[2]: *** [testbed] Error 1
CMakeFiles/Makefile2:227: recipe for target 'CMakeFiles/testbed.dir/all' failed
make[1]: *** [CMakeFiles/testbed.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX shared library pyngp.cpython-39-x86_64-linux-gnu.so
/usr/bin/ld: cannot find -lcublas
collect2: error: ld returned 1 exit status
CMakeFiles/pyngp.dir/build.make:115: recipe for target 'pyngp.cpython-39-x86_64-linux-gnu.so' failed
make[2]: *** [pyngp.cpython-39-x86_64-linux-gnu.so] Error 1
CMakeFiles/Makefile2:172: recipe for target 'CMakeFiles/pyngp.dir/all' failed
make[1]: *** [CMakeFiles/pyngp.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

Any ideas what the cause of this is?

**Comment by kajc10** [comment]
I think my issue #347 was the same.
Try @leventt 's suggestion:
```
export CUDA_HOME=/usr/local/cuda
export PATH="/usr/local/cuda/bin:$PATH"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64"
export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/cuda/lib64"
```

**Comment by HassanNawazish1** [comment]
> 

Not able to resolve this issue by using these export commands.
