### ISSUE TITLE
optimize extrinsics now broken?

### ISSUE THREAD

**Issue by pwais** [NVlabs/instant-ngp#348]
I seem to get this now thru the GUI or python API:
```
02:50:39 ERROR    Uncaught exception: Could not copy to host: /opt/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:292 cudaMemcpy(host_data, data(), num_elements * sizeof(T), cudaMemcpyDeviceToHost) failed with error an illegal memory access was encountered
```

**Comment by pwais** [comment]
previous commit 7b37eee0aa9ea31362d2a5a799e007a731de385c seems to work

**Comment by sherwoac** [comment]
same issue, full output:
`(instant_ngp_env) adam@z10:~/CODE_z10/instant_ngp_test$ vglrun ./build/testbed --scene ~/CODE_z10/WOE_DATA/kadyrov1_masked_unblurred.json
[VGL] NOTICE: Automatically setting VGL_CLIENT environment variable to
[VGL]    192.168.0.29, the IP address of your SSH client.
10:03:45 INFO     Loading NeRF dataset from
10:03:45 INFO       /home/adam/CODE_z10/WOE_DATA/kadyrov1_masked_unblurred.json
10:03:45 SUCCESS  Loaded 1302 images of size 480x256 after 0s
10:03:45 INFO       cam_aabb=[min=[0.519464,-0.194703,0.244347], max=[3.18889,0.29037,0.758979]]
10:03:45 INFO     Loading network config from: configs/nerf/base.json
10:03:45 INFO     GridEncoding:  Nmin=16 b=1.66248 F=2 T=2^19 L=16
10:03:45 INFO     Density model: 3--[HashGrid]-->32--[FullyFusedMLP(neurons=64,layers=3)]-->1
10:03:45 INFO     Color model:   3--[Composite]-->16+16--[FullyFusedMLP(neurons=64,layers=4)]-->3
10:03:45 INFO       total_encoding_params=13623184 total_network_params=10240
10:03:53 INFO     Loading network config from: configs/nerf/base.json
10:03:53 INFO     GridEncoding:  Nmin=16 b=1.66248 F=2 T=2^19 L=16
10:03:53 INFO     Density model: 3--[HashGrid]-->32--[FullyFusedMLP(neurons=64,layers=3)]-->1
10:03:53 INFO     Color model:   3--[Composite]-->16+16--[FullyFusedMLP(neurons=64,layers=4)]-->3
10:03:53 INFO       total_encoding_params=13623184 total_network_params=10240
10:03:59 INFO     Loading network config from: configs/nerf/base.json
10:03:59 INFO     GridEncoding:  Nmin=16 b=1.66248 F=2 T=2^19 L=16
10:03:59 INFO     Density model: 3--[HashGrid]-->32--[FullyFusedMLP(neurons=64,layers=3)]-->1
10:03:59 INFO     Color model:   3--[Composite]-->16+16--[FullyFusedMLP(neurons=64,layers=4)]-->3
10:03:59 INFO       total_encoding_params=13623184 total_network_params=10240
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:458 cudaDeviceSynchronize() failed with error an illegal memory access was encountered
/home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/src/fully_fused_mlp.cu:691 cudaEventDestroy(m_training_splitk_events[i]) failed with error an illegal memory access was encountered
/home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/src/fully_fused_mlp.cu:692 cudaStreamDestroy(m_training_splitk_streams[i]) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:458 cudaDeviceSynchronize() failed with error an illegal memory access was encountered
/home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/src/fully_fused_mlp.cu:691 cudaEventDestroy(m_training_splitk_events[i]) failed with error an illegal memory access was encountered
/home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/src/fully_fused_mlp.cu:692 cudaStreamDestroy(m_training_splitk_streams[i]) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:458 cudaDeviceSynchronize() failed with error an illegal memory access was encountered
/home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/src/fully_fused_mlp.cu:691 cudaEventDestroy(m_training_splitk_events[i]) failed with error an illegal memory access was encountered
/home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/src/fully_fused_mlp.cu:692 cudaStreamDestroy(m_training_splitk_streams[i]) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:458 cudaDeviceSynchronize() failed with error an illegal memory access was encountered
/home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/src/fully_fused_mlp.cu:691 cudaEventDestroy(m_training_splitk_events[i]) failed with error an illegal memory access was encountered
/home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/src/fully_fused_mlp.cu:692 cudaStreamDestroy(m_training_splitk_streams[i]) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:458 cudaDeviceSynchronize() failed with error an illegal memory access was encountered
/home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/src/fully_fused_mlp.cu:691 cudaEventDestroy(m_training_splitk_events[i]) failed with error an illegal memory access was encountered
/home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/src/fully_fused_mlp.cu:692 cudaStreamDestroy(m_training_splitk_streams[i]) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered
10:04:02 ERROR    Uncaught exception: Could not copy to host: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:292 cudaMemcpy(host_data, data(), num_elements * sizeof(T), cudaMemcpyDeviceToHost) failed with error an illegal memory access was encountered
Could not free memory: /home/adam/CODE_z10/instant_ngp_test/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:458 cudaDeviceSynchronize() failed with error an illegal memory access was encountered
(instant_ngp_env) adam@z10:~/CODE_z10/instant_ngp_test$ 
`

**Comment by Tom94** [comment]
Should be fixed by the latest commit https://github.com/NVlabs/instant-ngp/commit/2f12e1e613287b444f652892dbd23435614db642

Apologies for this regression!

**Comment by sherwoac** [comment]
works

**Comment by pwais** [comment]
thank you @Tom94 !!! smashing residuals left and right 🔨🔨🔨 and some bugs too
