### ISSUE TITLE
Optix call 'optixInit()' failed

### ISSUE THREAD

**Issue by phelps-matthew** [NVlabs/instant-ngp#35]
It appears that I am able to build the source successfully, but upon running ./build/testbed --scene data/nerf/fox I receive: Uncaught exception: Optix call 'optixInit()' failed.

Do you know of any manners by which I can test/debug the working condition of Optix itself? I am having some difficulty finding this information online. Much appreciated, thank you! 

( Running Tesla V100, export OptiX_INSTALL_DIR=/usr/local/NVIDIA-OptiX-SDK-7.4.0-linux64-x86_64 )

**Comment by phelps-matthew** [comment]
I believe this arises from the driver compatibility for OptiX. From https://developer.nvidia.com/designworks/optix/download it is stated: 'Requires NVIDIA R495.89 driver or newer'.

Hence, for TCNN_CUDA_ARCHITECTURES <= 70, I am going to assume that one needs to run ngp in headless mode, via scripts/run.py (no gui default).

**Comment by phelps-matthew** [comment]
Using OptiX-SDK-7.1.0 (compatible for R450+ NVIDIA drivers) solved my issue. Cheers!

**Comment by Tom94** [comment]
Glad to hear you fixed it!

This is still great to know -- OptiX shouldn't even _be_ initialized as long as `Testbed` isn't run in `SDF` mode. Plus, a failure to initialize should just fall back to non-OptiX behavior (rather than crashing). I'll take this issue as motivation to fix these things.
