### ISSUE TITLE
Build error on Ubuntu: too few arguments in function call

### ISSUE THREAD

**Issue by tlok666** [NVlabs/instant-ngp#37]
![ssss](https://user-images.githubusercontent.com/12291907/149859542-ba09fa9d-5422-44fd-aa46-88b0c3b8f298.png)
Ubuntu18.04.6
GTX3080
CUDA 11.5
What should I fix? Is this a Cuda version error?

**Comment by somisawa** [comment]
What were the cmake and build command? In my case, the build failed when the environmental variables were not correctly set in cmake and build command.

**Comment by somisawa** [comment]
And also, you had better to check whether any warnings appear in cmake command. In my case, it totally worked well by solving all warnings.

**Comment by Tom94** [comment]
This looks like one of the submodules (`glfw` to be precise) is not tracking the right commit.
```sh
git submodule sync --recursive
git submodule update --init --recursive
```
should do the trick.

Please feel free to re-open this issue if the problem persists.
