### ISSUE TITLE
`-fPIC` needs to be `-Xcompiler=-fPIC` for nvcc version 11.4

### ISSUE THREAD

**Issue by amonszpart** [NVlabs/instant-ngp#380]
Based on this: https://bugs.gentoo.org/715610#c0

I think this line:
https://github.com/NVlabs/instant-ngp/blob/8625c253ed26f10d8a071f928da48ecad08b472d/CMakeLists.txt#L81

needs to say
```cmake
	list(APPEND CUDA_NVCC_FLAGS "-Xcompiler=-fPIC")
```

**Comment by Tom94** [comment]
That's interesting -- thanks for pointing this out! I'll let CI run through this and will merge the change if it looks to degrade nothing.
