### ISSUE TITLE
compiling error:no instance of overloaded function

### ISSUE THREAD

**Issue by yaohusama** [NVlabs/instant-ngp#415]
_D:\intern\kanjing\instant-ngp-misc-improvements\src\testbed_volume.cu(209): error : no instance of overloaded function
"tcnn::Trainer<T, PARAMS_T, COMPUTE_T>::training_step [with T=float, PARAMS_T=ngp::precision_t, COMPUTE_T=ngp::precisio
n_t]" matches the argument list [D:\intern\kanjing\instant-ngp-misc-improvements\build\ngp.vcxproj]
 argument types are: (cudaStream_t, tcnn::GPUMatrix<float, tcnn::MatrixLayout::ColumnMajor>, tcnn::GPUMatr
  ix<float, tcnn::MatrixLayout::ColumnMajor>, float *)object type is: tcnn::Trainer<float, ngp::precision_t, ngp::precision_t>_
When I run this command:cmake --build build --config RelWithDebInfo -j 16,the error occured.So I wonder whether the code right or not  and how can I solve this problem?
And there were other errors.For example,following one is as follows:
`D:\intern\kanjing\instant-ngp-misc-improvements\include\neural-graphics-primitives/trainable_buffer.cuh(40): error : me
mber function declared with "override" does not override a base class member [D:\intern\kanjing\instant-ngp-misc-improv
ements\build\ngp.vcxproj]
            detected during instantiation of class "ngp::TrainableBuffer<N_DIMS, RANK, T> [with N_DIMS=4U, RANK=2U, T=f
  loat]"
  D:\intern\kanjing\instant-ngp-misc-improvements\src\testbed_volume.cu(439): here`

**Comment by Tom94** [comment]
This sounds like the __tiny-cuda-nn__ submodule being out of sync. Did you by any chance pull without also updating submodules?
```sh
git submodule sync --recursive
git submodule update --recursive
```

Cheers!

**Comment by yaohusama** [comment]
@Tom94 I think you're right. I download the submodules manually because the network signal is bad. After the submodules are synchronized, the problem is solved. Thanks a lot.
