### ISSUE TITLE
Error while running colmap2nerf.py

### ISSUE THREAD

**Issue by MIMNSI** [NVlabs/instant-ngp#419]
I encountered this error at the Feature extraction stage.

----------------------------------------------------------------
F20220402 11:31:06.884990 22536 sift.cc:656] Check failed: octave_scale_idx <= prev_octave_scale_idx (-1689112243 vs. -1873862397)
*** Check failure stack trace: ***
    @     0x7fbd4207fc0d  google::LogMessage::Fail()
    @     0x7fbd420827a6  google::LogMessage::SendToLog()
    @     0x7fbd4207f705  google::LogMessage::Flush()
    @     0x7fbd42082d6a  google::LogMessageFatal::~LogMessageFatal()
    @     0x55b9adab03c9  colmap::ExtractCovariantSiftFeaturesCPU()
    @     0x55b9ada8a4dc  colmap::internal::SiftFeatureExtractorThread::Run()
    @     0x55b9adc2602e  colmap::Thread::RunFunc()
    @     0x7fbd4021f039  execute_native_thread_routine
    @     0x7fbd41c99609  start_thread
    @     0x7fbd3fef3163  clone
Aborted (core dumped)
FATAL: command failed
----------------------------------------------------------------

I searched on the web about this error but couldn't find anything.

**Comment by Tom94** [comment]
To troubleshoot this, I recommend printing the precise command line parameters that are passed to COLMAP and then asking for help on their GitHub repository. Cheers!

**Comment by MIMNSI** [comment]
Alright I'll do that. Thanks!

**Comment by epicgzs1112** [comment]
@MIMNSI how to  fix it ,bro  ! 
--video_in
data/video/VID_20230506_191635.mp4
--video_fps
1
--run_colmap
--out
transforms.json
--colmap_matcher
exhaustive
--aabb_scale
32
