### ISSUE TITLE
Google Colab Mesh Output

### ISSUE THREAD

**Issue by aceIsHere** [NVlabs/instant-ngp#427]
What will be the equivalent like for google colab for this notebook (https://colab.research.google.com/drive/10TgQ4gyVejlHiinrmm5XOvQQmgVziK3i?usp=sharing)

Basically after last line I want to export/save my file as a .obj or .ply format so that I can download and try it on my local blender environment

I tried to iterate your line for colab but it was not successful. I hope you can help me here. Thanks!

**Comment by Vertecedoc4545** [comment]
@aceIsHere create a folder called saved
`%mkdir instant-ngp/saved`
before running the command and works
then convert the fox.ply an the folder saved to obj i duno if can be saved directly to obj
consider taking the basics on linux command line

**Comment by aceIsHere** [comment]
Thanks a lot, my blunder -beginner but not that much ;0
👍 💯 
Here was the previous discussion thinking it was some disk usage limit 
https://github.com/NVlabs/instant-ngp/discussions/412
