### ISSUE TITLE
Stuck during Cmake build 

### ISSUE THREAD

**Issue by faizkhan12** [NVlabs/instant-ngp#433]
cmake . -B build command is working fine and giving me a build folder. but when I run cmake --build build --config RelWithDebInfo -j 16, it's getting stuck at 89% and my whole system hangs. Is this problem persist because of low memory? I have 16 GB RAM

**Comment by nmlt** [comment]
I'm having the same problem. Not even SysRq is still working. So the compilation is somehow crashing the Linux kernel. I'm on Arch Linux.

I just looked at journalctl while compiling and got this output ~5 seconds before the hang:
```
gnome-shell[1046]: clutter_actor_set_allocation_internal: asser
tion '!isnan (box->x1) && !isnan (box->x2) && !isnan (box->y1) && !isnan (box->y2)" failed
gnome-shell[1046]:
../mutter/clutter/clutter/clutter-actor.c:92
41: Actor
" <unnamed› [<StDrawingArea>:0x55b55cf2b030]* tried to allocate a size of -21474
83648.00 x
-
gnome-shell[1046]:
./mutter/clutter/clutter/clutter-actor.c:92
41: Actor
" <unnamed> [<StBin>: 0x55b5598927d0] •
tried to allocate a size of -2147483648.00
X
-2147483648.00
```
(Copied log via OCR)

But it probably has nothing to do with the hang, as I've also tried to compile it without a desktop environment and experienced the same hang.

**Comment by faizkhan12** [comment]
of course, basically compiling in low ram memory.... mine now working ...@nmlt please note

**Comment by dframirez-usmc** [comment]
My situation was similar, 
`cmake --build build --config RelWithDebInfo -j 16`
stuck at 89%
> [ 89%] Building CXX object CMakeFiles/ngp.dir/src/tinyobj_loader_wrapper.cpp.o
> Killed
> make[2]: *** [CMakeFiles/ngp.dir/build.make:202: CMakeFiles/ngp.dir/src/common_device.cu.o] Error 137
> make[2]: *** Waiting for unfinished jobs....
> ...
Ubuntu 20.04 system is still responsive after failure though. 

**Fix stated above worked for me:**
`cmake --build build --config RelWithDebInfo -j 4`
