### ISSUE TITLE
Get transforms from ARkit data

### ISSUE THREAD

**Issue by Vadkoz** [NVlabs/instant-ngp#439]
Hi,
I have extrinsic data (quaternions and translation) from ARkit. But if simply pass my quaternions instead COLMAP's, the result is clearly wrong. How do I need to preprocess ARkit data to make it similar to COLMAP before passing it to colmap2nerf script? Or what transformation i need to do instead of preprocessing and colmap2nerf?
I use ios_logger from [this](https://github.com/Varvrar/ios_logger) repo to get ARkit data.
Thanks!

**Comment by dodatko** [comment]
same question
