### ISSUE TITLE
Could not register, trying another image

### ISSUE THREAD

**Issue by henrikmyl** [NVlabs/instant-ngp#444]
What causes this error message?? This comes when i try to use my own images. 

![error message](https://user-images.githubusercontent.com/40103915/162005067-8e5d27d7-dd46-40d6-8ae6-e271fd2f17b2.png)

**Comment by henrikmyl** [comment]
I think this is more COLMAP issue.... My images was too big (5472x3648) and all those images are taken by automatic turntable (360°) system. I have to try a more simpler solution.

**Comment by mgupta70** [comment]
Hey @henrikmyl, Did you find a way to register your 360 photos?
