### ISSUE TITLE
Some doubts about updating density grid in NeRF

### ISSUE THREAD

**Issue by lzhnb** [NVlabs/instant-ngp#459]
Thanks for your amazing project!

For the nerf training, using the density grid is essential to skip the empty area and promote efficiency.
After scanning the project, I have some doubts about the procedure of updating density grid.

- First, there are several important variables: `density_grid`, `density_grid_bitfield` and `mip`
The size of `density_grid` is **[128, 128, 128]**
The size of `density_grid_bitfield` is **[128 * 128 * 80]** (**1310720** as **128 * 128 * 128 * NERF_CASCADES() / 8**)
`density_grid` stores the predicted densities(sigmas) of the given grid centers with noise. But in the rendering, `density_grid_bitfield` is used to skip points, not `density_grid`. It seems to store the 8-bit mask, but the size of `density_grid_bitfield` is less than the number of grids, how to realize the grid-wise judgments? And what is the meaning of `8` in this part?
Also, what is the meaning of the `mip`? It looks different from the `mip` in `mip-NeRF`.
- Second, [grid_to_bitfield](https://github.com/NVlabs/instant-ngp/blob/0e63027a14a0d49bb7c5e10414deeda9c7b707f9/src/testbed_nerf.cu#L2457) and [bitfield_max_pool](https://github.com/NVlabs/instant-ngp/blob/0e63027a14a0d49bb7c5e10414deeda9c7b707f9/src/testbed_nerf.cu#L2460) functions in [Testbed::update_density_grid_mean_and_bitfield](https://github.com/NVlabs/instant-ngp/blob/0e63027a14a0d49bb7c5e10414deeda9c7b707f9/src/testbed_nerf.cu#L2447) confuse me. In my opinion, the aim is to generate the mask of grid to realize skipping the empty points. Why not directly mask the `density_grid` via thresh?

**Is there any technical report or reference? If so, I will be glad to read it :)**

> I am not familiar with some concepts in graphics and would like your help!

Thanks! :)

**Comment by lzhnb** [comment]
I have learned about some of the concepts in graphics.
The morton code is important in this part. So the `8` means the node in each octree, right?
The `density_grid` stores the predicted densities(sigmas) of the given grid centers with noise. And the `density_grid_bitfield` stores the node masks of each octree in z-order.

In `generate_training_samples_nerf`, the `density_grid_bitfield` is used to skip the empty point via querying the node masks of each octree, right?

But I have new questions now?
- Why not directly generate the mask of `density_grid` via `density_threshold` to realize skipping the empty points?
- For some datasets, like **lego**, the `max_cascade` is zero(with small aabb), but it also construct a **5-level** mip density, what is the correspondence between the `max_cascade` and `level / NERF_CASCADES()`.
- The [bitfield_max_pool](https://github.com/NVlabs/instant-ngp/blob/0e63027a14a0d49bb7c5e10414deeda9c7b707f9/src/testbed_nerf.cu#L2460) still confuses me. It looks like to construct a hierarchical octree, which means the low-level octrees will be the leaf nodes of the high-level octree. But the high-level octree looks as big as the low-level octrees, because the `n_elements` for each loop is not changed.

Thanks! :)

**Comment by Tom94** [comment]
Hi there, while the semantics of the cascade of bitfields are the same as those of an octree, I'd caution against calling it a "tree". These grids are all dense and can be directly addressed with traversing a hierarchy.

As for your questions:
1. Two reasons. (i) it's more expensive/memory incoherent to load full-precision density values on the fly. Much less memory bandwidth is required to march through bitfields (32x at the finest level, and even more at coarser levels). (ii) building a multi-resolution cascade allows taking larger steps through the bitfield if the NeRF stepping size is correspondingly larger.
2. `NERF_CASCADES()` is a compile-time constant that determines the maximum supported number of cascades. `max_cascade` is the highest cascade that's actually used in the current dataset and has to be smaller than `NERF_CASCADES()`. The distinction between the two arises from some calculations being cheaper/easier when done with compile-time values -- even if this results in slightly higher memory usage. With a little bit of implementation effort, one could probably get rid of `NERF_CASCADES()` and do everything at runtime.
3. Here's where it's important to not treat the cascade of grids as a tree. Each cascade represents a 2x coarser representation of the scene -- so far the correspondence -- but as you noticed, the coarser representations have same number of entries and thus cover twice the size as well. These coarser cascades simply reach further from the center of the scene, providing a coarser, but still usable occupancy lookup in larger scenes.

Cheers!
