### ISSUE TITLE
CMAKE_CUDA_ARCHITECTURES must be valid if set

### ISSUE THREAD

**Issue by Nasa1423** [NVlabs/instant-ngp#465]
H:\instant-ngp>cmake . -B build
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
CMake Error at C:/Program Files/CMake/share/cmake-3.23/Modules/CMakeDetermineCUDACompiler.cmake:311 (message):
  CMAKE_CUDA_ARCHITECTURES must be valid if set.
Call Stack (most recent call first):
  CMakeLists.txt:11 (PROJECT)

-- Configuring incomplete, errors occurred!
See also "H:/instant-ngp/build/CMakeFiles/CMakeOutput.log".
See also "H:/instant-ngp/build/CMakeFiles/CMakeError.log".

**Comment by Freeman015** [comment]
Hi Nasa1423,
The issue occurs for me with multiple GPU's (Laptop).

Try the following as mentioned on the Readme:
"
<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">If automatic GPU architecture detection fails, (as can happen if you have multiple GPUs installed), set the<span> </span><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;">TCNN_CUDA_ARCHITECTURES</code><span> </span>enivonment variable for the GPU you would like to use. The following table lists the values for common GPUs. If your GPU is not listed, consult<span> </span><a href="https://developer.nvidia.com/cuda-gpus" rel="nofollow" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">this exhaustive list</a>.</p>

RTX 30X0 | A100 | RTX 20X0 | TITAN V / V100 | GTX 10X0 / TITAN Xp | GTX 9X0 | K80
-- | -- | -- | -- | -- | -- | --
86 | 80 | 75 | 70 | 61 | 52 | 37


</body>
</html>
"

I am still trying to fix it however (new to CMake) 

Hope this helps you out.

**Comment by dreadlokon** [comment]
have the same problem

**Comment by espackman** [comment]
If it is helpful, I was stuck on the same issue. I tried deleting the build folder within instant-ngp, and then re-running `cmake . -B build`. For some reason, this worked.

**Comment by Nasa1423** [comment]
@espackman Thanks a lot! That one worked perfectly.
