### ISSUE TITLE
Uncaught exception - Memory Allocation

### ISSUE THREAD

**Issue by nopor** [NVlabs/instant-ngp#488]
[Copied from https://github.com/NVlabs/tiny-cuda-nn/issues/82]
Error:
`ERROR Uncaught exception: Could not allocate memory: ~/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:112 cudaMalloc(&rawptr, n_bytes+DEBUG_GUARD_SIZE*2) failed with error out of memory`

Description/how to reproduce:
When adjusting the marching cubes mesh output (in https://github.com/NVlabs/instant-ngp), all resolutions roughly above 768^3 fail with the exception stated above.
This happens regardless of the scene/used data.

(Not sure if tiny-cuda-nn is used correctly, thus reporting it in this repo as well)

**Comment by Tom94** [comment]
As the error says: you're running out of memory. In order to export larger resolutions, you need to either free up GPU RAM elsewhere or obtain a GPU with more RAM (short of optimizing the algorithm). Cheers!
