### ISSUE TITLE
How to export the 3D scene as ply or obj file for further usage.

### ISSUE THREAD

**Issue by endlesswho** [NVlabs/instant-ngp#49]

**Comment by mmalex** [comment]
hi! you can export to OBJ via the GUI at the moment, there is a demonstration how to do it at 1:14 in this video https://nvlabs.github.io/instant-ngp/assets/mueller2022instant.mp4
I will be adding a python binding & vertex colors support today. stretch goal to support PLY too. I will update this issue with details when it is done.

**Comment by mmalex** [comment]
note that the 3d export respects the 'render crop aabb' which is also configurable from the GUI, so you can select which portion of the scene to mesh & export.

**Comment by endlesswho** [comment]
> 

That could be wondful! 
I found the save_mesh function in marching_cubes.cu, I'm running on a headless server, so I'd prefer saving the results to devices for further usage.

**Comment by mmalex** [comment]
ok this work is done but we will merge it tomorrow! PLY and OBJ supported, as well as returning the mesh vertices, colors and triangle indices as numpy arrays to python. thanks for your patience.

**Comment by endlesswho** [comment]
> we will merge it tomorrow! PLY and OBJ supported, as well as returning the mesh vertices, colors and triangle indices as numpy arrays to python. tha

Unlike the rendered result from the network, the exported results seems a little bit mess in PLY or OBJ. This is caused by triangulate step?
![fox](https://user-images.githubusercontent.com/8555404/150287456-4b029b22-c4f0-4fcd-ac54-5c58a246f3b4.png)

**Comment by feiyilicare** [comment]
i have same results,not as network output

**Comment by endlesswho** [comment]
> I have same results, how did you fix?

A larger resolution could solve. But I recommand a sdf nerf reconstruction for better visualization.

**Comment by andreac** [comment]
> > I have same results, how did you fix?
> 
> A larger resolution could solve. But I recommand a sdf nerf reconstruction for better visualization.

Ok for resolution, but how can i export sdf (and convert to ply or others) without using GUI?

**Comment by endlesswho** [comment]
> > > I have same results, how did you fix?
> > 
> > 
> > A larger resolution could solve. But I recommand a sdf nerf reconstruction for better visualization.
> 
> Ok for resolution, but how can i export sdf (and convert to ply or others) without using GUI?

The project is for fast nerf training for novel view synthesis. In my opinion, this only support little customization due to many dependencies. For better reconstruction, you can try sdf-nerf such as NeuS.

**Comment by ishandutta04** [comment]
How do we save mesh with the vertex colors?

**Comment by alter-sachin** [comment]
NUDGE
