### ISSUE TITLE
Build fail on Windows 10

### ISSUE THREAD

**Issue by StarsTesla** [NVlabs/instant-ngp#495]
**Here is the log after run：**cmake . -B build

-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
-- The C compiler identification is MSVC 19.29.30140.0
-- The CXX compiler identification is MSVC 19.29.30140.0
-- The CUDA compiler identification is NVIDIA 11.6.124
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.6/bin/nvcc.exe - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
CMake Deprecation Warning at dependencies/glfw/CMakeLists.txt:5 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at dependencies/glfw/CMakeLists.txt:10 (cmake_policy):
  The OLD behavior for policy CMP0042 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Using Win32 for window creation
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- OptiX_INSTALL_DIR value: C:\ProgramData\NVIDIA Corporation\OptiX SDK 7.4.0
-- Found Python: C:/ProgramData/Anaconda3/python.exe (found suitable version "3.9.7", minimum required is "3.7") found components: Interpreter Development Development.Module Development.Embed
-- pybind11 v2.8.0 dev1
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.22/Modules/CMakeDependentOption.cmake:84 (message):
  Policy CMP0127 is not set: cmake_dependent_option() supports full Condition
  Syntax.  Run "cmake --help-policy CMP0127" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
Call Stack (most recent call first):
  dependencies/pybind11/CMakeLists.txt:98 (cmake_dependent_option)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test HAS_MSVC_GL_LTCG
-- Performing Test HAS_MSVC_GL_LTCG - Success
-- Targeting GPU architectures: 86
-- Configuring done
-- Generating done
-- Build files have been written to: B:/git/instant-ngp/build

Seems fine.

**Here is the log after run:** cmake --build build --config RelWithDebInfo -j 16
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
版权所有(C) Microsoft Corporation。保留所有权利。

  Checking Build System
  Building Custom Rule B:/git/instant-ngp/dependencies/glfw/src/CMakeLists.txt
  Building Custom Rule B:/git/instant-ngp/CMakeLists.txt
  context.c
  init.c
  input.c
  monitor.c
  vulkan.c
  window.c
  Compiling CUDA source file ..\src\optix\raystab.cu...
  Compiling CUDA source file ..\src\optix\pathescape.cu...
  Compiling CUDA source file ..\src\optix\raytrace.cu...
  win32_init.c

  B:\git\instant-ngp\build>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute
  _52\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu
   -I"B:\git\instant-ngp\dependencies" -I"B:\git\instant-ngp\dependencies\eigen" -I"B:\git\instant-ngp\dependencies\filesystem" -I"B:\git\instan
  t-ngp\dependencies\glfw\include" -I"B:\git\instant-ngp\dependencies\imgui" -I"B:\git\instant-ngp\dependencies\gl3w" -I"B:\git\instant-ngp\depe
  ndencies\nanovdb" -I"C:\ProgramData\NVIDIA Corporation\OptiX SDK 7.4.0\include" -I"B:\git\instant-ngp\dependencies\tiny-cuda-nn\include" -I"B:
  \git\instant-ngp\dependencies\tiny-cuda-nn\dependencies" -I"B:\git\instant-ngp\dependencies\tinylogger" -I"B:\git\instant-ngp\include" -I"B:\g
  it\instant-ngp\build" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include"     --keep-dir x64\RelWithDebInfo  -maxrregcount=0
   --machine 64 -ptx -cudart static --expt-relaxed-constexpr -std=c++14 -Xcompiler="/EHsc -Zi -Ob1" -D_WINDOWS -DNDEBUG -DNGP_GUI -DNGP_OPTIX -D
  "NGP_VERSION=\"1.0dev\"" -DTCNN_MIN_GPU_ARCH=0 -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -D_MBCS -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -o optix_progra
  m.dir\RelWithDebInfo\pathescape.ptx "B:\git\instant-ngp\src\optix\pathescape.cu"

  B:\git\instant-ngp\build>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute
  _52\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu
   -I"B:\git\instant-ngp\dependencies" -I"B:\git\instant-ngp\dependencies\eigen" -I"B:\git\instant-ngp\dependencies\filesystem" -I"B:\git\instan
  t-ngp\dependencies\glfw\include" -I"B:\git\instant-ngp\dependencies\imgui" -I"B:\git\instant-ngp\dependencies\gl3w" -I"B:\git\instant-ngp\depe
  ndencies\nanovdb" -I"C:\ProgramData\NVIDIA Corporation\OptiX SDK 7.4.0\include" -I"B:\git\instant-ngp\dependencies\tiny-cuda-nn\include" -I"B:
  \git\instant-ngp\dependencies\tiny-cuda-nn\dependencies" -I"B:\git\instant-ngp\dependencies\tinylogger" -I"B:\git\instant-ngp\include" -I"B:\g
  it\instant-ngp\build" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include"     --keep-dir x64\RelWithDebInfo  -maxrregcount=0
   --machine 64 -ptx -cudart static --expt-relaxed-constexpr -std=c++14 -Xcompiler="/EHsc -Zi -Ob1" -D_WINDOWS -DNDEBUG -DNGP_GUI -DNGP_OPTIX -D
  "NGP_VERSION=\"1.0dev\"" -DTCNN_MIN_GPU_ARCH=0 -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -D_MBCS -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -o optix_progra
  m.dir\RelWithDebInfo\raystab.ptx "B:\git\instant-ngp\src\optix\raystab.cu"

  B:\git\instant-ngp\build>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute
  _52\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu
   -I"B:\git\instant-ngp\dependencies" -I"B:\git\instant-ngp\dependencies\eigen" -I"B:\git\instant-ngp\dependencies\filesystem" -I"B:\git\instan
  t-ngp\dependencies\glfw\include" -I"B:\git\instant-ngp\dependencies\imgui" -I"B:\git\instant-ngp\dependencies\gl3w" -I"B:\git\instant-ngp\depe
  ndencies\nanovdb" -I"C:\ProgramData\NVIDIA Corporation\OptiX SDK 7.4.0\include" -I"B:\git\instant-ngp\dependencies\tiny-cuda-nn\include" -I"B:
  \git\instant-ngp\dependencies\tiny-cuda-nn\dependencies" -I"B:\git\instant-ngp\dependencies\tinylogger" -I"B:\git\instant-ngp\include" -I"B:\g
  it\instant-ngp\build" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include"     --keep-dir x64\RelWithDebInfo  -maxrregcount=0
   --machine 64 -ptx -cudart static --expt-relaxed-constexpr -std=c++14 -Xcompiler="/EHsc -Zi -Ob1" -D_WINDOWS -DNDEBUG -DNGP_GUI -DNGP_OPTIX -D
  "NGP_VERSION=\"1.0dev\"" -DTCNN_MIN_GPU_ARCH=0 -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -D_MBCS -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -o optix_progra
  m.dir\RelWithDebInfo\raytrace.ptx "B:\git\instant-ngp\src\optix\raytrace.cu"
  win32_joystick.c
B:\git\instant-ngp\include\neural-graphics-primitives/common.h(19): fatal error C1083: Cannot open include file: 'tinylogger/tinylogger.h': No s
uch file or directory [B:\git\instant-ngp\build\optix_program.vcxproj]
B:\git\instant-ngp\include\neural-graphics-primitives/common.h(19): fatal error C1083: Cannot open include file: 'tinylogger/tinylogger.h': No s
uch file or directory [B:\git\instant-ngp\build\optix_program.vcxproj]
  raystab.cu
  pathescape.cu
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.6.targets(790,9): error MSB3
721: 命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --use-local-e
nv -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu   -I"B:\git\instant-ng
p\dependencies" -I"B:\git\instant-ngp\dependencies\eigen" -I"B:\git\instant-ngp\dependencies\filesystem" -I"B:\git\instant-ngp\dependencies\glfw
\include" -I"B:\git\instant-ngp\dependencies\imgui" -I"B:\git\instant-ngp\dependencies\gl3w" -I"B:\git\instant-ngp\dependencies\nanovdb" -I"C:\P
rogramData\NVIDIA Corporation\OptiX SDK 7.4.0\include" -I"B:\git\instant-ngp\dependencies\tiny-cuda-nn\include" -I"B:\git\instant-ngp\dependenci
es\tiny-cuda-nn\dependencies" -I"B:\git\instant-ngp\dependencies\tinylogger" -I"B:\git\instant-ngp\include" -I"B:\git\instant-ngp\build" -I"C:\P
rogram Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include"     --keep-dir x64\RelWithDebInfo  -maxrregcount=0  --machine 64 -ptx -cudart stat
ic --expt-relaxed-constexpr -std=c++14 -Xcompiler="/EHsc -Zi -Ob1" -D_WINDOWS -DNDEBUG -DNGP_GUI -DNGP_OPTIX -D"NGP_VERSION=\"1.0dev\"" -DTCNN_M
IN_GPU_ARCH=0 -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -D_MBCS -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -o optix_program.dir\RelWithDebInfo\raystab.ptx "B
:\git\instant-ngp\src\optix\raystab.cu"”已退出，返回代码为 2。 [B:\git\instant-ngp\build\optix_program.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.6.targets(790,9): error MSB3
721: 命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --use-local-e
nv -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu   -I"B:\git\instant-ng
p\dependencies" -I"B:\git\instant-ngp\dependencies\eigen" -I"B:\git\instant-ngp\dependencies\filesystem" -I"B:\git\instant-ngp\dependencies\glfw
\include" -I"B:\git\instant-ngp\dependencies\imgui" -I"B:\git\instant-ngp\dependencies\gl3w" -I"B:\git\instant-ngp\dependencies\nanovdb" -I"C:\P
rogramData\NVIDIA Corporation\OptiX SDK 7.4.0\include" -I"B:\git\instant-ngp\dependencies\tiny-cuda-nn\include" -I"B:\git\instant-ngp\dependenci
es\tiny-cuda-nn\dependencies" -I"B:\git\instant-ngp\dependencies\tinylogger" -I"B:\git\instant-ngp\include" -I"B:\git\instant-ngp\build" -I"C:\P
rogram Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include"     --keep-dir x64\RelWithDebInfo  -maxrregcount=0  --machine 64 -ptx -cudart stat
ic --expt-relaxed-constexpr -std=c++14 -Xcompiler="/EHsc -Zi -Ob1" -D_WINDOWS -DNDEBUG -DNGP_GUI -DNGP_OPTIX -D"NGP_VERSION=\"1.0dev\"" -DTCNN_M
IN_GPU_ARCH=0 -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -D_MBCS -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -o optix_program.dir\RelWithDebInfo\pathescape.ptx
 "B:\git\instant-ngp\src\optix\pathescape.cu"”已退出，返回代码为 2。 [B:\git\instant-ngp\build\optix_program.vcxproj]
  win32_monitor.c
B:\git\instant-ngp\include\neural-graphics-primitives/common.h(19): fatal error C1083: Cannot open include file: 'tinylogger/tinylogger.h': No s
uch file or directory [B:\git\instant-ngp\build\optix_program.vcxproj]
  raytrace.cu
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.6.targets(790,9): error MSB3
721: 命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --use-local-e
nv -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu   -I"B:\git\instant-ng
p\dependencies" -I"B:\git\instant-ngp\dependencies\eigen" -I"B:\git\instant-ngp\dependencies\filesystem" -I"B:\git\instant-ngp\dependencies\glfw
\include" -I"B:\git\instant-ngp\dependencies\imgui" -I"B:\git\instant-ngp\dependencies\gl3w" -I"B:\git\instant-ngp\dependencies\nanovdb" -I"C:\P
rogramData\NVIDIA Corporation\OptiX SDK 7.4.0\include" -I"B:\git\instant-ngp\dependencies\tiny-cuda-nn\include" -I"B:\git\instant-ngp\dependenci
es\tiny-cuda-nn\dependencies" -I"B:\git\instant-ngp\dependencies\tinylogger" -I"B:\git\instant-ngp\include" -I"B:\git\instant-ngp\build" -I"C:\P
rogram Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include"     --keep-dir x64\RelWithDebInfo  -maxrregcount=0  --machine 64 -ptx -cudart stat
ic --expt-relaxed-constexpr -std=c++14 -Xcompiler="/EHsc -Zi -Ob1" -D_WINDOWS -DNDEBUG -DNGP_GUI -DNGP_OPTIX -D"NGP_VERSION=\"1.0dev\"" -DTCNN_M
IN_GPU_ARCH=0 -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -D_MBCS -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -o optix_program.dir\RelWithDebInfo\raytrace.ptx "
B:\git\instant-ngp\src\optix\raytrace.cu"”已退出，返回代码为 2。 [B:\git\instant-ngp\build\optix_program.vcxproj]
  win32_time.c
  win32_tls.c
  win32_window.c
  wgl_context.c
  egl_context.c
  Generating Code...
  glfw_objects.vcxproj -> B:\git\instant-ngp\build\dependencies\glfw\src\glfw_objects.dir\RelWithDebInfo\glfw_objects.lib

shows**:B:\git\instant-ngp\include\neural-graphics-primitives/common.h(19): fatal error C1083: Cannot open include file: 'tinylogger/tinylogger.h': No s
uch file or directory [B:\git\instant-ngp\build\optix_program.vcxproj]
B:\git\instant-ngp\include\neural-graphics-primitives/common.h(19): fatal error C1083: Cannot open include file: 'tinylogger/tinylogger.h': No s
uch file or directory [B:\git\instant-ngp\build\optix_program.vcxproj]**

**Comment by StarsTesla** [comment]
envs:
CUDA 11.6
Optix 7.4
GPU 3090
OS win10

**Comment by StarsTesla** [comment]
Solved it by re-clone the repo.

**Comment by cococolorful** [comment]
In fact, you can first download the submodule by typing `git submodule update --init --recursive`. If there is still a problem after downloading all code content, if not, try deleting the folder and typing `git submodule update --init --recursive` again. At this time, it will probably display `Submodule path 'dependencies/tinylogger': checked out '9b7a92ff44ffca3e80dca3549fa4eb599d039eeb'`, and then re-cmake it.
This way I don't have to re-clone the repository because I can't guarantee that my network won't go wrong the next time I clone:joy::joy::joy:
