### ISSUE TITLE
Error with "cmake --build build --config RelWithDebInfo -j 16  tiny-cuda-nn/cutlass_matmul.h(40): fatal error C1083: Unable to open include file: “cutlass/cutlass.h”: No such file or directory [C:\User s\Administrator\Desktop\instant-ngp\build\dependencies\tiny-cuda-nn\src\tiny-cuda-nn.vcxproj]  

### ISSUE THREAD

**Issue by Yancy-lv** [NVlabs/instant-ngp#504]
![1CMake -Bbuild](https://user-images.githubusercontent.com/95954197/164220380-a0acc9c5-e6a3-44f0-9c6e-a281dc97d986.png)
![2CMake -Bbuild](https://user-images.githubusercontent.com/95954197/164220416-bab49ef2-1ba5-455d-8032-f00563bfebc2.png)
![3RelWithDebInfo](https://user-images.githubusercontent.com/95954197/164220434-f60f06de-ab12-47c8-aec1-ea6cb1bab4ef.png)
![4RelWithDebInfo](https://user-images.githubusercontent.com/95954197/164220447-d35b853b-f06c-4f34-aef2-21071637014a.png)
![5error](https://user-images.githubusercontent.com/95954197/164220474-2c888921-88ab-49f9-8b77-0537e5022d24.png)
![6error](https://user-images.githubusercontent.com/95954197/164220482-443040bf-65ef-4c5d-be12-b86165f82ccf.png)
![7RelWithDebInfo](https://user-images.githubusercontent.com/95954197/164220501-1b6ddb20-3209-4cab-9c6a-94dd79814cb2.png)
![8error](https://user-images.githubusercontent.com/95954197/164220515-d1f4ec6a-808b-4364-bac6-bab6bba312d8.png)

**Comment by Yancy-lv** [comment]
envs:
Windows 10
GTX  1650
CUDA  11.6
CMake  3.22.4

**Comment by li195111** [comment]
Hi @Yancy-lv I got the same problem, do you solve it? can you share your solution?

**Comment by FuturaTino** [comment]
i got the same problem in the same envs

**Comment by Yancy-lv** [comment]
You&nbsp;might&nbsp;use&nbsp;"git&nbsp;clone&nbsp;--&nbsp;recursive"&nbsp;instead&nbsp;of&nbsp;"git&nbsp;clone".&nbsp;Because&nbsp;some&nbsp;sub&nbsp;modules&nbsp;may&nbsp;not&nbsp;be&nbsp;downloaded.



信息172吕苏倩
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NVlabs/instant-ngp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 上午7:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NVlabs/instant-ngp] Error with "cmake --build build --config RelWithDebInfo -j 16  tiny-cuda-nn/cutlass_matmul.h(40): fatal error C1083: Unable to open include file: “cutlass/cutlass.h”: No such file or directory [C:\User s\Administrator\Desktop\instant-ngp\build\dependencies\tiny-cuda-nn\src\tiny-cuda-nn.vcxproj]   (Issue #504)





 
i got the same problem in the same envs

**Comment by Yancy-lv** [comment]
You might use "git clone -- recursive" instead of "git clone". Because some sub modules may not be downloaded.

**Comment by Yancy-lv** [comment]
You&nbsp;might&nbsp;use&nbsp;"git&nbsp;clone&nbsp;--&nbsp;recursive"&nbsp;instead&nbsp;of&nbsp;"git&nbsp;clone".&nbsp;Because&nbsp;some&nbsp;sub&nbsp;modules&nbsp;may&nbsp;not&nbsp;be&nbsp;downloaded.



***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NVlabs/instant-ngp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 上午7:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NVlabs/instant-ngp] Error with "cmake --build build --config RelWithDebInfo -j 16  tiny-cuda-nn/cutlass_matmul.h(40): fatal error C1083: Unable to open include file: “cutlass/cutlass.h”: No such file or directory [C:\User s\Administrator\Desktop\instant-ngp\build\dependencies\tiny-cuda-nn\src\tiny-cuda-nn.vcxproj]   (Issue #504)





 
i got the same problem in the same envs
