### ISSUE TITLE
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified  

### ISSUE THREAD

**Issue by Cassiatora** [NVlabs/instant-ngp#548]
Hello! Who can tell what can I do?

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.1.t argets(785,9): error MSB3721: 命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc.exe" -gencode=arch=                                                                                                                      compute_86,code=\"compute_86,compute_86\" -gencode=arch=compute_86,code=\"sm_86,compute_86\" --use-local-env -ccbin "C: \Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu   -I"D:\Py thon code\instant-ngp\dependencies" -I"D:\Python code\instant-ngp\dependencies\eigen" -I"D:\Python code\instant-ngp\dep endencies\filesystem" -I"D:\Python code\instant-ngp\dependencies\glfw\include" -I"D:\Python code\instant-ngp\dependenci es\imgui" -I"D:\Python code\instant-ngp\dependencies\gl3w" -I"D:\Python code\instant-ngp\dependencies\nanovdb" -I"D:\Py thon code\instant-ngp\dependencies\tiny-cuda-nn\include" -I"D:\Python code\instant-ngp\dependencies\tiny-cuda-nn\depend encies" -I"D:\Python code\instant-ngp\dependencies\tiny-cuda-nn\dependencies\cutlass\include" -I"D:\Python code\instant -ngp\dependencies\tiny-cuda-nn\dependencies\cutlass\tools\util\include" -I"C:\Program Files\NVIDIA GPU Computing Toolki t\CUDA\v11.1\include"     --keep-dir x64\RelWithDebInfo -maxrregcount=0  --machine 64 --compile -cudart static --extend ed-lambda --expt-relaxed-constexpr -std=c++14 -Xcompiler="/EHsc -Zi -Ob1 -bigobj"    -D_WINDOWS -DNDEBUG -DTCNN_MIN_GPU _ARCH=86 -DTCNN_SHAMPOO -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -D_MBCS -Xcompiler "/EH sc /W1 /nologo /O2 /Fd"D:\Python code\instant-ngp\build\dependencies\tiny-cuda-nn\src\RelWithDebInfo\tiny-cuda-nn.pdb"  /FS /Zi  /MD /GR" -o tiny-cuda-nn.dir\RelWithDebInfo\optimizer.obj "D:\Python code\instant-ngp\dependencies\tiny-cuda-n n\src\optimizer.cu"”已退出，返回代码为 1。 [D:\Python code\instant-ngp\build\dependencies\tiny-cuda-nn\src\tiny-cuda-nn.vcxproj]                                                                                                               C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.1.t argets(785,9): error MSB3721: 命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc.exe" -gencode=arch=

**Comment by greenbrettmichael** [comment]
This is in the FAQ, the build doesn't accept spaces in filepaths, your filepath is
D:\Py thon code\instant-ngp\dependencies
suggest changing to something like
D:\Python_code\instant-ngp\dependencies
