### ISSUE TITLE
Testbed runs successfully, but GUI is blank

### ISSUE THREAD

**Issue by maskjp** [NVlabs/instant-ngp#55]
Hi, 

Thank you for the great work!
I followed the instruction and built the code without any errors occurring.

But when I ran the fox demo using ```./build/testbed --scene data/nerf/fox```, the window didn't show the fox image. After I run the marching cube, the meshes can be displayed. 

My system info is as follows:

- Ubuntu 18.04
- GCC 7.5
- CMake 3.22.1
- CUDA 11.3
- OptiX 7.3

When I built OptiX, it always failed to find the "IMathBox.h" file used by OpenEXR. So I ignored the OpenEXR when I installed OptiX. Is this the reason?

I am looking for your reply.

Thanks!

**Comment by sizeofbeer** [comment]
I have the same problem on ubuntu18.04, but it's visible on ubuntu20.04.
you can try it.

**Comment by bit704** [comment]
My GUI is blank in the Remote computer. It is because the displayer is not detected, applications that rely on hardware acceleration of the GPU will not display, and remote control of those applications will display a blank screen. 
I solved it by connecting the displayer to the remote computer.

**Comment by InconsolableCellist** [comment]
I had this issue and solved it by running `export CUDA_VISIBLE_DEVICES=0` which corresponds to the proper ID on my system. I think it was getting confused by my two GPUs.
