### ISSUE TITLE
Vulkan not initializing

### ISSUE THREAD

**Issue by jhurlbut** [NVlabs/instant-ngp#601]
With the latest commit I am getting a VK_ERROR_LAYER_NOT_PRESENT error returned from the call to vkCreateInstance. Any idea how to fix this?

OS: Ubuntu
GPU: 3090 ti
Driver: 
510.68.02

**Comment by jhurlbut** [comment]
removing the validation layer defination lines from dlss.cu around 155 and below seems to fix it?

**Comment by Tom94** [comment]
Hi there, should be fixed now. It's going to emit a warning about being unable to set up the validation layer on your system -- but that's generally fine as long as you don't run into Vulkan problems that need to be diagnosed.

**Comment by jhurlbut** [comment]
Thanks. I still am unable to initialize Vulkan but now I get the error message:
12:01:59 ERROR    Vulkan: loaderValidateLayers: Layer 0 does not exist in the list of available layers

I was able to fix by just installing the Vulkan SDK on my system. Maybe that should be added to the Readme?

**Comment by Tom94** [comment]
Done!
