### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by ASRodrigo1** [NVlabs/instant-ngp#607]
While installing, it's using all available RAM (16GB), then all available SWAP (2GB). After using all available memory it's killed and the installation never finishes.

![Screenshot from 2022-05-14 09-45-40](https://user-images.githubusercontent.com/45823308/168428453-c34a9095-2f77-4cc2-8807-6b15a96ac06f.png)

It happens after calling `cmake --build build --config RelWithDebInfo -j 16`

Cmake version = 3.23.1
Cuda version = 11.5

**Comment by Tom94** [comment]
You can use fewer parallel threads for compilation (e.g. `-j 2`), which will alleviate RAM load at the cost of taking longer.

**Comment by ASRodrigo1** [comment]
Thanks, it worked
