### ISSUE TITLE
At cmake . -B build  it give the error of fail to find a CmakeLists.txt file

### ISSUE THREAD

**Issue by FuturaTino** [NVlabs/instant-ngp#615]
![1](https://user-images.githubusercontent.com/103358629/168751265-abf3ce63-b136-4bf1-9683-4b3628007697.png)

**Comment by VibraniumQ** [comment]
It seems you forgot to run the following commands:
```sh
git submodule sync --recursive
git submodule update --init --recursive
```
which is mentioned in [README file](https://github.com/NVlabs/instant-ngp/blob/master/README.md#Troubleshooting-compile-errors).
Hope this can address your problem.
