### ISSUE TITLE
getting CmakeLists Error

### ISSUE THREAD

**Issue by Maki9009** [NVlabs/instant-ngp#619]
CMake Error at CMakeLists.txt:38 (message):
  Some instant-ngp dependencies are missing.  If you forgot the "--recursive"
  flag when cloning this project, this can be fixed by calling "git submodule
  update --init --recursive".

-- Configuring incomplete, errors occurred!
See also "C:/Users/UserName/Desktop/Instant Nerf/instant-npg/build/CMakeFiles/CMakeOutput.log".

don't know whats wrong

**Comment by Tom94** [comment]
Doing what the error message tells you to do, i.e. running
```sh
git submodule update --init --recursive
```
should do the trick.
