### ISSUE TITLE
Build Error On Windows related to Json.

### ISSUE THREAD

**Issue by fafancier** [NVlabs/instant-ngp#62]
Thanks for your work 
I build it on win10 cuda11.1  

I got this error when build  [tiny-cuda-nn] with the latest repo, any suggestion? could you help me with this error
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/39083471/150302590-4b33a667-67a4-4350-82a1-fa568943c135.png">
```
1>J:\InstantNGP\instant-ngp\dependencies\tiny-cuda-nn\dependencies\json/json.hpp(6891): error : enum "nlohmann::detail::lexer_base<BasicJsonType>::token_type [with BasicJsonType=BasicJsonType]" has no member "parse_error"
1>
1>J:\InstantNGP\instant-ngp\dependencies\tiny-cuda-nn\dependencies\json/json.hpp(6897): error : enum "nlohmann::detail::lexer_base<BasicJsonType>::token_type [with BasicJsonType=BasicJsonType]" has no member "value_string"
1>
1>J:\InstantNGP\instant-ngp\dependencies\tiny-cuda-nn\dependencies\json/json.hpp(6947): error : enum "nlohmann::detail::lexer_base<BasicJsonType>::token_type [with BasicJsonType=BasicJsonType]" has no member "parse_error"

**Comment by Tom94** [comment]
Based on similar issues in the past, updating Visual Studio and subsequently updating to the latest version of CUDA 11 will likely fix this issue.

**Comment by Punkin18** [comment]
- [ ] @dumerrill
