### ISSUE TITLE
fatal error: nvsdk_ngx_vk.h: No such file or directory

### ISSUE THREAD

**Issue by achaosss** [NVlabs/instant-ngp#621]
root@jmd250-Y730:/home/jmd250/Desktop/clik/instant-ngp# cmake --build build --config RelWithDebInfo -j 16
[ 29%] Built target glfw_objects
[ 49%] Built target tiny-cuda-nn
[ 50%] Building CUDA object CMakeFiles/ngp.dir/src/dlss.cu.o
/home/jmd250/Desktop/clik/instant-ngp/src/dlss.cu:36:10: fatal error: nvsdk_ngx_vk.h: No such file or directory
   36 | #include <nvsdk_ngx_vk.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/ngp.dir/build.make:76: CMakeFiles/ngp.dir/src/dlss.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:172: CMakeFiles/ngp.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by achaosss** [comment]
cuda_11.4.r11.4/compiler.30300941_0
gcc version 9.4.0
ubuntu20.04

Hey, Does anyone have this problem.nvsdk_ngx_vk.h: No such file or directory

**Comment by Tom94** [comment]
Hi there, this sounds like the DLSS submodule is missing.
```sh
git submodule sync --recursive
git submodule init --recursive
git submodule update --recursive
```
should do the trick.

**Comment by achaosss** [comment]
Thanks~ It Done.
