### ISSUE TITLE
Build Error on Windows related to Nmake

### ISSUE THREAD

**Issue by telarium** [NVlabs/instant-ngp#65]
After installing the dependencies in the documentation, I'm running into this error:

```
CMake Error at CMakeLists.txt:11 (PROJECT):
  Running

   'nmake' '-?'

  failed with:

   The system cannot find the file specified


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CUDA_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

Windows 10
CMake 3.22.1
Visual Studio 2022
Cuda 11
Python 3.10

**Comment by pureexe** [comment]
Run CMD with administrator and use this command before Cmake

```
"C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64
```

**Comment by telarium** [comment]
This didn't solve it for me. I opened my console as administrator and ran the command, which gave me this output:

```
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.0.5
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
```

Immediately after, if I run the "cmake . -B build" command, I get the same error about nmake.

**Comment by YtengTan** [comment]
Don't use Visual Studio 2022, try Visual Studio 2019. Seems cuda toolkit hasn't supported vs2022. You will find the tools for visual studio didn't install after ur cuda installation.
1. uninstall VS 2022 and delete the instant-ngp repo(because the cmakelist records ur VS path from ur previous build attempt)
2. install VS 2019 and C++ things
3. install cuda, choose customize and check the  VS tools option
I had the same issue, and found that it was cuda tools for VS install failed, and successfully built after changing the Visual Studio version to 2019.
Hope it works for u

**Comment by kdand35** [comment]
> This didn't solve it for me. I opened my console as administrator and ran the command, which gave me this output:
> 
> ```
> **********************************************************************
> ** Visual Studio 2022 Developer Command Prompt v17.0.5
> ** Copyright (c) 2021 Microsoft Corporation
> **********************************************************************
> ```
> 
> Immediately after in the same console window, if I run the "cmake . -B build" command, I get the same error about nmake.

Hi, Did you solve this? I run 'cmake . -B build' in VS2019 developer command prompt and got the same error. Do you have any idea for addressing it? Thank you in advance

**Comment by kdand35** [comment]
> > This didn't solve it for me. I opened my console as administrator and ran the command, which gave me this output:
> > ```
> > **********************************************************************
> > ** Visual Studio 2022 Developer Command Prompt v17.0.5
> > ** Copyright (c) 2021 Microsoft Corporation
> > **********************************************************************
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Immediately after in the same console window, if I run the "cmake . -B build" command, I get the same error about nmake.
> 
> Hi, Did you solve this? I run 'cmake . -B build' in VS2019 developer command prompt and got the same error. Do you have any idea for addressing it? Thank you in advance


In my old version of the VS 2019, I only installed python packages, so I have solved this by adding C++ packages for VS 2019.

**Comment by alchemician** [comment]
I tried this, but it started throwing new errors

cmake . -B build -DCMAKE_CXX_COMPILER=C:\MinGW\bin\g++.exe -DCMAKE_C_COMPILER=C:\MinGW\bin\gcc.exe -DCMAKE_CUDA_COMPILER="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\nvcc.exe"
