### ISSUE TITLE
How to render images enabling DLSS in a headless device?

### ISSUE THREAD

**Issue by aritra-pal** [NVlabs/instant-ngp#656]
Hi, first of all, thanks for this awesome work. I have built it successfully on my device with vulkan SDK. So, I can enable DLSS in the GUI while rendering the scenes. 
However, I am wondering while I am saving images using the run.py script are those images are rendered with DLSS?
If not, can you please help me to enable DLSS while using the command line?

**Comment by Tom94** [comment]
Hi there, DLSS is not supported in headless mode. Supporting it would require disentangling Vulkan from GLFW, as well as figuring out an API to carry over motion vectors across separate `testbed.render` calls. Both of which are out of scope of this project at the moment. Cheers!
