### ISSUE TITLE
I have a build error on Windows with "cmake . -B build"

### ISSUE THREAD

**Issue by FilipeF12** [NVlabs/instant-ngp#66]
CMake Error at CMakeLists.txt:11 (PROJECT):
  Running

   'nmake' '-?'

  failed with:

   The system cannot find the file specified

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CUDA_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Comment by telarium** [comment]
This seems to be a duplicate of issue #65

**Comment by FilipeF12** [comment]
When I entered mine, #64 was the latest. After I added mine I saw yours. For now I'm leaving mine since some of my system data and software is different.

**Comment by pureexe** [comment]
You need to run `VsDevCmd.bat` before `cmake`

see how to run at: https://github.com/NVlabs/instant-ngp/issues/65#issuecomment-1018186575

**Comment by Tom94** [comment]
Closing as duplicate of #65 -- I don't think the system data specifics make a difference here. @pureexe's answer is the right one.

**Comment by FilipeF12** [comment]
> You need to run `VsDevCmd.bat` before `cmake`
> 
> see how to run at: [#65 (comment)](https://github.com/NVlabs/instant-ngp/issues/65#issuecomment-1018186575)

I am not using Microsoft Visual Studio.

> Closing as duplicate of #65 -- I don't think the system data specifics make a difference here. @pureexe's answer is the right one.

I am not using Microsoft Visual Studio.

**Comment by Tom94** [comment]
What are you using then? Beware that Visual Studio is the only compiler that this codebase was tested on on Windows -- getting it to compile using another pipeline might be involved (even though I hope it isn't).

**Comment by FilipeF12** [comment]
Requirements said "a C++14 capable compiler" so I Googled that and came up with MinGW GNU gcc.

**Comment by Tom94** [comment]
Apologies, you're right in that the readme should specify this in more detail rather than just assuming the most popular / default compilers in the respective OS's.

I'll make the respective change. The recommendation (that [CI](https://github.com/NVlabs/instant-ngp/actions/runs/1727321226) is testing for) is
- Visual Studio 2019 on Windows
- gcc on Linux

**Comment by FilipeF12** [comment]
Is Visual Studio free and easy to use? I can switch. I'm not ready to switch to Linux because of other software I run.

**Comment by Tom94** [comment]
Yes, Visual Studio is free and should be much easier to get going with than MinGW.
