### ISSUE TITLE
ERROR    Scene path data\nerf\fox does not exist.

### ISSUE THREAD

**Issue by jwetalley1** [NVlabs/instant-ngp#660]
I get the error when trying to run the fox example.  

(ngp) C:\Tutorial\ngp\instant-ngp\build>testbed --scene data\nerf\fox
**08:29:51 ERROR    Scene path data\nerf\fox does not exist.**

(ngp) C:\Tutorial\ngp\instant-ngp\build>conda info -e
# conda environments:
#
base                     C:\Users\vzn.iprg1\anaconda3
ngp                   *  C:\Users\vzn.iprg1\anaconda3\envs\ngp

Is there something wrong with my env?  What is causing this issue? Thanks!

**Comment by Dmarcotrigiano** [comment]
The command will attempt to resolve the path of the scene as a relative path to the current working directory, AFAIK. Try running the command 
`build\testbed --scene data\nerf\fox`
from 
`(ngp) C:\Tutorial\ngp\instant-ngp`
