### ISSUE TITLE
Memory issue when using own dataset

### ISSUE THREAD

**Issue by WXuanyang** [NVlabs/instant-ngp#67]
Thanks for your excellent work! I'm testing the code with my own data on a 3070 machine with 8GB memory, it works fine with the example fox data (50 1080*1920 images). However when I test the model on my own data, which has 35 1920*1080 images, the memory issue comes up:
![image](https://user-images.githubusercontent.com/69446297/150457441-248e4ec3-ef44-4d0d-871e-062afbc01984.png)
Fox data: everything works just fine

![image](https://user-images.githubusercontent.com/69446297/150457492-6eaf0b03-ce8d-41b0-8108-ec4eb4d6b7b5.png)
My own data: fewer image loaded but have the memory error

What could have caused this problem? My dataset have the same number of pixels per image as the example data and contain even fewer images, but why is my dataset using more memory? 

Also, it will be great if someone can tell me how to modify the network parameters to reduce memory usage since I'll need some extra memory reserved to extract high resolution mesh

**Comment by pureexe** [comment]
Could you share how you overcome the memory issue?

**Comment by WXuanyang** [comment]
> Could you share how you overcome the memory issue?

Sure, I did this by adjusting the aabb value when creating the dataset, you can find more detailed instructions here:
https://github.com/NVlabs/instant-ngp/blob/master/docs/nerf_dataset_tips.md
