### ISSUE TITLE
Build faild(win10 cuda11.1 )

### ISSUE THREAD

**Issue by zuixiaosanlang** [NVlabs/instant-ngp#673]
![image](https://user-images.githubusercontent.com/20105627/172984937-8fd1c43a-351b-4ea8-b26f-ddebcede0cb7.png)

error MSB3721

![image](https://user-images.githubusercontent.com/20105627/172985080-5d3a3a44-f70d-41d9-8393-34c5af2bdd57.png)

about device, i also try to change 7.5 to 8 By VS Studio 2019, but also get error  MSB3721

**Comment by hanikhatib** [comment]
Try installing CUDA v11.6 and ensure it is in your environment PATH

**Comment by zuixiaosanlang** [comment]
@hanikhatib 
thank you. i chang to cuda v11.4，everything goes ok
