### ISSUE TITLE
GUI application does not work with X11 forwarding

### ISSUE THREAD

**Issue by chekhovana** [NVlabs/instant-ngp#679]
I am trying to launch testbed application in gui mode on remote ubuntu server and forward display to local Mac with XQuartz. The application fails to start with the following output:

`03:23:56 INFO     Loading NeRF dataset from`
` 03:23:56 WARNING    data/nerf/fox/base_cam.json does not contain any frames. Skipping.`
`03:23:56 INFO       data/nerf/fox/valid.json`
`03:23:56 INFO       data/nerf/fox/transforms.json`
`03:23:56 INFO       data/nerf/fox/camera.json`
`03:23:56 SUCCESS  Loaded 53 images after 0s`
`03:23:56 INFO       cam_aabb=[min=[1.0229,-1.33309,-0.378748], max=[2.46175,1.00721,1.41295]]`
`03:23:56 INFO     Loading network config from: configs/nerf/base.json`
`03:23:56 INFO     GridEncoding:  Nmin=16 b=1.51572 F=2 T=2^19 L=16`
`03:23:56 INFO     Density model: 3--[HashGrid]-->32--[FullyFusedMLP(neurons=64,layers=3)]-->1`
`03:23:56 INFO     Color model:   3--[Composite]-->16+16--[FullyFusedMLP(neurons=64,layers=4)]-->3`
`03:23:56 INFO       total_encoding_params=13074912 total_network_params=10240`
`03:24:02 WARNING  Vulkan: loader_icd_scan: Can not find 'ICD' object in ICD JSON file /usr/share/vulkan/icd.d/nvidia_layers.json.  Skipping ICD JSON`
`03:24:02 WARNING  Could not initialize Vulkan and NGX. DLSS not supported. (Buffer device address extension not available.)
libGL error: No matching fbConfigs or visuals found`
`libGL error: failed to load driver: swrast`
`03:24:03 ERROR    GLFW error #65543: GLX: Forward compatibility requested but GLX_ARB_create_context_profile is unavailable`
`03:24:03 ERROR    Uncaught exception: GLFW window could not be created.`

Has anyone encountered the same problem? Any help would be greatly appreciated.

**Comment by paulmelis** [comment]
This is no surprise, X11 forwarding on an OpenGL application is in most cases useless (as the required GLX extensions are not supported by the protocol). You are probably better off running a VNC server on the remote machine and use VirtualGL to render locally.

**Comment by chekhovana** [comment]
Thanks for the answer, 

I've already tried VirtualGL, but it turned out to be extremely slow.

**Comment by paulmelis** [comment]
> I've already tried VirtualGL, but it turned out to be extremely slow.

Then there's probably something amiss with the setup (network, VNC viewer, etc) you're using, as I use it with the instant-ngp viewer remotely with no performance issue whatsoever.

**Comment by barakmam** [comment]
I have the same problem with the X11 forwarding. 
I can't use the VNC :/ .
Is there an option to get some results without the testbed guy? i.e. only running a script that saves the model or .mp4 file of the fox?

**Comment by chekhovana** [comment]
@barakmam yes, you can. Read the first question in the FAQ section:
[How can I run instant-ngp in headless mode?](https://github.com/NVlabs/instant-ngp#frequently-asked-questions-faq)

**Comment by chekhovana** [comment]
@barakmam take a look at the [example of python script usage](https://github.com/NVlabs/instant-ngp/discussions/326#discussioncomment-2361698)

**Comment by Harper714** [comment]
> This is no surprise, X11 forwarding on an OpenGL application is in most cases useless (as the required GLX extensions are not supported by the protocol). You are probably better off running a VNC server on the remote machine and use VirtualGL to render locally.


Hi, is there any tutorial material about how to set VNC + VirtualGL? I also met the same issue but not familiar with the GUI setting. Thanks!

**Comment by paulmelis** [comment]
We use TurboVNC as VNC server, which works very well. See [here (latest version)](https://turbovnc.org/Documentation/Documentation) for more information. Documentation on VirtualGL can be found [here](https://rawcdn.githack.com/VirtualGL/virtualgl/3.0.2/doc/index.html). 

In principle, both TurboVNC and VirtualGL can be installed in most Linux distros through their respective package manager. VirtualGL does not need any configuration, TurboVNC in generally also doesn't need it (but has some options that can be tweaked). You need to install both these packages on the GPU system you intend to run instant-ngp on. On the PC/laptop from which you intend to connect to you only need the VNC viewer (which can be TurboVNC as well).

When installed starting the VNC server on the GPU server is as simple as `vncserver :1` in a shell. I'm assuming a Linux system here, btw, don't know about other OSs. Once you have the VNC server running, connect to it using the VNC client on the PC/laptop, by connecting to the host name of the GPU server (e.g. `gpuserver:1`). You should now get a remote desktop view. Within that, open a terminal window and navigate to where instant-ngp is installed. Run the instant-ngp viewer with `vglrun <path-to-testbed-binary> ...`. The `vglrun` part is crucial, without it you won't get GPU acceleration.

**Comment by Harper714** [comment]
@paulmelis  Hi paul, many thanks for your information. Following your guidance, I managed to connect to the GPU server via TurboVNC viewer. However, the refresh of the screen is extremely slow on my windows PC. I am trying to find solutions...

**Comment by paulmelis** [comment]
With "refresh of the screen" do you mean the remote desktop itself, regardless of which application you're running inside it? If so, VNC over wifi will not work very well (high latency), so use a wired network connection if you can. Also, the higher the resolution of the desktop, or the size of the windows updating within the desktop, will have an impact on the refresh rate. There's usually also an option in the VNC client to pick the maximum bandwidth and/or screen encoding. Those settings can usually improve the refresh rate.

**Comment by Harper714** [comment]
> With "refresh of the screen" do you mean the remote desktop itself, regardless of which application you're running inside it? If so, VNC over wifi will not work very well (high latency), so use a wired network connection if you can. Also, the higher the resolution of the desktop, or the size of the windows updating within the desktop, will have an impact on the refresh rate. There's usually also an option in the VNC client to pick the maximum bandwidth and/or screen encoding. Those settings can usually improve the refresh rate.

I tried to set the scene encoding options, but it can only improve the refresh rate slightly... I am using the python script without GUI now :(

**Comment by Harper714** [comment]
yes, non-graphics windows also have a low refresh rate, even the terminal... I am working on a windows system, and the remote server works in the internal network always needs a proxy to access outside, I don't know if these points affect the performance...
