### ISSUE TITLE
Tips for calculating offset for nerf?

### ISSUE THREAD

**Issue by markisus** [NVlabs/instant-ngp#68]
Following the instructions here https://github.com/NVlabs/instant-ngp/blob/master/docs/nerf_dataset_tips.md I see clearly that my nerf data does have the points of interest inside the unit cube. I have tried adjusting the "offset" parameter in the transforms.json but the results are not intuitive. 

![image](https://user-images.githubusercontent.com/469689/150461876-79f4289e-47ab-49d0-8c2f-5a043ffa9aaa.png)
![image](https://user-images.githubusercontent.com/469689/150462201-6d7c5575-dee1-4809-8562-26807fe3e340.png)

I would like to move the box in the direction of the arrow, but I'm not sure what offset vector that corresponds to. Any tips for doing this?

**Comment by markisus** [comment]
Doing some more experimenting, I discovered that blue=x, red=y, green=z. The units of the box are 1 unit along each side. The positive directions on each axis are pointing outside of the box. If you want to move the box one unit along the red axis, the offset would be [0.5, 1.5, 0.5] (the .5's come in because that is the default origin of the box).

![image](https://user-images.githubusercontent.com/469689/150464111-3e4a8180-f88b-42a7-9d0d-6f8b392ba1e1.png)

**Comment by mmalex** [comment]
hi
there was a bug in colmap2nerf that was fixed recently. could you try
re-running colmap2nerf on your dataset with the latest version?
thanks

**Comment by markisus** [comment]
Thanks, updated to latest and the colmap2nerf calculated the box for me automatically!
