### ISSUE TITLE
Cropping 3D Mesh from run.py

### ISSUE THREAD

**Issue by acun1994** [NVlabs/instant-ngp#683]
Is there a way to crop the 3D Mesh generated by running the run.py script? Preferably similarly to the way the GUI handles the cropping when crop_aabb option is active.

Thanks for any help or suggestions

**Comment by acun1994** [comment]
For additional info, what I've done so far is adding the following lines to run.py

`testbed.render_aabb = ngp.BoundingBox([0.25, -1.5, -1.5], [1.5, 2.5, 2.5])`

to presumable set the initial rendering confines, and

`testbed.compute_and_save_marching_cubes_mesh(args.save_mesh, [res, res, res], ngp.BoundingBox([0.25, -1.5, -1.5], [1.5, 2.5, 2.5])`

to crop the 3D mesh accordingly.

The resulting mesh I get is Cropped as specified, but it is stretched into a cube (presumably into the original unit cube)

![Original Untweaked Settings](https://user-images.githubusercontent.com/7620407/173488882-38211f90-1a26-441b-85c4-ca858a646a5b.png)

**Comment by MichaelXt** [comment]
There appears to be a bug in `int Testbed::marching_cubes(Vector3i res3d, const BoundingBox& aabb, float thresh) {`
fix by changing `m_render_aabb` -> `aabb`
```
	// marching_cubes_gpu(m_inference_stream, m_render_aabb, res3d, thresh, density, m_mesh.verts, m_mesh.indices);
	marching_cubes_gpu(m_inference_stream, aabb, res3d, thresh, density, m_mesh.verts, m_mesh.indices);
```
then rebuild the instant-ngp and try it out.

Explanation: The UI sets `m_render_aabb` and mesh generation uses it. The script doesn't set it, hence the mapping is incorrect. That fixed the vertex coloring for me, however I haven't tried if it would stop the stretching of the cube.

**Comment by acun1994** [comment]
Thanks for that, seems to fix my issue.

**Comment by Tom94** [comment]
The fix is implemented, along with the additional ability to rotate the crop box.
