### ISSUE TITLE
TSDF fusion based on NGP rendered color and depth

### ISSUE THREAD

**Issue by liruiw** [NVlabs/instant-ngp#687]
### Discussed in https://github.com/NVlabs/instant-ngp/discussions/684

<div type='discussions-op-text'>

<sup>Originally posted by **liruiw** June 13, 2022</sup>
Hello,

I am looking for ways to do RGB-D fusion based on the camera trajectory. In addition to rendered [RGB](https://github.com/NVlabs/instant-ngp/blob/master/scripts/run.py#L257) image, I have also added depth output. However, when I use the camera poses in transforms.json along with the RGB-D information, the fused TSDF does not seem correct. In other words, how to align the depth images to the colmap poses. I think I might be missing a pose transforms based on NGP conventions. 

I am also curious if there is a way to get metric-scale depth and reconstruction, given known camera poses and potential depth supervision. Thanks!</div>

**Comment by kafei123456** [comment]
> ### Discussed in #684
> Originally posted by **liruiw** June 13, 2022 Hello,
> 
> I am looking for ways to do RGB-D fusion based on the camera trajectory. In addition to rendered [RGB](https://github.com/NVlabs/instant-ngp/blob/master/scripts/run.py#L257) image, I have also added depth output. However, when I use the camera poses in transforms.json along with the RGB-D information, the fused TSDF does not seem correct. In other words, how to align the depth images to the colmap poses. I think I might be missing a pose transforms based on NGP conventions.
> 
> I am also curious if there is a way to get metric-scale depth and reconstruction, given known camera poses and potential depth supervision. Thanks!

have your problems solution?
