### ISSUE TITLE
No module named 'pyngp'

### ISSUE THREAD

**Issue by TimSousa1** [NVlabs/instant-ngp#688]
CMake did generate and build the file “pyngp.cp310-win_amd64.pyd” successfully 
but… even though I'm running python v3.8, it generated a file for python 3.10
so when I run “python scripts/render.py --scene data/tree --n_seconds 60 --fps 60 --render_name tree1 --width 1920 --height 1080”
i get:
```
Traceback (most recent call last):
  File "scripts/render.py", line 16, in <module>
    import pyngp as ngp # noqa
ModuleNotFoundError: No module named 'pyngp'
```

**Comment by lhy0807** [comment]
See #43

**Comment by TimSousa1** [comment]
I decided to build the project again, but using py v.3.10
That fixed it. Thanks anyways!
(Posting this is in case someone else is having a similar issue)

**Comment by Timothy-pop** [comment]
> 我决定再次构建该项目，但使用 py v.3.10 修复了它。无论如何，谢谢！ （发布此内容是为了以防其他人遇到类似问题）

Thank you very much for the information you provided!
I found my file, it is /home/timo/documents/instant-ngp/build/pyngp.cpython-311-x86_64-linux-gnu.so.
So, I was able to recreate the environment with python==3.11 in the virtual environment.
The issue has been resolved.

**Comment by RyanAshbaugh** [comment]
This also works well.

`$ export PYTHONPATH=./build_ngp/`
