### ISSUE TITLE
Running into issue with Camera render - No render.py found

### ISSUE THREAD

**Issue by stannardtyler** [NVlabs/instant-ngp#693]
Followed bycloud's tutorial to get everything up and running and having success with multiple models. My issue comes with rendering out the camera path. I've saved the snapshot and created the corresponding json file, however once I enter in the script below:

`python script/render.py --scene data/vasona_rock --n_seconds 10 --fps 60 --render_name test_V_rock --width 1920 --height 1080
`
I run into this error: 

python: can't open file 'D:\ngp-tutorial\ngp\instant-ngp\script\render.py': [Errno 2] No such file or directory

Looking back into the script files I did notice that there was no render.py listed. So I manually added the render.py script manually from bycloud's forked repo, yet the error still persists. Unsure where to go from here. 

So far for trouble shooting I followed bycloud's method to install more dependencies. Install `pip install tqdm scipy pillow opencv-python`, `conda install -c conda-forge ffmpeg`. Yet the whole "might be needed in the conda virtual environment" I was unsure if needed as I had success installing the pyexr file. So this could be the root of the issue within the environments. 

Any support would be greatly appreciated! Thank you! 

p.s. I'm a bit of a noob to all of this but having fun!

**Comment by Vincentqyw** [comment]
maybe the typo error: `script` -> `scripts`

**Comment by stannardtyler** [comment]
YO Thank you that was it. Always nice to have a second eye! Thanks Vincentqyw.

That issue has be resolved.

**Comment by TimSousa1** [comment]
for some reason I'm missing render.py.. 
any ideas?
when running `python scripts/render.py --scene data/algarve_stove --n_seconds 10 --fps 60 --render_name algarve_stove_video_render --width 1920 --height 1080` i get thrown this error: python: `can't open file 'D:\ngp\ngp3\instant-ngp\scripts\render.py': [Errno 2] No such file or directory`
it's my fifth time installing and I'm still missing render.py
