### ISSUE TITLE
I got problem at "cmake --build build --config RelWithDebInfo -j 16"

### ISSUE THREAD

**Issue by BUILDERlym** [NVlabs/instant-ngp#70]
here are the errors
![image](https://user-images.githubusercontent.com/71302160/150557805-4c2f3ac0-8d6f-482f-b977-4e770a1063fb.png)
![image](https://user-images.githubusercontent.com/71302160/150558099-adab2c25-2f56-483c-8903-1884980ad141.png)
but im using a rts 3090, anyone can help me?

**Comment by SomeoneSerge** [comment]
Compute 86

E.g. configure with
```bash
$ TCNN_CUDA_ARCHITECTURES=86 cmake -S . -B build -D CMAKE_BUILD_TYPE=RelWithDebInfo
```

**Comment by BUILDERlym** [comment]
> Compute 86
> 
> E.g. configure with
> 
> ```shell
> $ TCNN_CUDA_ARCHITECTURES=86 cmake -S . -B build -D CMAKE_BUILD_TYPE=RelWithDebInfo
> ```

![image](https://user-images.githubusercontent.com/71302160/150620727-4d9189fe-920a-4c09-a12b-211072759075.png)
no, it's still not working

**Comment by SomeoneSerge** [comment]
Have you checked how old your nvcc is?

**Comment by BUILDERlym** [comment]
I figured out. RTX3090 requires CUDA 11.1 or higher

**Comment by BUILDERlym** [comment]
> Hello, have you checked how old your nvcc is?

now i upgrade to 11.1, thanks a lot
