### ISSUE TITLE
can arcore use for nerf like colmap?

### ISSUE THREAD

**Issue by zuixiaosanlang** [NVlabs/instant-ngp#704]
i have images and pose from arcore, can use for nerf like colmap?

camera model like this: 
![image](https://user-images.githubusercontent.com/20105627/174750413-763bc690-6f4e-4c25-b235-3d0618ba6daf.png)

i generate the transforms.json like this:

![image](https://user-images.githubusercontent.com/20105627/174751035-003dc7ed-527b-4325-acd8-74ff18e36412.png)

i notice that The transformation from COLMAP to ARCore's system is:
[[1, 0, 0, 0],
 [0, -1, 0, 0],
 [0, 0, -1, 0]]

so i command the two line:
![image](https://user-images.githubusercontent.com/20105627/174751643-961bcd97-6f56-4b5c-8c38-140d1e5dda9c.png)

but when i train, the result is wrong and bad.

**Comment by reynoldscem** [comment]
@zuixiaosanlang did you figure this out?

**Comment by helenacorreia** [comment]
@zuixiaosanlang Hello, Did you get good results using Arcore? If you could, could you provide the code to transform the arcore into nerf? Thanks

**Comment by zuixiaosanlang** [comment]
> 



> @zuixiaosanlang Hello, Did you get good results using Arcore? If you could, could you provide the code to transform the arcore into nerf? Thanks
![image](https://user-images.githubusercontent.com/20105627/176652395-e0264de6-190b-4f07-abb1-84fabe22481e.png)
![image](https://user-images.githubusercontent.com/20105627/176652395-e0264de6-190b-4f07-abb1-84fabe22481e.png)

i just do this. it looks good.

**Comment by zuixiaosanlang** [comment]
> @zuixiaosanlang did you figure this out?



> @zuixiaosanlang did you figure this out?

arcore Coordinate system is opengl，and the pose R is aleardy camera2world

**Comment by helenacorreia** [comment]
@zuixiaosanlang Hello, thank you very much for your answer. But I still have doubts about how you imported the data from arcore? I look forward to hearing from you! Thanks

**Comment by zuixiaosanlang** [comment]
@helenacorreia 
images, pose, camera intrinsics come from arcore;  code to get them like this:
![image](https://user-images.githubusercontent.com/20105627/177726770-95c5527a-754b-4edc-8fcf-eaf62b88da26.png)

save them:
![image](https://user-images.githubusercontent.com/20105627/177727229-4c39ef36-4450-4a5e-92f8-2214f96cec89.png)

![image](https://user-images.githubusercontent.com/20105627/177727866-2c70cc10-64d8-45c3-9ab2-e92edc44803f.png)

imported them fllow by colmap2nerf.py:
![image](https://user-images.githubusercontent.com/20105627/177728406-ed7e11cf-4133-4cf5-b913-cce3e42530cc.png)
![image](https://user-images.githubusercontent.com/20105627/177728570-57f7e4aa-d20f-4299-8363-2942b18c3cac.png)

**Comment by 1kaiser** [comment]
hoe to get data and pose from arcore is there any app for this for andriod ?? arcore2nerf.py script ???

**Comment by hnj5247** [comment]
Hello I'm trying to train through nerf with arcore. Could I know which camera you used to take the position? Will an android smart phone be accurate to get pose? I'm curious about your camera. Thank you.
