### ISSUE TITLE
Help with rendering camera animation

### ISSUE THREAD

**Issue by jimmaybones** [NVlabs/instant-ngp#713]
When I run the render.py script I get:

 Loading network config from: data\into_building\base.msgpack
Traceback (most recent call last):
  File "C:\Users\Admin\ngp\instant-ngp\scripts\render.py", line 56, in <module>
    render_video([args.width, args.height], args.n_seconds*args.fps, args.scene, args.render_name, spp=8, fps=args.fps)
  File "C:\Users\Admin\ngp\instant-ngp\scripts\render.py", line 23, in render_video
    testbed.load_snapshot(os.path.join(scene, "base.msgpack"))
RuntimeError: Network config "data\into_building\base.msgpack" does not exist.

Any help would be greatly appreciated!

**Comment by Vincentqyw** [comment]
it seems you don't provide the snapshot, please check if you have saved the snapshot in the correct path.

**Comment by VibrantNebula** [comment]
What is your order of commands?
