### ISSUE TITLE
Since the latest commit the project builds for suboptimal GPU arch

### ISSUE THREAD

**Issue by reynoldscem** [NVlabs/instant-ngp#724]
Since the commits today the project seems to compile for GPU arch 51 when 86 is available. Seems exporting `TCNN_CUDA_ARCHITECTURE` makes the appropriate target build.

**Comment by Rifahaziz** [comment]
What version of TCNN_CUDA_ARCHITECTURE works? Seems like building works only for 75. But that is not enough to run fullyfusedMLP. I tried 86 and 100 but building fails towards the end.  Any solution to this for the colab version? Thanks.
