### ISSUE TITLE
Colab Notebook build broken

### ISSUE THREAD

**Issue by EsbernTK** [NVlabs/instant-ngp#729]
There is currently a problem with the colab notebook that is linked in this repo, when building testbed.cu
Colab link: https://colab.research.google.com/drive/10TgQ4gyVejlHiinrmm5XOvQQmgVziK3i?usp=sharing
(I am running a GPU Notebook, so missing GPU is not the problem)

Steps to recreate:
 - Open colab Notebook
 - select GPU runtime
 - "Run all" cells

Error:

[ 59%] Building CUDA object CMakeFiles/ngp.dir/src/testbed_image.cu.o
/content/instant-ngp/src/testbed.cu(1640): error: class "ngp::Testbed" has no member "create_second_window"

/content/instant-ngp/src/testbed.cu(1641): error: identifier "m_second_window" is undefined

/content/instant-ngp/src/testbed.cu(1644): error: identifier "GLFW_OPENGL_FORWARD_COMPAT" is undefined

/content/instant-ngp/src/testbed.cu(1644): error: identifier "GL_TRUE" is undefined

/content/instant-ngp/src/testbed.cu(1644): error: identifier "glfwWindowHint" is undefined

/content/instant-ngp/src/testbed.cu(1645): error: identifier "GLFW_RESIZABLE" is undefined

/content/instant-ngp/src/testbed.cu(1646): error: identifier "GLFW_OPENGL_PROFILE" is undefined

/content/instant-ngp/src/testbed.cu(1646): error: identifier "GLFW_OPENGL_CORE_PROFILE" is undefined

/content/instant-ngp/src/testbed.cu(1647): error: identifier "GLFW_CENTER_CURSOR" is undefined

/content/instant-ngp/src/testbed.cu(1648): error: identifier "GLFW_DECORATED" is undefined

/content/instant-ngp/src/testbed.cu(1649): error: identifier "GLFW_SCALE_TO_MONITOR" is undefined

/content/instant-ngp/src/testbed.cu(1650): error: identifier "GLFW_TRANSPARENT_FRAMEBUFFER" is undefined

/content/instant-ngp/src/testbed.cu(1674): error: identifier "compile_shader" is undefined

/content/instant-ngp/src/testbed.cu(1677): error: identifier "m_glfw_window" is undefined

/content/instant-ngp/src/testbed.cu(1677): error: identifier "glfwCreateWindow" is undefined

/content/instant-ngp/src/testbed.cu(1678): error: identifier "glfwSetWindowPos" is undefined

/content/instant-ngp/src/testbed.cu(1679): error: identifier "glfwMakeContextCurrent" is undefined

/content/instant-ngp/src/testbed.cu(1680): error: identifier "glCreateProgram" is undefined

/content/instant-ngp/src/testbed.cu(1681): error: identifier "glAttachShader" is undefined

/content/instant-ngp/src/testbed.cu(1683): error: identifier "glLinkProgram" is undefined

/content/instant-ngp/src/testbed.cu(1684): error: identifier "check_shader" is undefined

/content/instant-ngp/src/testbed.cu(1685): error: identifier "glDeleteProgram" is undefined

/content/instant-ngp/src/testbed.cu(1689): error: identifier "glGenVertexArrays" is undefined

/content/instant-ngp/src/testbed.cu(1690): error: identifier "glGenBuffers" is undefined

/content/instant-ngp/src/testbed.cu(1691): error: identifier "glBindVertexArray" is undefined

/content/instant-ngp/src/testbed.cu(1699): error: identifier "GL_ARRAY_BUFFER" is undefined

/content/instant-ngp/src/testbed.cu(1699): error: identifier "glBindBuffer" is undefined

/content/instant-ngp/src/testbed.cu(1700): error: identifier "GL_STATIC_DRAW" is undefined

/content/instant-ngp/src/testbed.cu(1700): error: identifier "glBufferData" is undefined

/content/instant-ngp/src/testbed.cu(1701): error: identifier "GL_FLOAT" is undefined

/content/instant-ngp/src/testbed.cu(1701): error: identifier "GL_FALSE" is undefined

/content/instant-ngp/src/testbed.cu(1701): error: identifier "glVertexAttribPointer" is undefined

/content/instant-ngp/src/testbed.cu(1702): error: identifier "glEnableVertexAttribArray" is undefined

/content/instant-ngp/dependencies/eigen/Eigen/src/Geometry/AngleAxis.h(178): warning: calling a __host__ function from a __host__ __device__ function is not allowed
          detected during:
            instantiation of "Eigen::AngleAxis<Scalar_> &Eigen::AngleAxis<Scalar_>::operator=(const Eigen::QuaternionBase<QuatDerived> &) [with Scalar_=float, QuatDerived=Eigen::Quaternion<float, 0>]" 
(213): here
            instantiation of "Eigen::AngleAxis<Scalar_> &Eigen::AngleAxis<Scalar_>::fromRotationMatrix(const Eigen::MatrixBase<Derived> &) [with Scalar_=float, Derived=Eigen::Matrix<float, 3, 3, 0, 3, 3>]" 
/content/instant-ngp/include/neural-graphics-primitives/adam_optimizer.h(123): here

33 errors detected in the compilation of "/content/instant-ngp/src/testbed.cu".
CMakeFiles/ngp.dir/build.make:145: recipe for target 'CMakeFiles/ngp.dir/src/testbed.cu.o' failed
make[2]: *** [CMakeFiles/ngp.dir/src/testbed.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:121: recipe for target 'CMakeFiles/ngp.dir/all' failed
make[1]: *** [CMakeFiles/ngp.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

Here is the full build output.
[instant_ngp.log](https://github.com/NVlabs/instant-ngp/files/9027140/instant_ngp.log)

**Comment by janeadams** [comment]
I have the same issue; tested on a T4 and a P100

**Comment by janeadams** [comment]
So `instant-ngp/src/testbed.cu(1640)` references `[<neural-graphics-primitives/testbed.h>](https://github.com/NVlabs/instant-ngp/blob/master/include/neural-graphics-primitives/testbed.h)` which defines `create_second_window()` at line 480. I'm wondering if maybe it has something to do with `#ifdef NGP_GUI` on line 471 in testbed.h -- basically, Colab doesn't support the GUI, so we shouldn't be installing anything GUI-related, if I understand correctly. So we'd want to skip that part of the build somehow.

**Comment by Tom94** [comment]
Should be fixed on latest `master`. Thanks for reporting!
