### ISSUE TITLE
Error with "cmake --build build --config RelWithDebInfo -j 16" related to Optix

### ISSUE THREAD

**Issue by FilipeF12** [NVlabs/instant-ngp#74]
![error1](https://user-images.githubusercontent.com/86638612/150570399-d3e05834-af4b-4971-8eef-231390841e62.gif)
![error2](https://user-images.githubusercontent.com/86638612/150570411-b71deafc-afb9-42f7-9ae2-0397cfe3ffef.gif)

**Comment by Tom94** [comment]
Unfortunately, these errors look rather generic to me -- no immediate ideas about what is causing them. A general thing, if you haven't tried it already, is to update CUDA to the latest version you can find. Sometimes, the latest compiler does not work with older versions of CUDA, and vice versa.

Also, could you remove the build folder, generate it again, and post CMake's log from said generation? That log might contain more clues.

**Comment by FilipeF12** [comment]
Good advice Tom.

I found CUDA 11.6. After installing that a popup alerted that NVIDIA NSight had an update, so I did that too.

The last change I made was to add an environment variable. Not sure if that was necessary.

   LD_LIBRARY_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\lib\x64

Both cmakes ran without error.

**Comment by Tom94** [comment]
Amazing, glad to hear that!
