### ISSUE TITLE
cmake . -B build on Windows Objects of target "glfw_objects" referenced but no such target exists.

### ISSUE THREAD

**Issue by dpyneo** [NVlabs/instant-ngp#75]
Windows10
CUDA 11.6
TITAN RTX
cmake 3.22.1
VS2022

Microsoft Windows [版本 10.0.17134.984]
(c) 2018 Microsoft Corporation。保留所有权利。

C:\Windows\system32>d:

D:\>cd instant-ngp-master

D:\instant-ngp-master>cmake . -B build
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.17134.
-- The C compiler identification is MSVC 19.30.30709.0
-- The CXX compiler identification is MSVC 19.30.30709.0
-- The CUDA compiler identification is NVIDIA 11.6.55
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.6/bin/nvcc.exe - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Including Win32 support
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- !!! Warning OptiX_INSTALL_DIR not set in environment. using default
-- OptiX_INSTALL_DIR value: C:\ProgramData\NVIDIA Corporation\OptiX SDK 7.3.0
-- OptiX headers (optix.h and friends) not found.
CMake Warning at CMakeLists.txt:169 (message):
  OptiX was not found.  Neural graphics primitives will still compile and run
  correctly.  However, SDF training in 'raystab' and 'pathescape' modes will
  be significantly slower.

-- Found Python: C:/Users/admin/Anaconda3/python.exe (found suitable version "3.7.4", minimum required is "3.7") found components: Interpreter Development Development.Module Development.Embed
-- pybind11 v2.9.0
-- Performing Test HAS_MSVC_GL_LTCG
-- Performing Test HAS_MSVC_GL_LTCG - Success
-- Targeting GPU architectures: 75
-- Configuring done
CMake Error at CMakeLists.txt:278 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_OBJECTS:glfw_objects>

  Objects of target "glfw_objects" referenced but no such target exists.

CMake Error at CMakeLists.txt:278 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_OBJECTS:glfw_objects>

  Objects of target "glfw_objects" referenced but no such target exists.

CMake Error at CMakeLists.txt:278 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_OBJECTS:glfw_objects>

  Objects of target "glfw_objects" referenced but no such target exists.

CMake Error at CMakeLists.txt:278 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_OBJECTS:glfw_objects>

  Objects of target "glfw_objects" referenced but no such target exists.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_OBJECTS:glfw_objects>

  Objects of target "glfw_objects" referenced but no such target exists.

CMake Error at CMakeLists.txt:278 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_OBJECTS:glfw_objects>

  Objects of target "glfw_objects" referenced but no such target exists.

CMake Error at CMakeLists.txt:278 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_OBJECTS:glfw_objects>

  Objects of target "glfw_objects" referenced but no such target exists.

CMake Error at CMakeLists.txt:278 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_OBJECTS:glfw_objects>

  Objects of target "glfw_objects" referenced but no such target exists.

CMake Error at CMakeLists.txt:278 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_OBJECTS:glfw_objects>

  Objects of target "glfw_objects" referenced but no such target exists.

CMake Error at CMakeLists.txt:278 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_OBJECTS:glfw_objects>

  Objects of target "glfw_objects" referenced but no such target exists.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_OBJECTS:glfw_objects>

  Objects of target "glfw_objects" referenced but no such target exists.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_OBJECTS:glfw_objects>

  Objects of target "glfw_objects" referenced but no such target exists.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_OBJECTS:glfw_objects>

  Objects of target "glfw_objects" referenced but no such target exists.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_OBJECTS:glfw_objects>

  Objects of target "glfw_objects" referenced but no such target exists.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_OBJECTS:glfw_objects>

  Objects of target "glfw_objects" referenced but no such target exists.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_OBJECTS:glfw_objects>

  Objects of target "glfw_objects" referenced but no such target exists.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_OBJECTS:glfw_objects>

  Objects of target "glfw_objects" referenced but no such target exists.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by Immortal00ZJ** [comment]
Don't download the zip.Use cmd.exe and copy 'git clone --recursive https://github.com/nvlabs/instant-ngp'
