### ISSUE TITLE
Save Mesh Feature Fails with Illegal Memory Access

### ISSUE THREAD

**Issue by GitUser520** [NVlabs/instant-ngp#751]
I'm having trouble with running the --save_mesh feature in /scripts/run.py.

When I run the following command, I get these errors about illegal memory access. Is this due to GPU ram being too small? Right now I am running on a 4GB GPU.

Command:
`python ./scripts/run.py --scene fox --n_steps 50 --save_mesh fox.obj`

Error: 
> Generating mesh via marching cubes and saving to fox.obj. Resolution=[256,256,256]
> Could not free memory: C:\Users\user\Documents\instant-ngp\dependencies\tiny-cuda-nn\include\tiny-cuda-nn/gpu_memory.h:129 cudaFree(rawptr) failed with error an illegal memory access was encountered
> Could not free memory: C:\Users\user\Documents\instant-ngp\dependencies\tiny-cuda-nn\include\tiny-cuda-nn/gpu_memory.h:129 cudaFree(rawptr) failed with error an illegal memory access was encountered
> Traceback (most recent call last):
>   File "C:\Users\user\Documents\instant-ngp\scripts\run.py", line 313, in <module>
>     testbed.compute_and_save_marching_cubes_mesh(args.save_mesh, [res, res, res])
> RuntimeError: Could not copy to host: C:\Users\user\Documents\instant-ngp\dependencies\tiny-cuda-nn\include\tiny-cuda-nn/gpu_memory.h:285 cudaMemcpy(host_data, data(), num_elements * sizeof(T), cudaMemcpyDeviceToHost) failed with error an illegal memory access was encountered
> Could not free memory: C:\Users\user\Documents\instant-ngp\dependencies\tiny-cuda-nn\include\tiny-cuda-nn/gpu_memory.h:129 cudaFree(rawptr) failed with error an illegal memory access was encountered

Specifications:
Processor: Intel (R) Core (TM) i7-7700K CPU @4.20GHz (8 CPUs)
Graphics Card: NVIDIA GeForce GTX 1080 (4GB RAM)

**Comment by StillSpeedo** [comment]
Same error with RTX 3060 (12 GB RAM).

**Comment by Tom94** [comment]
Should be fixed on latest master. Thanks for reporting!

**Comment by a-sharifi** [comment]
@Tom94 Same issue 

when will this feature be fixed?

**Comment by GitUser520** [comment]
It was fixed when I last tried it, so 20 days ago.
