### ISSUE TITLE
ERROR    Uncaught exception: Could not copy to host: /home/dsj/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:285 cudaMemcpy(host_data, data(), num_elements * sizeof(T), cudaMemcpyDeviceToHost) failed with error an illegal memory access was encountered Could not free memory: /home/dsj/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:454 cudaDeviceSynchronize() failed with error an illegal memory access was encountered

### ISSUE THREAD

**Issue by xiaoxiaolu1111** [NVlabs/instant-ngp#754]
ERROR    Uncaught exception: Could not copy to host: /home/dsj/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:285 cudaMemcpy(host_data, data(), num_elements * sizeof(T), cudaMemcpyDeviceToHost) failed with error an illegal memory access was encountered
Could not free memory: /home/dsj/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:454 cudaDeviceSynchronize() failed with error an illegal memory access was encountered

**Comment by JasperAlgra** [comment]
@xiaoxiaolu1111 I have the same error. Did you find out why?

**Comment by calmelo** [comment]
> ERROR Uncaught exception: Could not copy to host: /home/dsj/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:285 cudaMemcpy(host_data, data(), num_elements * sizeof(T), cudaMemcpyDeviceToHost) failed with error an illegal memory access was encountered Could not free memory: /home/dsj/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/gpu_memory.h:454 cudaDeviceSynchronize() failed with error an illegal memory access was encountered

I have the same error. How did you resolve it?
