### ISSUE TITLE
I got a problem when I used my own dataset

### ISSUE THREAD

**Issue by BUILDERlym** [NVlabs/instant-ngp#77]
after doing so
![image](https://user-images.githubusercontent.com/71302160/150645565-d2f8343d-a1d2-4dc9-a133-dfe720ad2e2e.png)
problems are here
![image](https://user-images.githubusercontent.com/71302160/150645536-af25d407-f1a0-4d73-8c27-a290cf23e5b4.png)
anyone can help me pls

**Comment by Tom94** [comment]
Hi there, this seems to be a problem over at COLMAP and not with our portion of the code. I recommend asking for help there, providing the CLI argument that `colmap2nerf` generated. All the best!
