### ISSUE TITLE
Holey SDF on flat outermost surfaces

### ISSUE THREAD

**Issue by StillSpeedo** [NVlabs/instant-ngp#775]
I decided to create a separate issue for the problem mentioned in https://github.com/NVlabs/instant-ngp/issues/768.

You can see that after fix the highlighted part of the model is saved in the mesh, but still full of holes.
![energy_fixed](https://user-images.githubusercontent.com/60139001/178766454-811a65e5-acea-4748-ae9e-40623e7585d4.png)

Other examples. You can see that only outermost flat surfaces are affected.
![baldor_holes](https://user-images.githubusercontent.com/60139001/178767160-855173a9-d531-4fc5-9bcf-88ed92f6342a.png)
![aero_holes](https://user-images.githubusercontent.com/60139001/178768712-c9611039-353a-415a-a7b4-f769ae54b411.png)

I thought it is a problem with my models exported from CAD, but I downloaded [this free model of cube](https://free3d.com/3d-model/abstract-chairconcave-cube-v1--456640.html) and got the same problem:
![cube_holes](https://user-images.githubusercontent.com/60139001/178769351-82231972-1dbc-4862-804f-893f54447b64.png)

Again, my hypothesis is that there is some bounding box for raytracing and it is too tight. 

Thanks in advance!

**Comment by Tom94** [comment]
Thanks for reporting this one! Fixed by https://github.com/NVlabs/instant-ngp/commit/60a992eb008953b0047bf017ec3b1c047fbb5cec
