### ISSUE TITLE
Is it possible to export mesh from NGLOD SDF?

### ISSUE THREAD

**Issue by StillSpeedo** [NVlabs/instant-ngp#776]
Hi!

When using config _takiwawa.json_ and trying to build mesh, I got strange results.

Here is rendered SDF, and it is ok:

![takiwawa_sdf](https://user-images.githubusercontent.com/60139001/178771114-1c14c6bd-bd6c-490e-b7fc-729def589799.PNG)

Mesh:

![takiwawa_mesh](https://user-images.githubusercontent.com/60139001/178770883-0c0835e4-5369-4490-8131-7620e82c73ac.PNG)

Mesh for same object, but using _hashgrid.json_:

![ingp_mesh](https://user-images.githubusercontent.com/60139001/178771076-68736ea5-93f4-447e-8162-c928c9709fe7.PNG)

I believe that's because NGLOD is only defined within the octree and wondering is it possible to export clear mesh? 
The question arises because NGLOD achieves better visual quality than I-NGP as mentioned in the paper and after all optimizations has comparable speed.

Thanks in advance!

**Comment by Tom94** [comment]
Hi there, unfortunately I don't see an obvious way to determine inside vs. outside for vertices that don't touch the triangle octree (as used in NGLOD) and so marching cubes (the mesh generation algorithm) will fail. For now, I've disabled the "Mesh it!" button if such an octree is used to prevent unexpected results like the one you've encountered: https://github.com/NVlabs/instant-ngp/commit/46a8cb0104725d3a8985a1aa5fa6f7bcf21d6fff

Good chance I'm missing an obvious tweak to marching cubes that'll make it work without snapping to the octree resolution -- please feel free to re-open the issue if there is one and I'll implement the corresponding fix.
