### ISSUE TITLE
Neat Demo Video Location

### ISSUE THREAD

**Issue by rhuts** [NVlabs/instant-ngp#780]
Does anyone know where to find that epic little edit of a woman walking down a sidewalk and then freezing mid pose as if it's the mannequin challenge and then the camera goes wild because it's a nerfie?

I thought I saw it on the 2MinutePapers YouTube channel but I cannot find it anymore.

Anyone have the link?

**Comment by JamesPerlman** [comment]
haha that was mine with Karen X! 

https://www.instagram.com/p/Cfb32WDJYen/
https://twitter.com/karenxcheng/status/1544718308535980032

**Comment by rhuts** [comment]
that's the one! Thank you 😃
