### ISSUE TITLE
CMake Error at CMakeLists.txt:11

### ISSUE THREAD

**Issue by mdsonnenberg** [NVlabs/instant-ngp#781]
Hi there, I'm seeing the following issues when I attempt to build the project using CMake. I appreciate any insight:

C:\Users\mdson\Documents\GitHub\instant-ngp>cmake . -B build
-- Building for: NMake Makefiles
CMake Error at CMakeLists.txt:11 (project):
  Running

   'nmake' '-?'

  failed with:

   The system cannot find the file specified

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CUDA_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/Users/mdson/Documents/GitHub/instant-ngp/build/CMakeFiles/CMakeOutput.log".

**Comment by psakamoori** [comment]
Try below (with your install paths)

export PATH="/usr/local/cuda-11.0/bin:$PATH"
export LD_LIBRARY_PATH="/usr/local/cuda-11.0/lib64"
export CUDACXX="/usr/local/cuda-11.0/bin/nvcc"
export OptiX_INSTALL_DIR="/home/username/Downloads/NVIDIA-OptiX-SDK-7.5.0-linux64-x86_64"

**Comment by camoy4to** [comment]
tried to add those variables to PATH, that doesn't solve an issue 
looks like Cmake cant find a C compiler, which path should be specified exactly?
https://stackoverflow.com/questions/70524164/cmake-c-compiler-not-set-after-enablelanguage

**Comment by psakamoori** [comment]
I am trying it on Ubuntu 20.04...So, did not encountered this...

**Comment by mdsonnenberg** [comment]
@psakamoori I updated my path in a manner similar to what you described and I was able to get over that issue. Now I'm running into a different issue :D
