### ISSUE TITLE
The DISPLAY environment variable is missing

### ISSUE THREAD

**Issue by resurgo97** [NVlabs/instant-ngp#80]
After the build successfully done, I want to display a fox being rendered by NeRF.
However, I got a problem as below.
![image](https://user-images.githubusercontent.com/37990297/150875497-813650bc-3399-46f8-953a-2a78961554ca.png)

Actually I am working on a remote server which lacks a displaying device.
Is it then impossible to display it on my (local) computer?
If not, is there any method to at least train it without GUI?

Thanks,

**Comment by neilgogogo** [comment]
You could probably try X-11 forwarding together with MobaXterm, or run the sripts/run.py and set no_gui
![image](https://user-images.githubusercontent.com/53148705/150929876-78e8d7c7-42fc-41b0-8782-90819c756f50.png)

**Comment by resurgo97** [comment]
Solved! thx :)

**Comment by 1LOVESJohnny** [comment]
Hi @neilgogogo, thanks a lot for your help! This problem can straightly solved by --no_gui. 
But I still wonder about X-11, could you please give a simple guide of how I can set X-11 server along with mobaxterm?
