### ISSUE TITLE
colmap problem without gui 

### ISSUE THREAD

**Issue by 1kaiser** [NVlabs/instant-ngp#805]
warning! folders 'colmap_sparse' and 'colmap_text' will be deleted/replaced. continue? (Y/n)y
==== running: colmap feature_extractor --ImageReader.camera_model OPENCV --ImageReader.camera_params "" --SiftExtraction.estimate_affine_shape=true --SiftExtraction.domain_size_pooling=true --ImageReader.single_camera 1 --database_path colmap.db --image_path "images"
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
FATAL: command failed

**Comment by Tom94** [comment]
Hi, this is a problem with COLMAP and should be reported over at their repository: https://github.com/colmap/colmap
