### ISSUE TITLE
what does a,b,c mean in the triangle.cuh

### ISSUE THREAD

**Issue by neilgogogo** [NVlabs/instant-ngp#81]
`return factor0 * a + factor1 * b + factor2 * c`
Sorry, I'm not very familiar with c++, I want to know what a,b,c refer to, I don't see the corresponding declaration of a,b,c

https://github.com/NVlabs/instant-ngp/blob/12018ab9c85b5caade12de87188330b1a5dcc862/include/neural-graphics-primitives/triangle.cuh#L32

**Comment by Tom94** [comment]
Hi there, the member variables a, b, c are defined at the [bottom of the struct](https://github.com/NVlabs/instant-ngp/blob/12018ab9c85b5caade12de87188330b1a5dcc862/include/neural-graphics-primitives/triangle.cuh#L171) and refer to the vertices of the triangle.
