### ISSUE TITLE
Detail: Depth of Field in GUI is reversed or should be called Aperture

### ISSUE THREAD

**Issue by nosy-b** [NVlabs/instant-ngp#819]
First I would like to congratulate: This work is amazing thank you so much!! :) 

Just a tiny remark for the Depth Of Field (DoF) Slider in the GUI. It should actually goes in the opposite direction, the bigger the DoF, the sharper out of focus.
Or you can just rename it Aperture?

Thank you!

**Comment by Tom94** [comment]
Thanks for pointing this out! In the interest of not breaking backward compatibility, I'll simply rename the parameter and leave existing bindings using the wrong terminology in place.
