### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by zh-en520** [NVlabs/instant-ngp#830]
windows10
cmake=3.24.0
Optix=7.5.0
vulkan=1.3.216.0
VS=2019

when ">cmake . -B build",result-->
1-- Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR) (found version "")
CMake Warning at CMakeLists.txt:118 (message):
  Vulkan was not found.  Neural graphics primitives will still compile and
  run correctly, but DLSS will not be supported.

2-- !!! Warning OptiX_INSTALL_DIR not set in environment. using default
-- OptiX_INSTALL_DIR value: C:\ProgramData\NVIDIA Corporation\OptiX SDK 7.5.0

![image](https://user-images.githubusercontent.com/51226297/181684647-bcd90fd0-49ff-4de1-a105-de432bdadcd9.png)
![image](https://user-images.githubusercontent.com/51226297/181684897-0f077e7c-a317-439a-958b-afddae023f5f.png)

Why?

**Comment by cyz2727327** [comment]
Hi @zh-en520 , did you find a way to fix this problem? I have the same issue, thank you !

**Comment by zh-en520** [comment]
reboot！
