### ISSUE TITLE
Density derivative questions

### ISSUE THREAD

**Issue by chanket** [NVlabs/instant-ngp#838]
As can be seen in
https://github.com/NVlabs/instant-ngp/blob/e7631da9fca9d0f3467f826fccd7a5849b3f6309/src/testbed_nerf.cu#L1513
the density derivative is calculated by
```
float dloss_by_dmlp = density_derivative * (
	dt * (lg.gradient.matrix().dot((T * rgb - suffix).matrix()) + depth_supervision)
);
```

Maybe I'm wrong, but I have 2 questions about that:

1. Regardless of `depth_supervision`, I think `dloss_by_dmlp` here is calcualted by `ddensity_by_dmlp` dots `dalpha_by_ddensity` dots `dloss_by_dalpha`, where `ddensity_by_dmlp` is `density_derivative`, the part `lg.gradient.matrix().dot((T * rgb - suffix).matrix())` is `dloss_by_dalpha`. But I'm confused by the remaining `dt`, which doesn't seem to be `dalpha_by_ddensity`, see https://github.com/NVlabs/instant-ngp/blob/master/src/testbed_nerf.cu#L1491
2. It is clear that `lg.gradient` is `dloss_by_drgb`, but how does the part `T * rgb - suffix` represent `drgb_by_dalpha`? I understand that the current color component is calculated by `alpha * T * rgb`, which produces a derivative `T * rgb`, but as can be seen in https://github.com/NVlabs/instant-ngp/blob/master/src/testbed_nerf.cu#L1495 , the `T` is multiplied by `(1.f - alpha)` halfway, is that by design?

**Comment by chanket** [comment]
I found the answer: my 2 questions should not be considered separately. 

The original form is 

```
float dloss_by_dmlp = density_derivative * (
	(1.f - alpha) * dt * lg.gradient.matrix().dot((T / (1.f - alpha) * rgb - suffix / (1.f - alpha)).matrix())
);
```
and `(1.f - alpha)` is removed for reduction.

**Comment by no-Seaweed** [comment]
Hi, I also have a trouble to derive those derivatives. First, for `dloss_by_drgb`, it should come from `dloss_by_drgb_ray * drgb_ray_by_drgb_ray2 * drgb_ray2_by_dmlp`, and `dloss_by_drgb_ray` could be obtained from lg.gradient and `drgb_ray2_by_dmlp` could be obtained from network_to_rgb_derivative. However, I am confused about the `drgb_ray_by_drgb_ray2` part, which should be d(alpha*Prod(1-alpha)/d(alpha2*Prod(1-alpha2)). The output from this derivative might be exactly the suffix, not the weight. What am I wrong here?

For the second line of derivation `dloss_by_dmlp`, following your chain rule, the whole process could be written as `ddensity_by_dmlp*dalpha_by_ddensity*dalpha_by_dcolor*dcolor_by_dloss`, where the first part can be expressed as density_derivative and the last part can be written as lg.gradient. For the rest two, I could not get anyway near to your original form. Would you mind elaborate more on the derivation? Looking forward to your reply.

Best,
S.F.

**Comment by coreqode** [comment]
Hi, @chanket @Tom94 
I was not able to understand the purpose of suffix here. What I understood till now is, it's the residual in the rendered pixel value before pruning and after pruning.

**Comment by vincentcartillier** [comment]
I just had to go trough these equations as well. These "suffix" variables are introduced when we are computing the Jacobian $\frac{\partial L}{\partial MLP}$. Here's how I computed it:

$$\frac{\partial L}{ \partial \sigma^{mlp}_{i}} = \frac{\partial L}{ \partial \sigma_i} \times  \frac{\partial \sigma_i}{ \partial \sigma^{mlp}_i} = \left( \frac{\partial L_{RGB}}{ \partial \sigma_i}  +  \frac{\partial L_{D}}{ \partial \sigma_i} \right) \times  \frac{\partial \sigma_i}{ \partial \sigma^{mlp}_i}  $$

This equation is the partial derivative of the Loss given the $i^{th}$ MLP output density variable. We have $\frac{\partial \sigma_i}{ \partial \sigma^{mlp}_i}$ as the `density_derivative` in the code. 

I'll derive the equations for the depth loss $\frac{\partial L_{D}}{ \partial \sigma_i}$, but the idea is the same for RGB.


Let's define some variables:
$$D = \sum \alpha_i \times T_i \times d_i$$
with $\alpha_i = (1 - e^{-\sigma_i.\delta_t})$ and, $T_{i+1} = T_{i} \times (1 - \alpha_i) $.
Then we have:

$$
\frac{\partial L_{D}}{ \partial \sigma_i} = \frac{\partial L_{D}}{ \partial D} \times \frac{\partial D}{ \partial \sigma_i} 
$$

With $\frac{\partial L_{D}}{ \partial D}$ equal to `depth_loss_gradient` in the code. And

$$
\begin{align}
\frac{\partial D}{ \partial \sigma_i} &= \frac{\partial (\alpha_i T_i d_i)}{ \partial \sigma_i} + \sum_{j=i+1}\frac{\partial (\alpha_j T_j d_j)}{ \partial \sigma_i}  \\
 &= \frac{\partial (\alpha_i T_i d_i)}{ \partial \alpha_i} \times \frac{\partial \alpha_i }{ \partial \sigma_i} + \sum_{j=i+1} \alpha_j d_j \frac{\partial T_j }{ \partial \alpha_i} \times \frac{\partial \alpha_i}{ \partial \sigma_i}\\
 &=  T_i d_i \times \frac{\partial \alpha_i }{ \partial \sigma_i} + \sum_{j=i+1} \alpha_j d_j \frac{\partial T_j }{ \partial \alpha_i} \times \frac{\partial \alpha_i}{ \partial \sigma_i}
\end{align}
$$

to compute $\frac{\partial T_j }{ \partial \alpha_i}$ you can notice that:

$$
\begin{align}
\frac{\partial T_{i+1} }{ \partial \alpha_i} &= -T_i\\
\frac{\partial T_{i+2} }{ \partial \alpha_i} &= -T_i(1 - \alpha_{i+1})\\
\frac{\partial T_{i+3} }{ \partial \alpha_i} &= -T_i(1 - \alpha_{i+1})(1 - \alpha_{i+2})\\
& ...
\end{align}
$$

And thus, 

$$
\begin{align}
\frac{\partial T_{j}}{ \partial \alpha_i} &= -T_i \frac{T_j}{T_{i+1}}\\
 &= - \frac{T_j}{(1 - \alpha_{i})}
\end{align}
$$

Plugin this back into our equations, we have:

$$
\begin{align}
\frac{\partial D}{ \partial \sigma_i} &=  T_i d_i \times \frac{\partial \alpha_i }{ \partial \sigma_i} - \sum_{j=i+1} \alpha_j d_j \frac{T_j }{ (1- \alpha_i)} \times \frac{\partial \alpha_i}{ \partial \sigma_i}\\
 &= T_i d_i \delta_t e^{-\sigma_i \delta_t} - \sum_{j=i+1} \alpha_j d_j \frac{T_j }{ (1- \alpha_i)} \delta_t e^{-\sigma_i \delta_t} 
\end{align}
$$

Now you can notice that $e^{-\sigma_i \delta_t} = 1 - \alpha_i $.

$$
\begin{align}
\frac{\partial D}{ \partial \sigma_i} &= T_i d_i \delta_t (1-\alpha_i) - \sum_{j=i+1} \alpha_j d_j \frac{T_j }{ (1- \alpha_i)} \delta_t (1-\alpha_i)\\
 &= T_{i+1} d_i \delta_t - \sum_{j=i+1} \alpha_j d_j T_j  \delta_t \\
 &= \delta_t ( T_{i+1} d_i  - \sum_{j=i+1} \alpha_j d_j T_j ) \\ 
&= \delta_t ( T_{i+1} d_i  - (\sum_{j=1}^N \alpha_j d_j T_j  -   \sum_{j=1}^{i} \alpha_j d_j T_j) ) \\ 
&= \delta_t ( T_{i+1} d_i  - ( depth  -   depth_2 )) \\ 
&= \delta_t ( T_{i+1} d_i  -  depth_{suffix} ) \\ 
\end{align}
$$
