### ISSUE TITLE
Have the near distance be configurable in the transforms.json.

### ISSUE THREAD

**Issue by mcourteaux** [NVlabs/instant-ngp#84]
Now, for my wide-angle datasets, I need to every time adjust the slider to decrease the near distance in order for it to properly learn. As this is a dataset-specific property, it would make sense to have it be a property in the `transforms.json`.

**Comment by Tom94** [comment]
While adding more parameters to `transforms.json` is certainly an option, the Python bindings exist precisely to help automate these sorts of case-specific things away.

For example, if you're running the program via `scripts/run.py` (which I strongly recommend over the testbed binary if you're running actual experiments), you can add the line
```python
testbed.nerf.training.near_distance = 0.0
```

Granted, the near distance didn't have a Python binding until now; I quickly added one for your use case. pybind11 makes this fairly simple -- it's a one-liner; see https://github.com/NVlabs/instant-ngp/commit/e7d1e4047256585137491a365f4c1b44583c44ed -- which allows wiring up plenty of other behaviors fairly easily.

**Comment by mcourteaux** [comment]
Aha, I didn't come across the run.py yet. Thanks for the quick reply. This indeed is useful for academic purposes.
