### ISSUE TITLE
Explain number of weights in snapshot

### ISSUE THREAD

**Issue by sthfaceless** [NVlabs/instant-ngp#845]
I ran the run.py script with the settings from base.json for nerf dataset, during training the model used Cutlass MLP according to the logs, then I saved the model in a snapshot file.

The following code loads binary weights into float16 and I am interested in the resulting numbers

    import msgpack
    import numpy as np

    with open('worktable/worktable.msgpack', 'rb') as f:
        data = msgpack.loads(f.read())

    density_grid = np.frombuffer(data['snapshot']['density_grid_binary'], dtype=np.float16)
    params = np.frombuffer(data['snapshot']['params_binary'], dtype=np.float16)

    print(density_grid.shape) # <--- 6291456
    print(params.shape) # <--- 13084640

The first number is 128^3*3, as I understand it, it should be just one 128^3 density grid, but why are there 3 of them?

The second number does not have a beautiful representation, perhaps this is due to the Cutlass MLP paddings, but as I understand it, there should be at least among these parameters 2^19 * 16 * 2 for a hash grid, but this number is already larger than the resulting one, then I don't quite understand what these weights are

Could someone clarify the situation with how the weights of the model are arranged in the resulting matrix?

**Comment by sthfaceless** [comment]
Ok, what about second number.

 As I guess it can be very wasteful to store a complete table for small grids, i.e. 4 layers that do not exceed the size of the hash table 2^19, in this case, with an expansion coefficient b = 1.51572, according to the following formula, I get approximately the required number 

`((16)^3 + (16*1.51572^1)^3 + (16*1.51572^2)^3 + (16*1.51572^3)^3 + 12 * 2^19) * 2 = 13064873.9`

**Comment by sthfaceless** [comment]
I'm still pretty confused with first number which 128^3 * 3

**Comment by Tom94** [comment]
Hi there. For the first number: there are multiple 128^3 occupancy grids, each scaled twice as large as the previous -- this is to capture the multi-scale aspect of scenes with a central object of importance and further-and-further away background detail. More details are in the appendix of the paper.

Regarding the second number: you can query the exact number of parameters for a given `level` through the C++ API of `grid.h`. Within a `Testbed` member function, simply use
```
auto enc = dynamic_cast<GridEncoding<network_precision_t>*>(m_encoding.get());
uint32_t n_levels = enc->level_n_params(level);
```
