### ISSUE TITLE
build error in "cmake --build build --config RelWithDebInfo -j 16"

### ISSUE THREAD

**Issue by BUILDERlym** [NVlabs/instant-ngp#86]
![image](https://user-images.githubusercontent.com/71302160/151006452-47401e10-397c-4afc-bcae-1552bb07fedb.png)
anyone knows how to solve this? looks like lots of errors
thanks in advance
let me know if u need more detail

**Comment by bycloudai** [comment]
CUDA 11.6 + python 3.9 + latest VS19 fixed this for me

**Comment by Tom94** [comment]
I see you've posted results of successfully running the codebase in another issue. I'm going to close this one, but feel free to re-open it if the above is still problematic.
