### ISSUE TITLE
noob question: how to export a video of the model?

### ISSUE THREAD

**Issue by sunhoro** [NVlabs/instant-ngp#870]
Just wondering how others create fancy videos from the model.
I've seen 360-degree revolving videos or like a drone flight simulator as well.
Do I have to export the mesh model and record the video separately, or is there a feature within the GUI?

**Comment by barney2074** [comment]
It's not very well documented- but you:
1. Create the path using the gui & save it
2. Optionally train the model and save a snapshot
3. Generate the video using run.py
Something like:
`python3 scripts/run.py --scene=data/nerf/fox --mode=nerf --load_snapshot=data/fox.msgpack --video_camera_path=data/nerf/fox/my_foxy_camera_path.json --video_output=data/nerf/fox/my_foxy_video.mp4`

Takes a look at run.py in a text editor for all the arguments

**Comment by TanOneDeg** [comment]
How do you control the 'speed' of the video using the export video tab inside instant-ngp v1.0dev GUI?

**Comment by barney2074** [comment]
take a look at --video_fps and --video_n_seconds arguments to run.py

changing --video_n_seconds to a bigger number will make the video longer (and slower by effectively stretching across a longer time)

**Comment by TanOneDeg** [comment]
Thanks, that did the trick.
