### ISSUE TITLE
Vulkan on Ubuntu 22.04 ?

### ISSUE THREAD

**Issue by barney2074** [NVlabs/instant-ngp#872]
I'm not familiar with Vulkan- but has anyone managed to get Vulkan SDK running with instant-ngp on Ubuntu 22.04 ?

On the Vulkan website- there are only packages for Ubuntu 18.04 and 22.04
I've tried the tarball option- the installation script seems to work ok, but instant-ngp does not find it
https://vulkan.lunarg.com/sdk/home#linux

I'm assuming that DLSS improves the render quality- is this correct ??

Andrew

**Comment by barney2074** [comment]
I've tinkered around with it some more- I think Vulkan is working ok- refer attached Vulkan info file (not quite sure what I should be looking for)

I now get the below error message

`WARNING  Could not initialize Vulkan and NGX. DLSS not supported. (/home/ub/instant-ngp/src/dlss.cu:220 vkCreateInstance(&instance_create_info, nullptr, &vk_instance) failed)`

[vulkaninfo.txt](https://github.com/NVlabs/instant-ngp/files/9314063/vulkaninfo.txt)



Andrew
Andrew

**Comment by barney2074** [comment]
I ended up building a fresh 20.04 system & it works fine

Andrew

**Comment by belkahorry** [comment]
Could you please tell me which ver of vulkan sdk you've installed? and wether you used apt or script to install it?
I've reinstalled vulkan and optix several times but still got 

`Could not initialize Vulkan and NGX. DLSS not supported. (/home/XXX/Nerf/instant-ngp/src/dlss.cu:392 NVSDK_NGX_VULKAN_Init_with_ProjectID("ea75345e-5a42-4037-a5c9-59bf94dee157", NVSDK_NGX_ENGINE_TYPE_CUSTOM, "1.0.0", path.c_str(), vk_instance, vk_physical_device, vk_device) failed with error NVSDK_NGX_Result_FAIL_OutOfDate)`

my env:
ubuntu 20.04
vulkan sdk 1.3.216
optix 7.5.0

**Comment by barney2074** [comment]
that machine is in my office- I won't be there for a few days, but will check when I get back
From memory- I used the tarball installer (script)

There is also a `vulkaninfo` utility that I used to check it was working


Andrew

**Comment by belkahorry** [comment]
Thanks for quick reply, i finally solved it by updating gpu driver to 510.x. Optix7.5 required 495.+ causes my issue
