### ISSUE TITLE
render video with crop ?

### ISSUE THREAD

**Issue by barney2074** [NVlabs/instant-ngp#873]
Hello

I'm not sure if I'm missing something obvious- but if I've cropped my model (using the gui), how do I render a video of this cropped model ?

i.e there are a lot of floaters (outside the crop) that I don't want to see in the video

Andrew

**Comment by scyheidekamp** [comment]
Did you find out how to do this? Because I'm facing the same problem. Would love to render the cropped version.

**Comment by barney2074** [comment]
Sorry, no, I didn't find an answer to this

Andrew

**Comment by cansik** [comment]
The `cropsize` slider controls the `render_aabb` bounding box. It is possible to directly adjust it by using the following method I have converted from C++ to python:

```python
def set_crop_size(testbed, crop_size):
	cen = testbed.render_aabb.center()
	diag = np.array([crop_size, crop_size, crop_size])
	bbox = ngp.BoundingBox(cen - diag * 0.5, cen + diag * 0.5)

	testbed.render_aabb.min = bbox.min
	testbed.render_aabb.max = bbox.max
```

**Comment by barney2074** [comment]
thanks @cansik 

It is a bit beyond my skills- but I'll have a go at modifying run.py with an argument for crop_size

Andrew

**Comment by cansik** [comment]
@barney2074 Have a look at my custom render script. I have also optimised the frame-writing part performance wise.
https://github.com/cansik/instant-ngp/blob/master/scripts/render.py

**Comment by barney2074** [comment]
thanks @cansik 

that looks great- I'll give it a try


Andrew

**Comment by Tom94** [comment]
Hi, snapshots will now retain the crop settings from the interactive session. That should make it much easier to render videos of cropped content (without resorting to scripting). Cheers!

**Comment by barney2074** [comment]
Hi @Tom94 

Many thanks for this- I try it out

Andrew

Andrew
