### ISSUE TITLE
Marching cubes mesh export vertex colors

### ISSUE THREAD

**Issue by useronym** [NVlabs/instant-ngp#88]
Just wondering, would it be possible to add color to the vertices of the generated mesh?

Also using a binary format for the exported meshes might be preferable, given the large amounts of data.

**Comment by mmalex** [comment]
this should already be supported in both obj and ply format.
not every program supports object colors in obj, but meshlab does, and ngp
should write them.

**Comment by useronym** [comment]
Ah! You are right, I kinda assumed that Blender supports vertex colors. Thanks!

**Comment by mmalex** [comment]
I dont know about their OBJ loader, but iirc PLY in blender *does*. you
have to set up a material explicitly in blender that routes the vertex
color attribute to the diffuse color of the BRDF - but it's definitely
do-able. If you google a bit you should find the ingredients you need from
a blender pov. good luck!

**Comment by fahimsun** [comment]
I am little confuse, when I use --save_mesh  and --mode nerf, i only get obj file. When i open it in blender and render i get no color. Usually blender needs .mtl file along with .obj file in order to get color. Can someone enlighten me, how can i get color or links or article would be appreciate. 
Also let me know if my understanding is correct that .obj file and .ply file output from nerf contains color, just that blender cannot open it?
Thanks for patients

**Comment by fahimsun** [comment]
Just to update, if someone looking for same answer. The Blender doesn't support obj file format with vertex color. Download meshlab and open the obj file.

**Comment by just-benedict-it** [comment]
@fahimsun Well, I have a quetions. I added "--save_mesh" while running scripts/run.py, but can't not get .obj file.(just txt file) 
Am I missing something??

**Comment by mmalex** [comment]
you should follow --save_mesh parameter to run.py, with an output filename.
file with extension .obj and .ply are supported.
both contain vertex colors, however I believe blender .obj loader does not
support vertex colors. (meshlab does).
I am not an expert in blender, but I have a memory that .ply loader there
*does* support vertex colors, but it is not obvious in blender how to
display the vertex colors. you should look online for a tutorial video,
there are several. the short version is that you must assign a custom
material to the object, and route the 'vertex color' attribte in blender to
the surface color of the material. but obviously this is out of the scope
of NGP.
I confirmed when writing the code that the vertex colors were there in both
formats using meshlab.

**Comment by just-benedict-it** [comment]
Ah, I should've added .obj after filename.
Thanks for your quick reply!! :)
