### ISSUE TITLE
Nerf training generated 0 samples. Aborting training.

### ISSUE THREAD

**Issue by dsvilarkovic** [NVlabs/instant-ngp#888]
I have two json files (with single sample, just to try overfitting), made with different camera poses.

When running the below json file with 
`python scripts/run.py --scene ../coffee_martini/transforms_test.json --mode nerf`

<code>
{"h": 2028.0, "w": 2704.0, "frames": [{"file_path": "test/img_00_0001.jpg", "transform_matrix": [[-0.9989335392387547, 0.03113043777825586, 0.034098094194097824, -0.035885617538716545], [-0.03222537675516253, -0.9989667269084529, -0.03204689724138391, 0.2874310869291453], [-0.033065227610334924, 0.033111544414994136, -0.9989045581783731, 0.10288549096180542], [0.0, 0.0, 0.0, 1.0]]}], "camera_angle_x": 1.4935054002830719}
</code>

It works properly.

Unlike that one, the one I have here is giving me warning:
`python scripts/run.py --scene ../coffee_martini_improper/transforms_test.json --mode nerf`

`Training:   0%|                                                                                                                                             | 0/10000 [00:00<?, ?step/s]20:05:43 WARNING  Nerf training generated 0 samples. Aborting training.`
after which script is not able to train model at all, with GUI or without it, it just stays in loop indefinitely on 0%. 

<code>
{"h": 2028.0, "w": 2704.0,"frames": [{"file_path": "test/img_00_0001.jpg", "transform_matrix": [[-0.03206645145707186, 0.9991140185790592, 0.02725656936431812, 0.36619836581765997], [0.9952674969687105, 0.03442205483554682, -0.09087206181515432, -0.43790138099298775], [0.09172977798203953, -0.02421363300817761, 0.9954895016079615, 3.8720546384941184], [0.0, 0.0, 0.0, 1.0]]}], "camera_angle_x": 1.4935054002830719}
</code>

I have checked, and both models have the same test file content (image is there and both are the same images).
What could be the problem?

**Comment by mcourteaux** [comment]
This happens if all your camera positions (in the transform json) yield rays that do not cross the training volume.

**Comment by dsvilarkovic** [comment]
I figured it out, thanks!

**Comment by gs14iitbbs** [comment]
> I figured it out, thanks!

What was the issue and how you resolved?

**Comment by mohit-choithwani** [comment]
@rudylyh Did you change the translation (by reducing the values) or just change the rotation angles to point towards the center.
