### ISSUE TITLE
Missing 'commentjson' When Rendering Video

### ISSUE THREAD

**Issue by jbb-kryo** [NVlabs/instant-ngp#889]
When the command:
`python3 scripts/run.py --mode nerf --scene data/nerf/fox --load_snapshot data/nerf/fox/base.msgpack --video_camera_path data/nerf/fox/base_cam.json --video_n_seconds 5 --video_fps 60 --width 1920 --height 1080`
it throws the following error:
`Traceback (most recent call last):
  File "G:\NeRF\instant-ngp\scripts\run.py", line 13, in <module>
    import commentjson as json
ModuleNotFoundError: No module named commentjson`
The problem is that I have already installed `commentjson` using `pip3` (`pip3 install commentjson`)

Any ideas?

**Comment by barney2074** [comment]
I don't think you should have to install Python packages individually
Did you run `pip install -r requirements.txt` ??

**Comment by jbb-kryo** [comment]
I had not run it initially. However I ran it and retried the commands, however I was met with the same results unfortunately. I already have my environment variables set. Do I have to add more?

- `pip3 install -r requirements.txt`
- `python3 scripts/run.py --mode nerf --scene data/nerf/fox --load_snapshot data/nerf/fox/base.msgpack --video_camera_path data/nerf/fox/base_cam.json --video_n_seconds 5 --video_fps 60 --width 1920 --height 1080`

**Comment by barney2074** [comment]
sounds like something is messed up

You could try creating a Python virtual environment, activating it, then install necessary packages with requirements.txt (and run.py within the environment) I've not tried this myself, but it should work

**Comment by jbb-kryo** [comment]
I am doing this on Windows 11. If anything it is going to be to do with environment variables I think.

**Comment by barney2074** [comment]
not sure if I agree with that
environment variables are for supplementary applications (like Optix)- it sounds like commentjson, or the correct version of commentjson is not installed
You can easily test it from a Python prompt
i.e` import commentjson`

**Comment by jbb-kryo** [comment]
Thanks. I tried that. It keeps throwing the error that the module cannot be found. Despite me installing via `requirements.txt`.

**Comment by jbb-kryo** [comment]
To fix the problem of missing `commentjson`, you can try the following:
- [Download and Install Anaconda](https://www.anaconda.com/products/distribution)
- Add `C:\ProgramData\Anaconda3\Scripts` and `C:\ProgramData\Anaconda3\Library\bin` to your Environment Variables/Path
- Reboot the computer
- Open Powershell as an Administrator
- `conda install -c conda-forge commentjson`
- Reboot the computer
- Problem solved
