### ISSUE TITLE
strange error occur in “cmake --build build --config RelWithDebInfo -j 16”

### ISSUE THREAD

**Issue by BUILDERlym** [NVlabs/instant-ngp#89]
![image](https://user-images.githubusercontent.com/71302160/151099290-78bc21a2-4bc4-4b7d-9c5f-14d77b4b348a.png)
I git all submodules, but it still cant be built correctly

**Comment by Yancy-lv** [comment]
Hello,how did you deal with this problem? The same happened to me too.
