### ISSUE TITLE
How depth_supervision_lambda change the Depth supervision strength?

### ISSUE THREAD

**Issue by licj15** [NVlabs/instant-ngp#900]
Dear Authors,

Thanks for the great codebase!
When I am [tracking how depth_supervision_lambda change the depth supervision strength](https://github.com/NVlabs/instant-ngp/search?q=depth_supervision_lambda), I found that it seems that [it is only used to turn on depth supervision when it > 0](https://github.com/NVlabs/instant-ngp/blob/b551bf13df7ea60d5c2e7bae02d9d54065e71883/src/testbed_nerf.cu#L1423).

I am expecting to see that such depth_supervision_lambda will be applied to the depth_supervision when adding with color supervision signal during the [back propagation](https://github.com/NVlabs/instant-ngp/blob/b551bf13df7ea60d5c2e7bae02d9d54065e71883/src/testbed_nerf.cu#L1509-L1514), but it seems that this does not happen.

So I was wondering whether you could help to point out how depth_supervision_lambda change the Depth supervision strength?

Thank you for your time and efforts!

**Comment by jc211** [comment]
You're right. 
```
float depth_loss_gradient = target_depth>0.0f ? lg_depth.gradient.x() : 0; 
```
should be 
```
float depth_loss_gradient = target_depth>0.0f ? depth_supervision_lambda*lg_depth.gradient.x() : 0; 
```

**Comment by Tom94** [comment]
Fixed due to @jc211's PR.
