### ISSUE TITLE
Rendering screenshots takes a very long time

### ISSUE THREAD

**Issue by Jentuuh** [NVlabs/instant-ngp#912]
Is it normal that rendering screenshots using the python binding (run.py) takes a very long time, even when the model is already trained? I'm rendering 2560x2048 screenshots and it takes over 2 minutes, I would expect a screenshot to be rendered in real-time once the model is trained.

**Comment by barney2074** [comment]
Yes, I think that is normal- at least the same for me

**Comment by jc211** [comment]
Your SPP is probably too high. Reduce to 1 to make it as fast as possible. (--screenshot_spp 1)
