### ISSUE TITLE
Cannot open include file: 'tiny-cuda-nn/random.h': No such file or directory

### ISSUE THREAD

**Issue by tyc-proprio** [NVlabs/instant-ngp#925]
Hello,

Looks like I got a dependency error after updating & rebuilding based on the latest version of repo:

```
\instant-ngp\include\neural-graphics-primitives/random_val.cuh(22): fatal error C1083: Cannot open include file: 'tin
y-cuda-nn/random.h': No such file or directory
```
Any suggestion about the error?

**Comment by tyc-proprio** [comment]
Never mind, I got repo built after building the repo from scratch.

**Comment by fubenzun** [comment]
I meet the same problem, how to solve it?
