### ISSUE TITLE
运行这个命令时docker-compose -f .devcontainer/docker-compose.yml build instant-ngp遇到错误    ERROR: The Compose file './.devcontainer/docker-compose.yml' is invalid because: services.instant-ngp.deploy.resources.reservations value 'devices' does not match any of the regexes: '^x-'

### ISSUE THREAD

**Issue by 582796566** [NVlabs/instant-ngp#929]
root@container-f51f1185ac-98923ed5:~/instant-ngp# docker-compose -f .devcontainer/docker-compose.yml build instant-ngp
WARNING: The DISPLAY variable is not set. Defaulting to a blank string.
ERROR: The Compose file './.devcontainer/docker-compose.yml' is invalid because:
services.instant-ngp.deploy.resources.reservations value 'devices' does not match any of the regexes: '^x-'

这是什么原因有人知道吗

**Comment by mathematicalmichael** [comment]
just ran into this myself.

upgrade docker-compose.. there was a big change in 1.28.0
https://docs.docker.com/compose/gpu-support/

**Comment by 582796566** [comment]
> just ran into this myself.
> 
> upgrade docker-compose.. there was a big change in 1.28.0 https://docs.docker.com/compose/gpu-support/

thanks for your reply!
