### ISSUE TITLE
Depth rendering in NeRF units

### ISSUE THREAD

**Issue by saunair** [NVlabs/instant-ngp#934]
Hello Authors, 
I have been using this code for a while now, and thank you guys for that!
My question is, when I set the rendering mode to `depth` in python, the values are set between 0-255. How do I convert the depths into the NeRF coordinate system's units? Or extracting the raw depth works too

**Comment by Tom94** [comment]
Hi, if you obtain the depth map using `render(..., linear=True)`, then the resulting numpy array already contains floating point depth values in the original NeRF scene's units.

**Comment by saunair** [comment]
Got it, that works. Thanks @Tom94!

**Comment by Harper714** [comment]
@saunair 
Hi, could you share how to set the rendering mode to depth in python? Many thanks!

**Comment by kafei123456** [comment]
> Got it, that works. Thanks @Tom94!

Hello. I use "render()" to get depth image, but it has 4 channels.  How do you deal with this problem?

**Comment by CaptainEven** [comment]
> Hello Authors, I have been using this code for a while now, and thank you guys for that! My question is, when I set the rendering mode to `depth` in python, the values are set between 0-255. How do I convert the depths into the NeRF coordinate system's units? Or extracting the raw depth works too

Hi, do you know how to render depth with python in run.py? how to set the params or pass args to the render() function?

**Comment by CaptainEven** [comment]
> linear=True

 

> > Got it, that works. Thanks @Tom94!
> 
> Hello. I use "render()" to get depth image, but it has 4 channels. How do you deal with this problem?

I got the same problem, have you solved it yet?

**Comment by kafei123456** [comment]
> > linear=True
> 
> > > Got it, that works. Thanks @Tom94!
> > 
> > 
> > Hello. I use "render()" to get depth image, but it has 4 channels. How do you deal with this problem?
> 
> I got the same problem, have you solved it yet?

testbed.render_mode = ngp.Depth 
depth = testbed.render(linear=True)#(width,height)#,1,False)
depth /=scale_trans
print("ddd=",depth.shape)
with open("11.txt","w") as f:
    for i in range(depth.shape[0]):
        for j in range(depth.shape[1]):
            #print(depth_img[i,j])
            if depth[i,j,0]!=0.0:
                f.write( str(i)+" "+str(j)+" "+str(depth[i,j,0])+"\n")
This is my code. “scale_trans” = 0.0004. I try to visualize the depth, but it  work not well for me. You can try it ! If this work in your project please tell me the luck message.
