### ISSUE TITLE
Colmap stuck at one point

### ISSUE THREAD

**Issue by akssieg** [NVlabs/instant-ngp#937]
After running the command: `python scripts/colmap2nerf.py --images data/nerf/test_jpg/  --run_colmap --out data/nerf/test_jpg/transform.json` colmap is showing the below same output and it is doing this for more than 30 minutes. Is this an expected behaviour or is there something wrong with my images?

`==============================================================================
Registering image #27 (3)
==============================================================================

  => Image sees 2215 / 6021 points
  => Could not register, trying another image.

==============================================================================
Registering image #35 (3)
==============================================================================

  => Image sees 1821 / 6137 points
  => Could not register, trying another image.

==============================================================================
Registering image #26 (3)
==============================================================================

  => Image sees 923 / 5678 points
  => Could not register, trying another image.

==============================================================================
Registering image #36 (3)
==============================================================================

  => Image sees 565 / 4529 points
  => Could not register, trying another image.

==============================================================================
Registering image #34 (3)
==============================================================================

  => Image sees 372 / 6939 points
  => Could not register, trying another image.

==============================================================================
Registering image #9 (3)
==============================================================================

  => Image sees 169 / 4640 points
  => Could not register, trying another image.

==============================================================================
Registering image #10 (3)
==============================================================================

  => Image sees 147 / 6739 points
  => Could not register, trying another image.

==============================================================================
Registering image #25 (3)
==============================================================================

  => Image sees 98 / 5791 points
  => Could not register, trying another image.

==============================================================================
Registering image #33 (3)
==============================================================================

  => Image sees 97 / 6360 points
  => Could not register, trying another image.

==============================================================================
Registering image #21 (3)
==============================================================================

  => Image sees 45 / 6543 points
  => Could not register, trying another image.

==============================================================================
Retriangulation
==============================================================================

  => Completed observations: 0
  => Merged observations: 0
  => Retriangulated observations: 0

==============================================================================
Global bundle adjustment
==============================================================================

iter      cost      cost_change  |gradient|   |step|    tr_ratio  tr_radius  ls_iter  iter_time  total_time
   0  1.694399e+03    0.00e+00    1.87e+00   0.00e+00   0.00e+00  1.00e+04        0    1.13e-02    1.99e-02
   1  1.694399e+03    5.15e-07    3.87e-02   8.21e-05   1.00e+00  3.00e+04        1    1.66e-02    3.65e-02

Bundle adjustment report
------------------------
    Residuals : 14536
   Parameters : 10913
   Iterations : 2
         Time : 0.0369098 [s]
 Initial cost : 0.341417 [px]
   Final cost : 0.341417 [px]
  Termination : Convergence

  => Completed observations: 0
  => Merged observations: 0
  => Filtered observations: 0
  => Changed observations: 0.000000
  => Filtered images: 0
`

Please let me know if I missed something during installation or during photo capture.

**Comment by jtas01** [comment]
Did you get a solution to this?
