### ISSUE TITLE
pyngp, ImportError on pyngp.cpython-37m-x86_64-linux-gnu.so: undefined symbol

### ISSUE THREAD

**Issue by smtabatabaie** [NVlabs/instant-ngp#950]
I'm trying to run it on Google Colab, and I'm following this guide: 
https://github.com/NVlabs/instant-ngp/blob/master/notebooks/instant_ngp.ipynb
Everything builds without any errors, when I try to run the run.py code (which is the 8th step of the mentioned link) I get this error:
```
Traceback (most recent call last):
  File "scripts/run.py", line 29, in <module>
    import pyngp as ngp # noqa
ImportError: /content/instant-ngp/build/pyngp.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK3ngp7Testbed16crop_box_cornersEb

```
I saw this issue in which the compiler couldn't find pyngp and there was a suggestion to specify the build folder #43 , so I also tried adding the lines to specify the build folder in run.py, but still no luck.
```
pyngp_path = '\build'
sys.path.append(pyngp_path)
import pyngp as ngp  # this line should already be there near the top of the code

```
I'd appreciate it if someone could help me with this.

**Comment by domef** [comment]
I'm having the same problem.

**Comment by domef** [comment]
I just found out that `instant-ngp/build/testbed` works.

**Comment by smtabatabaie** [comment]
> I just found out that `instant-ngp/build/testbed` works.

Thanks @domef , you mean I should set my path to build/testbed in run.py?

**Comment by domef** [comment]
I see now that `testbed` has many less options than `run.py`, but at the moment I think it's a good fallback.

**Comment by smtabatabaie** [comment]
That's unfortunate, If @andreykramer who's wrote the guide could help us it would be great.

**Comment by domef** [comment]
I think I will try to compile some older versions of instant-ngp and see if they work.

**Comment by domef** [comment]
I managed to run `run.py` and train on the fox dataset in headless mode by checking out the commit [add notebook with guide for execution in colab](https://github.com/NVlabs/instant-ngp/commit/50ed131f0e296801d4b3d09ff58295add2af42fa) :  `git checkout 50ed131f0e296801d4b3d09ff58295add2af42fa`.

**Comment by smtabatabaie** [comment]
T

> I managed to run `run.py` and train on the fox dataset in headless mode by checking out the commit [add notebook with guide for execution in colab](https://github.com/NVlabs/instant-ngp/commit/50ed131f0e296801d4b3d09ff58295add2af42fa) : `git checkout 50ed131f0e296801d4b3d09ff58295add2af42fa`.

Thanks very much, saved my day!

**Comment by taruntiwar** [comment]
Can you please explain to me how you managed to run `run.py` in colab notebook
Thank you

**Comment by domef** [comment]
I followed the instructions in https://github.com/NVlabs/instant-ngp/blob/master/notebooks/instant_ngp.ipynb with the following branch https://github.com/NVlabs/instant-ngp/commit/50ed131f0e296801d4b3d09ff58295add2af42fa.

**Comment by domef** [comment]
I just verified that the last working commit is `25dec33c253f035485bb2e1f8563e12ef3134e8b`.

**Comment by andreykramer** [comment]
> I just verified that the last working commit is `25dec33c253f035485bb2e1f8563e12ef3134e8b`.

Thanks, this sure will be helpful to find out what's wrong. 



> That's unfortunate, If @andreykramer who's wrote the guide could help us it would be great.

Unfortunately I don't know this repo deeply enough to have a clue of what may have broken the compilation nor how to fix it in the guide.

**Comment by sumanttyagi** [comment]
i am also facing the same issue please guide me how to solve this problem ? to train the model ?

**Comment by domef** [comment]
> I followed the instructions in https://github.com/NVlabs/instant-ngp/blob/master/notebooks/instant_ngp.ipynb with the following branch [50ed131](https://github.com/NVlabs/instant-ngp/commit/50ed131f0e296801d4b3d09ff58295add2af42fa).

Follow the instructions specified in the notebook but use the same commit I used.

**Comment by saisurbehera** [comment]
I get the same error with python with headless even with the  branch

**Comment by akbazuka** [comment]
Likewise, just tried to run it today and got issues with both of the suggested branches.

**Comment by SamDM** [comment]
Hi, I made a PR which fixes this issue, in the meantime, see here: https://github.com/NVlabs/instant-ngp/pull/991
