### ISSUE TITLE
More sensitive to sparse inputs than original NeRF?

### ISSUE THREAD

**Issue by Harper714** [NVlabs/instant-ngp#959]
Hi, thanks for the excellent work.

I found that for the same relatively sparse inputs, instant-ngp produces obviously worse results than the original NeRF. I want to ask if it is indeed the limitation of instant-ngp, and what do you think the reason is?
My test data are outdoor scenes with a far background like the sky.

**Comment by JordanMakesMaps** [comment]
@Harper714 do you have any images for qualitative comparison?

**Comment by Harper714** [comment]
@JordanMakesMaps  

Thanks for your quick reply. I carefully re-test my data, and found the problem is not caused by sparse inputs but outdoor images.

Sorry for the mistake. I will close the issue.
