### ISSUE TITLE
'n_dims_to_encode' error

### ISSUE THREAD

**Issue by aoliao12138** [NVlabs/instant-ngp#96]
The program gives me the following error and I don´t know how to solve it.

02:10:56 ERROR    Uncaught exception: CompositeEncoding: may only leave 'n_dims_to_encode' unspecified for a single nested encoding

**Comment by Tom94** [comment]
Hi there, whenever you pull the latest changes, you need to also update submodules or there'll be a version mismatch that can cause issues like this.

```
git submodule sync --recursive
git submodule update --recursive
```

Please feel free to re-open the issue if you still have this problem.
