### ISSUE TITLE
Suggestions for outdoor scenes

### ISSUE THREAD

**Issue by Harper714** [NVlabs/instant-ngp#975]
Hi, is there any tips for outdoor forward-facing scenes, especially unbounded scenes with far things like the sky?

**Comment by JordanMakesMaps** [comment]
There is a docker container on the readme, and tutorials on youtube on how to install and getting running using the docker container.

**Comment by Harper714** [comment]
If it is possible to add NDC conversion to improve the quality of unbounded forward-facing scenes?
