### ISSUE TITLE
NeRF rays seem to not reliably start at the camera.

### ISSUE THREAD

**Issue by mcourteaux** [NVlabs/instant-ngp#976]
I'm facing an issue where (due to small scene `scale`), I miss a part of near geometry. In classical graphics, it would resemble the near plane being too far out. However, as this is a ray-marching style of rendering, the problem seems to be of different kind.

Here is a screenshot of the issue:
![image](https://user-images.githubusercontent.com/845012/192306398-2a657ebc-e33d-4596-b546-437d2ed4630d.png)
This view is exactly one of the input views from the training dataset (obtained by pressing `G` twice on the keyboard (to toggle ground truth views)).

Now, if I move back a tiny little bit, the geometry reappears, so it seems that the model is correctly modelling it, but just the rendering has some problem:
![image](https://user-images.githubusercontent.com/845012/192307086-f8eb0d84-c3fe-4e82-b2ba-a35b7f16fe1f.png)

I was digging through the code and the only suspect I found so far is this:
https://github.com/NVlabs/instant-ngp/blob/e1d33a42a4de0b24237685f2ebdc07bcef1ecae9/src/testbed_nerf.cu#L1960-L2039
Especially near the end, where `advance_pos_nerf` kernel is immedately called. However, I commented out this call, compiled, and tested, but no luck.

Any idea what is going wrong?

**Comment by mcourteaux** [comment]
Note that this looks like the missing part of the geometry looks like a cut-out sphere. As if the first sample of the ray is initialized somewhere at `r.o + small_number * r.d`.

**Comment by mcourteaux** [comment]
Basically, this `small_number` should scale along with the scene `scale` from the `transforms.json` I think... But I don't know where this happens in the code yet.

**Comment by mcourteaux** [comment]
[scene_lone_monk_for_github_issue.zip](https://github.com/NVlabs/instant-ngp/files/9647972/scene_lone_monk_for_github_issue.zip)

**Comment by sumanttyagi** [comment]
@mcourteaux even i do spot this issue ...by changing to 0.01 where should i make these changes ?

**Comment by mcourteaux** [comment]
Well, I literally linked the file and line number in my last post. [instant-ngp/src/testbed_nerf.cu](https://github.com/NVlabs/instant-ngp/blob/e1d33a42a4de0b24237685f2ebdc07bcef1ecae9/src/testbed_nerf.cu#L47)

**Comment by mcourteaux** [comment]
Thanks Thomas! Appreciated!
