### ISSUE TITLE
About CMAKE and Vulkin Settings for DLSS

### ISSUE THREAD

**Issue by T-Photoworks** [NVlabs/instant-ngp#982]
I'm a beginner, just started with instant-ngp a few weeks ago.I'm new to python and writing code. 
So I have a question.
My instant-ngp training screen doesn't have DLSS. 
It was written on GitHub that CMAKE and Vulkan must be related in order to use DLSS. 
I installed VulkanSDK. 
Then the path was automatically created in the environment variable. 
But still dosenot make DLSS appear. Is there something wrong with my Vulkan settings?
Is there something wrong with my Vulkan configuration? 
Captured my environment variables and VulkinSDK installation settings. Please make good suggestions.
![220930Vulkin環境変数](https://user-images.githubusercontent.com/25383398/193175366-7d966bad-8965-4fff-9ed4-37b70efb9e99.JPG)
![vulkanSDk](https://user-images.githubusercontent.com/25383398/193175372-fbd3a5c5-987c-4272-9c82-0d2da9d198b0.JPG)

**Comment by barney2074** [comment]
yes, it can be a bit difficult to get this working
In Linux- there is the 'vulkaninfo' command which is useful to check if its working
There are some equivalents on Windows, although I have not tried them- I don't know if the 'Vulkan Configurator' you've shown checks the same thing

**Comment by T-Photoworks** [comment]
> 'Vulkan Configurator'

**Comment by T-Photoworks** [comment]
Thank you.  I'll try searching for 'Vulkan Configurator'.

**Comment by T-Photoworks** [comment]
I found the following description Do I just type this code at the VS prompt?

set(ENV{VULKAN_SDK} "Path/To/Vulkan/Version/Installation")
find_package(Vulkan REQUIRED)
target_link_libraries(target ${Vulkan_LIBRARIES})

**Comment by T-Photoworks** [comment]
Hi Copied part of my CMAKE.text. Are there any issues with this?

add_library(ngp STATIC ${NGP_SOURCES})
set_target_properties(ngp PROPERTIES CUDA_RESOLVE_DEVICE_SYMBOLS ON CUDA_SEPARABLE_COMPILATION ON)
target_compile_definitions(ngp PUBLIC ${NGP_DEFINITIONS})
target_compile_options(ngp PUBLIC $<$<COMPILE_LANGUAGE:CUDA>:${CUDA_NVCC_FLAGS}>)
target_include_directories(ngp PUBLIC ${NGP_INCLUDE_DIRECTORIES})
target_link_directories(ngp PUBLIC ${NGP_LINK_DIRECTORIES})
target_link_libraries(ngp PUBLIC ${NGP_LIBRARIES} tiny-cuda-nn)

add_executable(testbed src/main.cu)
target_link_libraries(testbed PRIVATE ngp)

# Copy DLSS shared libraries
if (NGP_VULKAN)
	if (CMAKE_BUILD_TYPE STREQUAL "Debug")
		set(NGX_BUILD_DIR "dev")
	else()
		set(NGX_BUILD_DIR "rel")
	endif()

	if (MSVC)
		add_custom_command(TARGET testbed POST_BUILD
			COMMAND ${CMAKE_COMMAND} -E copy "${CMAKE_CURRENT_SOURCE_DIR}/dependencies/dlss/lib/Windows_x86_64/${NGX_BUILD_DIR}/nvngx_dlss.dll" $<TARGET_FILE_DIR:testbed>
			COMMAND_EXPAND_LISTS
		)
	else()
		file(GLOB DLSS_SOS "${CMAKE_CURRENT_SOURCE_DIR}/dependencies/dlss/lib/Linux_x86_64/${NGX_BUILD_DIR}/libnvidia-ngx-dlss.so.*")
		add_custom_command(TARGET testbed POST_BUILD
			COMMAND ${CMAKE_COMMAND} -E copy ${DLSS_SOS} $<TARGET_FILE_DIR:testbed>
			COMMAND_EXPAND_LISTS
		)
	endif()
